/*
    Automatically generated by Fault
    Do not modify.
    Generated on: 2026-02-26 18:58:59
*/
/* FAULT METADATA: '{"boundaryCount":2,"sout":"sout","order":[{"width":1,"kind":"input","name":"D","ordinal":0},{"width":1,"kind":"dff","name":"_6_","ordinal":0},{"width":1,"kind":"dff","name":"_7_","ordinal":0},{"width":1,"kind":"output","name":"Q","ordinal":0}],"sin":"sin","shift":"shift","internalCount":2}' END FAULT METADATA */
/* Generated by Yosys 0.58+35 (git sha1 9a12d9255, clang++ 18.1.3 -fPIC -O3) */

module registersQueue(clk, rst, D, Q, sin, shift, sout, tck, test);
  input clk;
  wire clk;
  input rst;
  wire rst;
  input D;
  wire D;
  output Q;
  wire Q;
  input sin;
  wire sin;
  input shift;
  wire shift;
  output sout;
  wire sout;
  input tck;
  wire tck;
  input test;
  wire test;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire \__BoundaryScanRegister_input__0__.sout ;
  wire \__uuf__.Q1 ;
  wire \__uuf__._0_ ;
  wire \__uuf__._1_ ;
  wire \__uuf__._2_ ;
  wire \__uuf__._3_ ;
  wire \__uuf__.__clk_source__ ;
  sg13g2_mux2_1 _05_ (
    .A0(D),
    .A1(\__BoundaryScanRegister_input__0__.sout ),
    .S(test),
    .X(_02_)
  );
  sg13g2_mux2_1 _06_ (
    .A0(_02_),
    .A1(sin),
    .S(shift),
    .X(_00_)
  );
  sg13g2_mux2_1 _07_ (
    .A0(clk),
    .A1(tck),
    .S(test),
    .X(\__uuf__.__clk_source__ )
  );
  sg13g2_mux2_1 _08_ (
    .A0(_02_),
    .A1(\__BoundaryScanRegister_input__0__.sout ),
    .S(shift),
    .X(_01_)
  );
  sg13g2_dfrbp_1 _09_ (
    .CLK(tck),
    .D(Q),
    .Q(sout),
    .Q_N(_04_),
    .RESET_B(rst)
  );
  sg13g2_dfrbp_1 _10_ (
    .CLK(tck),
    .D(_00_),
    .Q(\__BoundaryScanRegister_input__0__.sout ),
    .Q_N(_03_),
    .RESET_B(rst)
  );
  sg13g2_inv_1 \__uuf__._4_  (
    .A(rst),
    .Y(\__uuf__._0_ )
  );
  sg13g2_inv_1 \__uuf__._5_  (
    .A(rst),
    .Y(\__uuf__._1_ )
  );
  sg13g2_dfrbp_1 \__uuf__._6_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_01_),
    .Q(\__uuf__.Q1 ),
    .Q_N(\__uuf__._3_ ),
    .RESET_B(\__uuf__._0_ )
  );
  sg13g2_dfrbp_1 \__uuf__._7_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(\__uuf__.Q1 ),
    .Q(Q),
    .Q_N(\__uuf__._2_ ),
    .RESET_B(\__uuf__._1_ )
  );
endmodule

