/*
    Automatically generated by Fault
    Do not modify.
    Generated on: 2025-12-20 15:33:04
*/
/* FAULT METADATA: '{"shift":"shift","sout":"sout","boundaryCount":2,"order":[{"ordinal":0,"width":1,"kind":"input","name":"D"},{"ordinal":0,"width":1,"kind":"output","name":"Q"}],"internalCount":0,"sin":"sin"}' END FAULT METADATA */
/* Generated by Yosys 0.58+35 (git sha1 9a12d9255, clang++ 18.1.3 -fPIC -O3) */

module registersQueue(clk, rst, D, Q, sin, shift, sout, tck, test);
  input clk;
  wire clk;
  input rst;
  wire rst;
  input D;
  wire D;
  output Q;
  wire Q;
  input sin;
  wire sin;
  input shift;
  wire shift;
  output sout;
  wire sout;
  input tck;
  wire tck;
  input test;
  wire test;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire D__dout;
  wire \__BoundaryScanRegister_input__0__.sout ;
  wire \__uuf__.Q1 ;
  wire \__uuf__._0_ ;
  wire \__uuf__._1_ ;
  wire \__uuf__._2_ ;
  wire \__uuf__._3_ ;
  sg13g2_inv_1 _06_ (
    .A(rst),
    .Y(_00_)
  );
  sg13g2_mux2_1 _07_ (
    .A0(D),
    .A1(\__BoundaryScanRegister_input__0__.sout ),
    .S(test),
    .X(D__dout)
  );
  sg13g2_mux2_1 _08_ (
    .A0(D__dout),
    .A1(sin),
    .S(shift),
    .X(_02_)
  );
  sg13g2_mux2_1 _09_ (
    .A0(Q),
    .A1(\__BoundaryScanRegister_input__0__.sout ),
    .S(shift),
    .X(_03_)
  );
  sg13g2_inv_1 _10_ (
    .A(rst),
    .Y(_01_)
  );
  sg13g2_dfrbp_1 _11_ (
    .CLK(tck),
    .D(_02_),
    .Q(\__BoundaryScanRegister_input__0__.sout ),
    .Q_N(_05_),
    .RESET_B(_00_)
  );
  sg13g2_dfrbp_1 _12_ (
    .CLK(tck),
    .D(_03_),
    .Q(sout),
    .Q_N(_04_),
    .RESET_B(_01_)
  );
  sg13g2_inv_1 \__uuf__._4_  (
    .A(rst),
    .Y(\__uuf__._0_ )
  );
  sg13g2_inv_1 \__uuf__._5_  (
    .A(rst),
    .Y(\__uuf__._1_ )
  );
  sg13g2_dfrbp_1 \__uuf__._6_  (
    .CLK(clk),
    .D(D__dout),
    .Q(\__uuf__.Q1 ),
    .Q_N(\__uuf__._3_ ),
    .RESET_B(\__uuf__._0_ )
  );
  sg13g2_dfrbp_1 \__uuf__._7_  (
    .CLK(clk),
    .D(\__uuf__.Q1 ),
    .Q(Q),
    .Q_N(\__uuf__._2_ ),
    .RESET_B(\__uuf__._1_ )
  );
endmodule

