/* Generated by Yosys 0.58+35 (git sha1 9a12d9255, clang++ 18.1.3 -fPIC -O3) */

(* top =  1  *)
(* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/registerQueue/registersQueue.v:1.1-22.10" *)
module registersQueue(clk, rst, D, Q);
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/registerQueue/registersQueue.v:2.11-2.14" *)
  input clk;
  wire clk;
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/registerQueue/registersQueue.v:3.11-3.14" *)
  input rst;
  wire rst;
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/registerQueue/registersQueue.v:4.11-4.12" *)
  input D;
  wire D;
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/registerQueue/registersQueue.v:5.12-5.13" *)
  output Q;
  wire Q;
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/registerQueue/registersQueue.v:7.10-7.12" *)
  wire Q1;
  (* hdlname = "reg1 D" *)
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/registerQueue/register.v:4.11-4.12" *)
  wire \reg1.D ;
  (* hdlname = "reg1 Q" *)
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/registerQueue/register.v:5.16-5.17" *)
  wire \reg1.Q ;
  (* hdlname = "reg1 clk" *)
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/registerQueue/register.v:2.11-2.14" *)
  wire \reg1.clk ;
  (* hdlname = "reg1 rst" *)
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/registerQueue/register.v:3.11-3.14" *)
  wire \reg1.rst ;
  (* hdlname = "reg2 D" *)
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/registerQueue/register.v:4.11-4.12" *)
  wire \reg2.D ;
  (* hdlname = "reg2 Q" *)
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/registerQueue/register.v:5.16-5.17" *)
  wire \reg2.Q ;
  (* hdlname = "reg2 clk" *)
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/registerQueue/register.v:2.11-2.14" *)
  wire \reg2.clk ;
  (* hdlname = "reg2 rst" *)
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/registerQueue/register.v:3.11-3.14" *)
  wire \reg2.rst ;
  sg13g2_inv_1 _4_ (
    .A(rst),
    .Y(_0_)
  );
  sg13g2_inv_1 _5_ (
    .A(rst),
    .Y(_1_)
  );
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/registerQueue/register.v:8.5-13.8" *)
  sg13g2_dfrbp_1 _6_ (
    .CLK(clk),
    .D(D),
    .Q(\reg1.Q ),
    .Q_N(_3_),
    .RESET_B(_0_)
  );
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/registerQueue/register.v:8.5-13.8" *)
  sg13g2_dfrbp_1 _7_ (
    .CLK(clk),
    .D(\reg1.Q ),
    .Q(\reg2.Q ),
    .Q_N(_2_),
    .RESET_B(_1_)
  );
  assign \reg1.rst  = rst;
  assign \reg1.clk  = clk;
  assign \reg1.D  = D;
  assign \reg2.rst  = rst;
  assign \reg2.clk  = clk;
  assign \reg2.D  = \reg1.Q ;
  assign Q = \reg2.Q ;
  assign Q1 = \reg1.Q ;
endmodule
