/*
    Automatically generated by Fault
    Do not modify.
    Generated on: 2026-04-01 17:11:51
*/

module b01_scan
(
  line1,
  line2,
  reset,
  outp,
  overflw,
  clock,
  sin,
  shift,
  sout,
  tck,
  test,
  _29_,
  \_29_.d ,
  _30_,
  \_30_.d ,
  _31_,
  \_31_.d ,
  _32_,
  \_32_.d ,
  \__uuf__._70_ ,
  \\__uuf__._70_.d ,
  \__uuf__._71_ ,
  \\__uuf__._71_.d ,
  \__uuf__._72_ ,
  \\__uuf__._72_.d ,
  \__uuf__._73_ ,
  \\__uuf__._73_.d ,
  \__uuf__._74_ ,
  \\__uuf__._74_.d 
);

  input _29_;
  output \_29_.d ;
  input _30_;
  output \_30_.d ;
  input _31_;
  output \_31_.d ;
  input _32_;
  output \_32_.d ;
  input \__uuf__._70_ ;
  output \\__uuf__._70_.d ;
  input \__uuf__._71_ ;
  output \\__uuf__._71_.d ;
  input \__uuf__._72_ ;
  output \\__uuf__._72_.d ;
  input \__uuf__._73_ ;
  output \\__uuf__._73_.d ;
  input \__uuf__._74_ ;
  output \\__uuf__._74_.d ;
  input line1;
  wire line1;
  input line2;
  wire line2;
  input reset;
  wire reset;
  output outp;
  wire outp;
  output overflw;
  wire overflw;
  input clock;
  wire clock;
  input sin;
  wire sin;
  input shift;
  wire shift;
  output sout;
  wire sout;
  input tck;
  wire tck;
  input test;
  wire test;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire \__BoundaryScanRegister_input__0__.dout ;
  wire \__BoundaryScanRegister_input__0__.sout ;
  wire \__BoundaryScanRegister_input__1__.dout ;
  wire \__BoundaryScanRegister_input__1__.sout ;
  wire \__BoundaryScanRegister_output__2__.sin ;
  wire \__BoundaryScanRegister_output__2__.sout ;
  wire \__uuf__._00_ ;
  wire \__uuf__._01_ ;
  wire \__uuf__._02_ ;
  wire \__uuf__._03_ ;
  wire \__uuf__._04_ ;
  wire \__uuf__._05_ ;
  wire \__uuf__._06_ ;
  wire \__uuf__._07_ ;
  wire \__uuf__._08_ ;
  wire \__uuf__._09_ ;
  wire \__uuf__._10_ ;
  wire \__uuf__._11_ ;
  wire \__uuf__._12_ ;
  wire \__uuf__._13_ ;
  wire \__uuf__._14_ ;
  wire \__uuf__._15_ ;
  wire \__uuf__._16_ ;
  wire \__uuf__._17_ ;
  wire \__uuf__._18_ ;
  wire \__uuf__._19_ ;
  wire \__uuf__._20_ ;
  wire \__uuf__._21_ ;
  wire \__uuf__._22_ ;
  wire \__uuf__._23_ ;
  wire \__uuf__._24_ ;
  wire \__uuf__._25_ ;
  wire \__uuf__._26_ ;
  wire \__uuf__._27_ ;
  wire \__uuf__._28_ ;
  wire \__uuf__._29_ ;
  wire \__uuf__._30_ ;
  wire \__uuf__._31_ ;
  wire \__uuf__._32_ ;
  wire \__uuf__._33_ ;
  wire \__uuf__._34_ ;
  wire \__uuf__.__clk_source__ ;
  wire \__uuf__.stato[0] ;
  wire \__uuf__.stato[1] ;

  INV_X1
  _13_
  (
    .I(reset),
    .ZN(_00_)
  );


  MUX2_X1
  _14_
  (
    .I0(line1),
    .I1(\__BoundaryScanRegister_input__0__.sout ),
    .S(test),
    .Z(\__BoundaryScanRegister_input__0__.dout )
  );


  MUX2_X1
  _15_
  (
    .I0(\__BoundaryScanRegister_input__0__.dout ),
    .I1(sin),
    .S(shift),
    .Z(_04_)
  );


  MUX2_X1
  _16_
  (
    .I0(line2),
    .I1(\__BoundaryScanRegister_input__1__.sout ),
    .S(test),
    .Z(\__BoundaryScanRegister_input__1__.dout )
  );


  MUX2_X1
  _17_
  (
    .I0(\__BoundaryScanRegister_input__1__.dout ),
    .I1(\__BoundaryScanRegister_input__0__.sout ),
    .S(shift),
    .Z(_05_)
  );


  MUX2_X1
  _18_
  (
    .I0(outp),
    .I1(\__BoundaryScanRegister_output__2__.sin ),
    .S(shift),
    .Z(_06_)
  );


  MUX2_X1
  _19_
  (
    .I0(overflw),
    .I1(\__BoundaryScanRegister_output__2__.sout ),
    .S(shift),
    .Z(_07_)
  );


  MUX2_X1
  _20_
  (
    .I0(clock),
    .I1(tck),
    .S(test),
    .Z(\__uuf__.__clk_source__ )
  );


  MUX2_X1
  _21_
  (
    .I0(\__uuf__._34_ ),
    .I1(\__uuf__.stato[1] ),
    .S(shift),
    .Z(_12_)
  );


  MUX2_X1
  _22_
  (
    .I0(\__uuf__._33_ ),
    .I1(\__uuf__.stato[0] ),
    .S(shift),
    .Z(_11_)
  );


  MUX2_X1
  _23_
  (
    .I0(\__uuf__._32_ ),
    .I1(overflw),
    .S(shift),
    .Z(_10_)
  );


  MUX2_X1
  _24_
  (
    .I0(\__uuf__._01_ ),
    .I1(outp),
    .S(shift),
    .Z(_09_)
  );


  MUX2_X1
  _25_
  (
    .I0(\__uuf__._00_ ),
    .I1(\__BoundaryScanRegister_input__1__.sout ),
    .S(shift),
    .Z(_08_)
  );


  INV_X1
  _26_
  (
    .I(reset),
    .ZN(_01_)
  );


  INV_X1
  _27_
  (
    .I(reset),
    .ZN(_02_)
  );


  INV_X1
  _28_
  (
    .I(reset),
    .ZN(_03_)
  );

  assign \__BoundaryScanRegister_output__2__.sout  = _29_;
  assign \_29_.d  = _06_;
  assign sout = _30_;
  assign \_30_.d  = _07_;
  assign \__BoundaryScanRegister_input__1__.sout  = _31_;
  assign \_31_.d  = _05_;
  assign \__BoundaryScanRegister_input__0__.sout  = _32_;
  assign \_32_.d  = _04_;

  INV_X1
  \__uuf__._35_ 
  (
    .I(\__uuf__.stato[0] ),
    .ZN(\__uuf__._07_ )
  );


  INV_X1
  \__uuf__._36_ 
  (
    .I(\__uuf__.stato[1] ),
    .ZN(\__uuf__._08_ )
  );


  INV_X1
  \__uuf__._37_ 
  (
    .I(\__BoundaryScanRegister_output__2__.sin ),
    .ZN(\__uuf__._09_ )
  );


  INV_X1
  \__uuf__._38_ 
  (
    .I(reset),
    .ZN(\__uuf__._02_ )
  );


  NOR2_X1
  \__uuf__._39_ 
  (
    .A1(\__BoundaryScanRegister_input__1__.dout ),
    .A2(\__BoundaryScanRegister_input__0__.dout ),
    .ZN(\__uuf__._10_ )
  );


  INV_X1
  \__uuf__._40_ 
  (
    .I(\__uuf__._10_ ),
    .ZN(\__uuf__._11_ )
  );


  AND2_X1
  \__uuf__._41_ 
  (
    .A1(\__BoundaryScanRegister_input__1__.dout ),
    .A2(\__BoundaryScanRegister_input__0__.dout ),
    .Z(\__uuf__._12_ )
  );


  NAND2_X1
  \__uuf__._42_ 
  (
    .A1(\__BoundaryScanRegister_input__1__.dout ),
    .A2(\__BoundaryScanRegister_input__0__.dout ),
    .ZN(\__uuf__._13_ )
  );


  NOR2_X1
  \__uuf__._43_ 
  (
    .A1(\__uuf__._10_ ),
    .A2(\__uuf__._12_ ),
    .ZN(\__uuf__._14_ )
  );


  NAND2_X1
  \__uuf__._44_ 
  (
    .A1(\__uuf__._07_ ),
    .A2(\__uuf__.stato[1] ),
    .ZN(\__uuf__._15_ )
  );


  NAND2_X1
  \__uuf__._45_ 
  (
    .A1(\__BoundaryScanRegister_output__2__.sin ),
    .A2(\__uuf__._15_ ),
    .ZN(\__uuf__._16_ )
  );


  XNOR2_X1
  \__uuf__._46_ 
  (
    .A1(\__uuf__._14_ ),
    .A2(\__uuf__._16_ ),
    .ZN(\__uuf__._00_ )
  );


  NOR3_X1
  \__uuf__._47_ 
  (
    .A1(\__uuf__._07_ ),
    .A2(\__uuf__.stato[1] ),
    .A3(\__uuf__._09_ ),
    .ZN(\__uuf__._17_ )
  );


  AOI21_X1
  \__uuf__._48_ 
  (
    .A1(\__BoundaryScanRegister_input__1__.dout ),
    .A2(\__BoundaryScanRegister_input__0__.dout ),
    .B(\__uuf__.stato[0] ),
    .ZN(\__uuf__._18_ )
  );


  NOR4_X1
  \__uuf__._49_ 
  (
    .A1(\__uuf__._08_ ),
    .A2(\__uuf__._09_ ),
    .A3(\__uuf__._10_ ),
    .A4(\__uuf__._18_ ),
    .ZN(\__uuf__._19_ )
  );


  AOI21_X1
  \__uuf__._50_ 
  (
    .A1(\__uuf__._11_ ),
    .A2(\__uuf__._17_ ),
    .B(\__uuf__._19_ ),
    .ZN(\__uuf__._20_ )
  );


  NOR3_X1
  \__uuf__._51_ 
  (
    .A1(\__uuf__.stato[0] ),
    .A2(\__uuf__._08_ ),
    .A3(\__BoundaryScanRegister_output__2__.sin ),
    .ZN(\__uuf__._21_ )
  );


  NAND2_X1
  \__uuf__._52_ 
  (
    .A1(\__uuf__._12_ ),
    .A2(\__uuf__._21_ ),
    .ZN(\__uuf__._22_ )
  );


  NOR3_X1
  \__uuf__._53_ 
  (
    .A1(\__uuf__._07_ ),
    .A2(\__uuf__.stato[1] ),
    .A3(\__BoundaryScanRegister_output__2__.sin ),
    .ZN(\__uuf__._23_ )
  );


  NOR3_X1
  \__uuf__._54_ 
  (
    .A1(\__uuf__.stato[0] ),
    .A2(\__uuf__.stato[1] ),
    .A3(\__uuf__._09_ ),
    .ZN(\__uuf__._24_ )
  );


  AOI22_X1
  \__uuf__._55_ 
  (
    .A1(\__uuf__._12_ ),
    .A2(\__uuf__._23_ ),
    .B1(\__uuf__._24_ ),
    .B2(\__uuf__._11_ ),
    .ZN(\__uuf__._25_ )
  );


  AOI21_X1
  \__uuf__._56_ 
  (
    .A1(\__uuf__.stato[0] ),
    .A2(\__uuf__._08_ ),
    .B(\__BoundaryScanRegister_output__2__.sin ),
    .ZN(\__uuf__._26_ )
  );


  NAND3_X1
  \__uuf__._57_ 
  (
    .A1(\__uuf__._13_ ),
    .A2(\__uuf__._15_ ),
    .A3(\__uuf__._26_ ),
    .ZN(\__uuf__._27_ )
  );


  NAND4_X1
  \__uuf__._58_ 
  (
    .A1(\__uuf__._20_ ),
    .A2(\__uuf__._22_ ),
    .A3(\__uuf__._25_ ),
    .A4(\__uuf__._27_ ),
    .ZN(\__uuf__._32_ )
  );


  AOI21_X1
  \__uuf__._59_ 
  (
    .A1(\__uuf__._13_ ),
    .A2(\__uuf__._23_ ),
    .B(\__uuf__._19_ ),
    .ZN(\__uuf__._28_ )
  );


  NAND2_X1
  \__uuf__._60_ 
  (
    .A1(\__uuf__._10_ ),
    .A2(\__uuf__._24_ ),
    .ZN(\__uuf__._29_ )
  );


  NOR2_X1
  \__uuf__._61_ 
  (
    .A1(\__uuf__._17_ ),
    .A2(\__uuf__._21_ ),
    .ZN(\__uuf__._30_ )
  );


  NAND3_X1
  \__uuf__._62_ 
  (
    .A1(\__uuf__._28_ ),
    .A2(\__uuf__._29_ ),
    .A3(\__uuf__._30_ ),
    .ZN(\__uuf__._33_ )
  );


  NAND3_X1
  \__uuf__._63_ 
  (
    .A1(\__uuf__._12_ ),
    .A2(\__uuf__._15_ ),
    .A3(\__uuf__._26_ ),
    .ZN(\__uuf__._31_ )
  );


  NAND3_X1
  \__uuf__._64_ 
  (
    .A1(\__uuf__._25_ ),
    .A2(\__uuf__._30_ ),
    .A3(\__uuf__._31_ ),
    .ZN(\__uuf__._34_ )
  );


  NOR3_X1
  \__uuf__._65_ 
  (
    .A1(\__uuf__._07_ ),
    .A2(\__uuf__._08_ ),
    .A3(\__BoundaryScanRegister_output__2__.sin ),
    .ZN(\__uuf__._01_ )
  );


  INV_X1
  \__uuf__._66_ 
  (
    .I(reset),
    .ZN(\__uuf__._03_ )
  );


  INV_X1
  \__uuf__._67_ 
  (
    .I(reset),
    .ZN(\__uuf__._04_ )
  );


  INV_X1
  \__uuf__._68_ 
  (
    .I(reset),
    .ZN(\__uuf__._05_ )
  );


  INV_X1
  \__uuf__._69_ 
  (
    .I(reset),
    .ZN(\__uuf__._06_ )
  );

  assign outp = \__uuf__._70_ ;
  assign \\__uuf__._70_.d  = _08_;
  assign overflw = \__uuf__._71_ ;
  assign \\__uuf__._71_.d  = _09_;
  assign \__uuf__.stato[0]  = \__uuf__._72_ ;
  assign \\__uuf__._72_.d  = _10_;
  assign \__uuf__.stato[1]  = \__uuf__._73_ ;
  assign \\__uuf__._73_.d  = _11_;
  assign \__BoundaryScanRegister_output__2__.sin  = \__uuf__._74_ ;
  assign \\__uuf__._74_.d  = _12_;

endmodule

