/*
    Automatically generated by Fault
    Do not modify.
    Generated on: 2026-04-02 20:43:38
*/
/* FAULT METADATA: '{"boundaryCount":4,"sin":"sin","internalCount":5,"sout":"sout","order":[{"kind":"input","name":"line1","ordinal":0,"width":1},{"kind":"input","name":"line2","ordinal":0,"width":1},{"kind":"dff","name":"_70_","ordinal":0,"width":1},{"kind":"dff","name":"_71_","ordinal":0,"width":1},{"kind":"dff","name":"_72_","ordinal":0,"width":1},{"kind":"dff","name":"_73_","ordinal":0,"width":1},{"kind":"dff","name":"_74_","ordinal":0,"width":1},{"kind":"output","name":"outp","ordinal":0,"width":1},{"kind":"output","name":"overflw","ordinal":0,"width":1}],"shift":"shift"}' END FAULT METADATA */
/* Generated by Yosys 0.57+263 (git sha1 637665c9d, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

module b01_scan(line1, line2, reset, outp, overflw, clock, sin, shift, sout, tck, test);
  input line1;
  wire line1;
  input line2;
  wire line2;
  input reset;
  wire reset;
  output outp;
  wire outp;
  output overflw;
  wire overflw;
  input clock;
  wire clock;
  input sin;
  wire sin;
  input shift;
  wire shift;
  output sout;
  wire sout;
  input tck;
  wire tck;
  input test;
  wire test;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire \__BoundaryScanRegister_input__0__.dout ;
  wire \__BoundaryScanRegister_input__0__.sout ;
  wire \__BoundaryScanRegister_input__1__.dout ;
  wire \__BoundaryScanRegister_input__1__.sout ;
  wire \__BoundaryScanRegister_output__2__.sin ;
  wire \__BoundaryScanRegister_output__2__.sout ;
  wire \__uuf__._00_ ;
  wire \__uuf__._01_ ;
  wire \__uuf__._02_ ;
  wire \__uuf__._03_ ;
  wire \__uuf__._04_ ;
  wire \__uuf__._05_ ;
  wire \__uuf__._06_ ;
  wire \__uuf__._07_ ;
  wire \__uuf__._08_ ;
  wire \__uuf__._09_ ;
  wire \__uuf__._10_ ;
  wire \__uuf__._11_ ;
  wire \__uuf__._12_ ;
  wire \__uuf__._13_ ;
  wire \__uuf__._14_ ;
  wire \__uuf__._15_ ;
  wire \__uuf__._16_ ;
  wire \__uuf__._17_ ;
  wire \__uuf__._18_ ;
  wire \__uuf__._19_ ;
  wire \__uuf__._20_ ;
  wire \__uuf__._21_ ;
  wire \__uuf__._22_ ;
  wire \__uuf__._23_ ;
  wire \__uuf__._24_ ;
  wire \__uuf__._25_ ;
  wire \__uuf__._26_ ;
  wire \__uuf__._27_ ;
  wire \__uuf__._28_ ;
  wire \__uuf__._29_ ;
  wire \__uuf__._30_ ;
  wire \__uuf__._31_ ;
  wire \__uuf__._32_ ;
  wire \__uuf__._33_ ;
  wire \__uuf__._34_ ;
  wire \__uuf__.__clk_source__ ;
  wire \__uuf__.stato[0] ;
  wire \__uuf__.stato[1] ;
  INV_X1 _13_ (
    .I(reset),
    .ZN(_00_)
  );
  MUX2_X1 _14_ (
    .I0(line1),
    .I1(\__BoundaryScanRegister_input__0__.sout ),
    .S(test),
    .Z(\__BoundaryScanRegister_input__0__.dout )
  );
  MUX2_X1 _15_ (
    .I0(\__BoundaryScanRegister_input__0__.dout ),
    .I1(sin),
    .S(shift),
    .Z(_04_)
  );
  MUX2_X1 _16_ (
    .I0(line2),
    .I1(\__BoundaryScanRegister_input__1__.sout ),
    .S(test),
    .Z(\__BoundaryScanRegister_input__1__.dout )
  );
  MUX2_X1 _17_ (
    .I0(\__BoundaryScanRegister_input__1__.dout ),
    .I1(\__BoundaryScanRegister_input__0__.sout ),
    .S(shift),
    .Z(_05_)
  );
  MUX2_X1 _18_ (
    .I0(outp),
    .I1(\__BoundaryScanRegister_output__2__.sin ),
    .S(shift),
    .Z(_06_)
  );
  MUX2_X1 _19_ (
    .I0(overflw),
    .I1(\__BoundaryScanRegister_output__2__.sout ),
    .S(shift),
    .Z(_07_)
  );
  MUX2_X1 _20_ (
    .I0(clock),
    .I1(tck),
    .S(test),
    .Z(\__uuf__.__clk_source__ )
  );
  MUX2_X1 _21_ (
    .I0(\__uuf__._34_ ),
    .I1(\__uuf__.stato[1] ),
    .S(shift),
    .Z(_12_)
  );
  MUX2_X1 _22_ (
    .I0(\__uuf__._33_ ),
    .I1(\__uuf__.stato[0] ),
    .S(shift),
    .Z(_11_)
  );
  MUX2_X1 _23_ (
    .I0(\__uuf__._32_ ),
    .I1(overflw),
    .S(shift),
    .Z(_10_)
  );
  MUX2_X1 _24_ (
    .I0(\__uuf__._01_ ),
    .I1(outp),
    .S(shift),
    .Z(_09_)
  );
  MUX2_X1 _25_ (
    .I0(\__uuf__._00_ ),
    .I1(\__BoundaryScanRegister_input__1__.sout ),
    .S(shift),
    .Z(_08_)
  );
  INV_X1 _26_ (
    .I(reset),
    .ZN(_01_)
  );
  INV_X1 _27_ (
    .I(reset),
    .ZN(_02_)
  );
  INV_X1 _28_ (
    .I(reset),
    .ZN(_03_)
  );
  DFFRNQ_X1 _29_ (
    .CLK(tck),
    .D(_06_),
    .Q(\__BoundaryScanRegister_output__2__.sout ),
    .RN(_00_)
  );
  DFFRNQ_X1 _30_ (
    .CLK(tck),
    .D(_07_),
    .Q(sout),
    .RN(_01_)
  );
  DFFRNQ_X1 _31_ (
    .CLK(tck),
    .D(_05_),
    .Q(\__BoundaryScanRegister_input__1__.sout ),
    .RN(_02_)
  );
  DFFRNQ_X1 _32_ (
    .CLK(tck),
    .D(_04_),
    .Q(\__BoundaryScanRegister_input__0__.sout ),
    .RN(_03_)
  );
  INV_X1 \__uuf__._35_  (
    .I(\__uuf__.stato[0] ),
    .ZN(\__uuf__._07_ )
  );
  INV_X1 \__uuf__._36_  (
    .I(\__uuf__.stato[1] ),
    .ZN(\__uuf__._08_ )
  );
  INV_X1 \__uuf__._37_  (
    .I(\__BoundaryScanRegister_output__2__.sin ),
    .ZN(\__uuf__._09_ )
  );
  INV_X1 \__uuf__._38_  (
    .I(reset),
    .ZN(\__uuf__._02_ )
  );
  NOR2_X1 \__uuf__._39_  (
    .A1(\__BoundaryScanRegister_input__1__.dout ),
    .A2(\__BoundaryScanRegister_input__0__.dout ),
    .ZN(\__uuf__._10_ )
  );
  INV_X1 \__uuf__._40_  (
    .I(\__uuf__._10_ ),
    .ZN(\__uuf__._11_ )
  );
  AND2_X1 \__uuf__._41_  (
    .A1(\__BoundaryScanRegister_input__1__.dout ),
    .A2(\__BoundaryScanRegister_input__0__.dout ),
    .Z(\__uuf__._12_ )
  );
  NAND2_X1 \__uuf__._42_  (
    .A1(\__BoundaryScanRegister_input__1__.dout ),
    .A2(\__BoundaryScanRegister_input__0__.dout ),
    .ZN(\__uuf__._13_ )
  );
  NOR2_X1 \__uuf__._43_  (
    .A1(\__uuf__._10_ ),
    .A2(\__uuf__._12_ ),
    .ZN(\__uuf__._14_ )
  );
  NAND2_X1 \__uuf__._44_  (
    .A1(\__uuf__._07_ ),
    .A2(\__uuf__.stato[1] ),
    .ZN(\__uuf__._15_ )
  );
  NAND2_X1 \__uuf__._45_  (
    .A1(\__BoundaryScanRegister_output__2__.sin ),
    .A2(\__uuf__._15_ ),
    .ZN(\__uuf__._16_ )
  );
  XNOR2_X1 \__uuf__._46_  (
    .A1(\__uuf__._14_ ),
    .A2(\__uuf__._16_ ),
    .ZN(\__uuf__._00_ )
  );
  NOR3_X1 \__uuf__._47_  (
    .A1(\__uuf__._07_ ),
    .A2(\__uuf__.stato[1] ),
    .A3(\__uuf__._09_ ),
    .ZN(\__uuf__._17_ )
  );
  AOI21_X1 \__uuf__._48_  (
    .A1(\__BoundaryScanRegister_input__1__.dout ),
    .A2(\__BoundaryScanRegister_input__0__.dout ),
    .B(\__uuf__.stato[0] ),
    .ZN(\__uuf__._18_ )
  );
  NOR4_X1 \__uuf__._49_  (
    .A1(\__uuf__._08_ ),
    .A2(\__uuf__._09_ ),
    .A3(\__uuf__._10_ ),
    .A4(\__uuf__._18_ ),
    .ZN(\__uuf__._19_ )
  );
  AOI21_X1 \__uuf__._50_  (
    .A1(\__uuf__._11_ ),
    .A2(\__uuf__._17_ ),
    .B(\__uuf__._19_ ),
    .ZN(\__uuf__._20_ )
  );
  NOR3_X1 \__uuf__._51_  (
    .A1(\__uuf__.stato[0] ),
    .A2(\__uuf__._08_ ),
    .A3(\__BoundaryScanRegister_output__2__.sin ),
    .ZN(\__uuf__._21_ )
  );
  NAND2_X1 \__uuf__._52_  (
    .A1(\__uuf__._12_ ),
    .A2(\__uuf__._21_ ),
    .ZN(\__uuf__._22_ )
  );
  NOR3_X1 \__uuf__._53_  (
    .A1(\__uuf__._07_ ),
    .A2(\__uuf__.stato[1] ),
    .A3(\__BoundaryScanRegister_output__2__.sin ),
    .ZN(\__uuf__._23_ )
  );
  NOR3_X1 \__uuf__._54_  (
    .A1(\__uuf__.stato[0] ),
    .A2(\__uuf__.stato[1] ),
    .A3(\__uuf__._09_ ),
    .ZN(\__uuf__._24_ )
  );
  AOI22_X1 \__uuf__._55_  (
    .A1(\__uuf__._12_ ),
    .A2(\__uuf__._23_ ),
    .B1(\__uuf__._24_ ),
    .B2(\__uuf__._11_ ),
    .ZN(\__uuf__._25_ )
  );
  AOI21_X1 \__uuf__._56_  (
    .A1(\__uuf__.stato[0] ),
    .A2(\__uuf__._08_ ),
    .B(\__BoundaryScanRegister_output__2__.sin ),
    .ZN(\__uuf__._26_ )
  );
  NAND3_X1 \__uuf__._57_  (
    .A1(\__uuf__._13_ ),
    .A2(\__uuf__._15_ ),
    .A3(\__uuf__._26_ ),
    .ZN(\__uuf__._27_ )
  );
  NAND4_X1 \__uuf__._58_  (
    .A1(\__uuf__._20_ ),
    .A2(\__uuf__._22_ ),
    .A3(\__uuf__._25_ ),
    .A4(\__uuf__._27_ ),
    .ZN(\__uuf__._32_ )
  );
  AOI21_X1 \__uuf__._59_  (
    .A1(\__uuf__._13_ ),
    .A2(\__uuf__._23_ ),
    .B(\__uuf__._19_ ),
    .ZN(\__uuf__._28_ )
  );
  NAND2_X1 \__uuf__._60_  (
    .A1(\__uuf__._10_ ),
    .A2(\__uuf__._24_ ),
    .ZN(\__uuf__._29_ )
  );
  NOR2_X1 \__uuf__._61_  (
    .A1(\__uuf__._17_ ),
    .A2(\__uuf__._21_ ),
    .ZN(\__uuf__._30_ )
  );
  NAND3_X1 \__uuf__._62_  (
    .A1(\__uuf__._28_ ),
    .A2(\__uuf__._29_ ),
    .A3(\__uuf__._30_ ),
    .ZN(\__uuf__._33_ )
  );
  NAND3_X1 \__uuf__._63_  (
    .A1(\__uuf__._12_ ),
    .A2(\__uuf__._15_ ),
    .A3(\__uuf__._26_ ),
    .ZN(\__uuf__._31_ )
  );
  NAND3_X1 \__uuf__._64_  (
    .A1(\__uuf__._25_ ),
    .A2(\__uuf__._30_ ),
    .A3(\__uuf__._31_ ),
    .ZN(\__uuf__._34_ )
  );
  NOR3_X1 \__uuf__._65_  (
    .A1(\__uuf__._07_ ),
    .A2(\__uuf__._08_ ),
    .A3(\__BoundaryScanRegister_output__2__.sin ),
    .ZN(\__uuf__._01_ )
  );
  INV_X1 \__uuf__._66_  (
    .I(reset),
    .ZN(\__uuf__._03_ )
  );
  INV_X1 \__uuf__._67_  (
    .I(reset),
    .ZN(\__uuf__._04_ )
  );
  INV_X1 \__uuf__._68_  (
    .I(reset),
    .ZN(\__uuf__._05_ )
  );
  INV_X1 \__uuf__._69_  (
    .I(reset),
    .ZN(\__uuf__._06_ )
  );
  DFFRNQ_X1 \__uuf__._70_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_08_),
    .Q(outp),
    .RN(\__uuf__._02_ )
  );
  DFFRNQ_X1 \__uuf__._71_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_09_),
    .Q(overflw),
    .RN(\__uuf__._03_ )
  );
  DFFRNQ_X1 \__uuf__._72_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_10_),
    .Q(\__uuf__.stato[0] ),
    .RN(\__uuf__._04_ )
  );
  DFFRNQ_X1 \__uuf__._73_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_11_),
    .Q(\__uuf__.stato[1] ),
    .RN(\__uuf__._05_ )
  );
  DFFRNQ_X1 \__uuf__._74_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_12_),
    .Q(\__BoundaryScanRegister_output__2__.sin ),
    .RN(\__uuf__._06_ )
  );
endmodule

