/* Generated by Yosys 0.57+263 (git sha1 637665c9d, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* top =  1  *)
(* src = "/home/bellee21/progettoEDA/proveSintesi/ITC99/b01/b01.v:1.1-117.10" *)
module b01(line1, line2, reset, outp, overflw, clock);
  (* src = "/home/bellee21/progettoEDA/proveSintesi/ITC99/b01/b01.v:5.7-5.12" *)
  input line1;
  wire line1;
  (* src = "/home/bellee21/progettoEDA/proveSintesi/ITC99/b01/b01.v:6.7-6.12" *)
  input line2;
  wire line2;
  (* src = "/home/bellee21/progettoEDA/proveSintesi/ITC99/b01/b01.v:4.7-4.12" *)
  input reset;
  wire reset;
  (* src = "/home/bellee21/progettoEDA/proveSintesi/ITC99/b01/b01.v:8.12-8.16" *)
  output outp;
  wire outp;
  (* src = "/home/bellee21/progettoEDA/proveSintesi/ITC99/b01/b01.v:9.12-9.19" *)
  output overflw;
  wire overflw;
  (* src = "/home/bellee21/progettoEDA/proveSintesi/ITC99/b01/b01.v:3.7-3.12" *)
  input clock;
  wire clock;
  (* src = "/home/bellee21/progettoEDA/proveSintesi/ITC99/b01/b01.v:23.1-114.4" *)
  wire _00_;
  (* src = "/home/bellee21/progettoEDA/proveSintesi/ITC99/b01/b01.v:23.1-114.4" *)
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  (* src = "/home/bellee21/progettoEDA/proveSintesi/ITC99/b01/b01.v:101.7-101.7|/home/bellee21/progettoEDA/proveSintesi/ITC99/b01/b01.v:31.3-112.10|/usr/local/bin/../share/yosys/techmap.v:583.21-583.22" *)
  wire _32_;
  (* src = "/home/bellee21/progettoEDA/proveSintesi/ITC99/b01/b01.v:101.7-101.7|/home/bellee21/progettoEDA/proveSintesi/ITC99/b01/b01.v:31.3-112.10|/usr/local/bin/../share/yosys/techmap.v:583.21-583.22" *)
  wire _33_;
  (* src = "/home/bellee21/progettoEDA/proveSintesi/ITC99/b01/b01.v:101.7-101.7|/home/bellee21/progettoEDA/proveSintesi/ITC99/b01/b01.v:31.3-112.10|/usr/local/bin/../share/yosys/techmap.v:583.21-583.22" *)
  wire _34_;
  (* src = "/home/bellee21/progettoEDA/proveSintesi/ITC99/b01/b01.v:21.11-21.16" *)
  wire \stato[0] ;
  (* src = "/home/bellee21/progettoEDA/proveSintesi/ITC99/b01/b01.v:21.11-21.16" *)
  wire \stato[1] ;
  (* src = "/home/bellee21/progettoEDA/proveSintesi/ITC99/b01/b01.v:21.11-21.16" *)
  wire \stato[2] ;
  INV_X1 _35_ (
    .I(\stato[0] ),
    .ZN(_07_)
  );
  INV_X1 _36_ (
    .I(\stato[1] ),
    .ZN(_08_)
  );
  INV_X1 _37_ (
    .I(\stato[2] ),
    .ZN(_09_)
  );
  INV_X1 _38_ (
    .I(reset),
    .ZN(_02_)
  );
  NOR2_X1 _39_ (
    .A1(line2),
    .A2(line1),
    .ZN(_10_)
  );
  INV_X1 _40_ (
    .I(_10_),
    .ZN(_11_)
  );
  AND2_X1 _41_ (
    .A1(line2),
    .A2(line1),
    .Z(_12_)
  );
  NAND2_X1 _42_ (
    .A1(line2),
    .A2(line1),
    .ZN(_13_)
  );
  NOR2_X1 _43_ (
    .A1(_10_),
    .A2(_12_),
    .ZN(_14_)
  );
  NAND2_X1 _44_ (
    .A1(_07_),
    .A2(\stato[1] ),
    .ZN(_15_)
  );
  NAND2_X1 _45_ (
    .A1(\stato[2] ),
    .A2(_15_),
    .ZN(_16_)
  );
  XNOR2_X1 _46_ (
    .A1(_14_),
    .A2(_16_),
    .ZN(_00_)
  );
  NOR3_X1 _47_ (
    .A1(_07_),
    .A2(\stato[1] ),
    .A3(_09_),
    .ZN(_17_)
  );
  AOI21_X1 _48_ (
    .A1(line2),
    .A2(line1),
    .B(\stato[0] ),
    .ZN(_18_)
  );
  NOR4_X1 _49_ (
    .A1(_08_),
    .A2(_09_),
    .A3(_10_),
    .A4(_18_),
    .ZN(_19_)
  );
  AOI21_X1 _50_ (
    .A1(_11_),
    .A2(_17_),
    .B(_19_),
    .ZN(_20_)
  );
  NOR3_X1 _51_ (
    .A1(\stato[0] ),
    .A2(_08_),
    .A3(\stato[2] ),
    .ZN(_21_)
  );
  NAND2_X1 _52_ (
    .A1(_12_),
    .A2(_21_),
    .ZN(_22_)
  );
  NOR3_X1 _53_ (
    .A1(_07_),
    .A2(\stato[1] ),
    .A3(\stato[2] ),
    .ZN(_23_)
  );
  NOR3_X1 _54_ (
    .A1(\stato[0] ),
    .A2(\stato[1] ),
    .A3(_09_),
    .ZN(_24_)
  );
  AOI22_X1 _55_ (
    .A1(_12_),
    .A2(_23_),
    .B1(_24_),
    .B2(_11_),
    .ZN(_25_)
  );
  AOI21_X1 _56_ (
    .A1(\stato[0] ),
    .A2(_08_),
    .B(\stato[2] ),
    .ZN(_26_)
  );
  NAND3_X1 _57_ (
    .A1(_13_),
    .A2(_15_),
    .A3(_26_),
    .ZN(_27_)
  );
  NAND4_X1 _58_ (
    .A1(_20_),
    .A2(_22_),
    .A3(_25_),
    .A4(_27_),
    .ZN(_32_)
  );
  AOI21_X1 _59_ (
    .A1(_13_),
    .A2(_23_),
    .B(_19_),
    .ZN(_28_)
  );
  NAND2_X1 _60_ (
    .A1(_10_),
    .A2(_24_),
    .ZN(_29_)
  );
  NOR2_X1 _61_ (
    .A1(_17_),
    .A2(_21_),
    .ZN(_30_)
  );
  NAND3_X1 _62_ (
    .A1(_28_),
    .A2(_29_),
    .A3(_30_),
    .ZN(_33_)
  );
  NAND3_X1 _63_ (
    .A1(_12_),
    .A2(_15_),
    .A3(_26_),
    .ZN(_31_)
  );
  NAND3_X1 _64_ (
    .A1(_25_),
    .A2(_30_),
    .A3(_31_),
    .ZN(_34_)
  );
  NOR3_X1 _65_ (
    .A1(_07_),
    .A2(_08_),
    .A3(\stato[2] ),
    .ZN(_01_)
  );
  INV_X1 _66_ (
    .I(reset),
    .ZN(_03_)
  );
  INV_X1 _67_ (
    .I(reset),
    .ZN(_04_)
  );
  INV_X1 _68_ (
    .I(reset),
    .ZN(_05_)
  );
  INV_X1 _69_ (
    .I(reset),
    .ZN(_06_)
  );
  (* src = "/home/bellee21/progettoEDA/proveSintesi/ITC99/b01/b01.v:23.1-114.4" *)
  DFFRNQ_X1 _70_ (
    .CLK(clock),
    .D(_00_),
    .Q(outp),
    .RN(_02_)
  );
  (* src = "/home/bellee21/progettoEDA/proveSintesi/ITC99/b01/b01.v:23.1-114.4" *)
  DFFRNQ_X1 _71_ (
    .CLK(clock),
    .D(_01_),
    .Q(overflw),
    .RN(_03_)
  );
  (* src = "/home/bellee21/progettoEDA/proveSintesi/ITC99/b01/b01.v:23.1-114.4" *)
  DFFRNQ_X1 _72_ (
    .CLK(clock),
    .D(_32_),
    .Q(\stato[0] ),
    .RN(_04_)
  );
  (* src = "/home/bellee21/progettoEDA/proveSintesi/ITC99/b01/b01.v:23.1-114.4" *)
  DFFRNQ_X1 _73_ (
    .CLK(clock),
    .D(_33_),
    .Q(\stato[1] ),
    .RN(_05_)
  );
  (* src = "/home/bellee21/progettoEDA/proveSintesi/ITC99/b01/b01.v:23.1-114.4" *)
  DFFRNQ_X1 _74_ (
    .CLK(clock),
    .D(_34_),
    .Q(\stato[2] ),
    .RN(_06_)
  );
endmodule
