/* Generated by Yosys 0.58+35 (git sha1 9a12d9255, clang++ 18.1.3 -fPIC -O3) */

(* top =  1  *)
(* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/counter/Counter4Bits.v:1.1-48.10" *)
module Counter4Bits(clk, rst, data_out);
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/counter/Counter4Bits.v:2.11-2.14" *)
  input clk;
  wire clk;
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/counter/Counter4Bits.v:3.11-3.14" *)
  input rst;
  wire rst;
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/counter/Counter4Bits.v:4.18-4.26" *)
  output [3:0] data_out;
  wire [3:0] data_out;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/counter/Counter4Bits.v:7.10-7.15" *)
  (* unused_bits = "0" *)
  wire andD2;
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/counter/Counter4Bits.v:7.17-7.22" *)
  (* unused_bits = "0" *)
  wire andD3;
  (* hdlname = "d0 J" *)
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/counter/JkFlipFlop.v:2.11-2.12" *)
  wire \d0.J ;
  (* hdlname = "d0 K" *)
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/counter/JkFlipFlop.v:3.11-3.12" *)
  wire \d0.K ;
  (* hdlname = "d0 Q" *)
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/counter/JkFlipFlop.v:6.16-6.17" *)
  wire \d0.Q ;
  (* hdlname = "d0 clk" *)
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/counter/JkFlipFlop.v:4.11-4.14" *)
  wire \d0.clk ;
  (* hdlname = "d0 rst" *)
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/counter/JkFlipFlop.v:5.11-5.14" *)
  wire \d0.rst ;
  (* hdlname = "d1 J" *)
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/counter/JkFlipFlop.v:2.11-2.12" *)
  wire \d1.J ;
  (* hdlname = "d1 K" *)
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/counter/JkFlipFlop.v:3.11-3.12" *)
  wire \d1.K ;
  (* hdlname = "d1 Q" *)
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/counter/JkFlipFlop.v:6.16-6.17" *)
  wire \d1.Q ;
  (* hdlname = "d1 clk" *)
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/counter/JkFlipFlop.v:4.11-4.14" *)
  wire \d1.clk ;
  (* hdlname = "d1 rst" *)
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/counter/JkFlipFlop.v:5.11-5.14" *)
  wire \d1.rst ;
  (* hdlname = "d2 J" *)
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/counter/JkFlipFlop.v:2.11-2.12" *)
  (* unused_bits = "0" *)
  wire \d2.J ;
  (* hdlname = "d2 K" *)
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/counter/JkFlipFlop.v:3.11-3.12" *)
  (* unused_bits = "0" *)
  wire \d2.K ;
  (* hdlname = "d2 Q" *)
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/counter/JkFlipFlop.v:6.16-6.17" *)
  wire \d2.Q ;
  (* hdlname = "d2 clk" *)
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/counter/JkFlipFlop.v:4.11-4.14" *)
  wire \d2.clk ;
  (* hdlname = "d2 rst" *)
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/counter/JkFlipFlop.v:5.11-5.14" *)
  wire \d2.rst ;
  (* hdlname = "d3 J" *)
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/counter/JkFlipFlop.v:2.11-2.12" *)
  (* unused_bits = "0" *)
  wire \d3.J ;
  (* hdlname = "d3 K" *)
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/counter/JkFlipFlop.v:3.11-3.12" *)
  (* unused_bits = "0" *)
  wire \d3.K ;
  (* hdlname = "d3 Q" *)
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/counter/JkFlipFlop.v:6.16-6.17" *)
  wire \d3.Q ;
  (* hdlname = "d3 clk" *)
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/counter/JkFlipFlop.v:4.11-4.14" *)
  wire \d3.clk ;
  (* hdlname = "d3 rst" *)
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/counter/JkFlipFlop.v:5.11-5.14" *)
  wire \d3.rst ;
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/counter/Counter4Bits.v:6.10-6.14" *)
  wire high;
  INV_X1 _10_ (
    .I(\d0.Q ),
    .ZN(_04_)
  );
  INV_X1 _11_ (
    .I(rst),
    .ZN(_00_)
  );
  NAND2_X1 _12_ (
    .A1(\d1.Q ),
    .A2(\d0.Q ),
    .ZN(_08_)
  );
  NAND3_X1 _13_ (
    .A1(\d2.Q ),
    .A2(\d1.Q ),
    .A3(\d0.Q ),
    .ZN(_09_)
  );
  XNOR2_X1 _14_ (
    .A1(\d3.Q ),
    .A2(_09_),
    .ZN(_07_)
  );
  XNOR2_X1 _15_ (
    .A1(\d2.Q ),
    .A2(_08_),
    .ZN(_06_)
  );
  XOR2_X1 _16_ (
    .A1(\d1.Q ),
    .A2(\d0.Q ),
    .Z(_05_)
  );
  INV_X1 _17_ (
    .I(rst),
    .ZN(_01_)
  );
  INV_X1 _18_ (
    .I(rst),
    .ZN(_02_)
  );
  INV_X1 _19_ (
    .I(rst),
    .ZN(_03_)
  );
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/counter/JkFlipFlop.v:11.5-25.8" *)
  DFFRNQ_X1 _20_ (
    .CLK(clk),
    .D(_04_),
    .Q(\d0.Q ),
    .RN(_00_)
  );
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/counter/JkFlipFlop.v:11.5-25.8" *)
  DFFRNQ_X1 _21_ (
    .CLK(clk),
    .D(_05_),
    .Q(\d1.Q ),
    .RN(_01_)
  );
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/counter/JkFlipFlop.v:11.5-25.8" *)
  DFFRNQ_X1 _22_ (
    .CLK(clk),
    .D(_06_),
    .Q(\d2.Q ),
    .RN(_02_)
  );
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/counter/JkFlipFlop.v:11.5-25.8" *)
  DFFRNQ_X1 _23_ (
    .CLK(clk),
    .D(_07_),
    .Q(\d3.Q ),
    .RN(_03_)
  );
  assign \d1.K  = \d0.Q ;
  assign \d1.J  = \d0.Q ;
  assign \d0.rst  = rst;
  assign \d2.rst  = rst;
  assign \d2.clk  = clk;
  assign \d2.K  = andD2;
  assign \d2.J  = andD2;
  assign \d3.rst  = rst;
  assign \d3.clk  = clk;
  assign \d3.K  = andD3;
  assign \d3.J  = andD3;
  assign \d0.K  = 1'h1;
  assign \d0.J  = 1'h1;
  assign \d1.rst  = rst;
  assign \d1.clk  = clk;
  assign \d0.clk  = clk;
  assign data_out = { \d3.Q , \d2.Q , \d1.Q , \d0.Q  };
  assign high = 1'h1;
endmodule
