/*
    Automatically generated by Fault
    Do not modify.
    Generated on: 2026-02-26 19:24:52
*/
/* FAULT METADATA: '{"boundaryCount":4,"order":[{"width":1,"kind":"dff","name":"_20_","ordinal":0},{"width":1,"kind":"dff","name":"_21_","ordinal":0},{"width":1,"kind":"dff","name":"_22_","ordinal":0},{"width":1,"kind":"dff","name":"_23_","ordinal":0},{"width":4,"kind":"output","name":"data_out","ordinal":0}],"sout":"sout","internalCount":4,"shift":"shift","sin":"sin"}' END FAULT METADATA */
/* Generated by Yosys 0.58+35 (git sha1 9a12d9255, clang++ 18.1.3 -fPIC -O3) */

module Counter4Bits(clk, rst, data_out, sin, shift, sout, tck, test);
  input clk;
  wire clk;
  input rst;
  wire rst;
  output [3:0] data_out;
  wire [3:0] data_out;
  input sin;
  wire sin;
  input shift;
  wire shift;
  output sout;
  wire sout;
  input tck;
  wire tck;
  input test;
  wire test;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire \__BoundaryScanRegister_output__0__.din ;
  wire \__BoundaryScanRegister_output__0__.sin ;
  wire \__BoundaryScanRegister_output__0__.sout ;
  wire \__BoundaryScanRegister_output__1__.din ;
  wire \__BoundaryScanRegister_output__1__.sout ;
  wire \__BoundaryScanRegister_output__2__.din ;
  wire \__BoundaryScanRegister_output__2__.sout ;
  wire \__uuf__._00_ ;
  wire \__uuf__._01_ ;
  wire \__uuf__._02_ ;
  wire \__uuf__._03_ ;
  wire \__uuf__._04_ ;
  wire \__uuf__._05_ ;
  wire \__uuf__._06_ ;
  wire \__uuf__._07_ ;
  wire \__uuf__._08_ ;
  wire \__uuf__._09_ ;
  wire \__uuf__.__clk_source__ ;
  MUX2_X1 _08_ (
    .I0(\__BoundaryScanRegister_output__0__.din ),
    .I1(\__BoundaryScanRegister_output__0__.sin ),
    .S(shift),
    .Z(_00_)
  );
  MUX2_X1 _09_ (
    .I0(\__BoundaryScanRegister_output__1__.din ),
    .I1(\__BoundaryScanRegister_output__0__.sout ),
    .S(shift),
    .Z(_01_)
  );
  MUX2_X1 _10_ (
    .I0(\__BoundaryScanRegister_output__2__.din ),
    .I1(\__BoundaryScanRegister_output__1__.sout ),
    .S(shift),
    .Z(_02_)
  );
  MUX2_X1 _11_ (
    .I0(\__BoundaryScanRegister_output__0__.sin ),
    .I1(\__BoundaryScanRegister_output__2__.sout ),
    .S(shift),
    .Z(_03_)
  );
  MUX2_X1 _12_ (
    .I0(clk),
    .I1(tck),
    .S(test),
    .Z(\__uuf__.__clk_source__ )
  );
  MUX2_X1 _13_ (
    .I0(\__uuf__._07_ ),
    .I1(\__BoundaryScanRegister_output__2__.din ),
    .S(shift),
    .Z(_07_)
  );
  MUX2_X1 _14_ (
    .I0(\__uuf__._06_ ),
    .I1(\__BoundaryScanRegister_output__1__.din ),
    .S(shift),
    .Z(_06_)
  );
  MUX2_X1 _15_ (
    .I0(\__uuf__._05_ ),
    .I1(\__BoundaryScanRegister_output__0__.din ),
    .S(shift),
    .Z(_05_)
  );
  MUX2_X1 _16_ (
    .I0(\__uuf__._04_ ),
    .I1(sin),
    .S(shift),
    .Z(_04_)
  );
  DFFRNQ_X1 _17_ (
    .CLK(tck),
    .D(_03_),
    .Q(sout),
    .RN(rst)
  );
  DFFRNQ_X1 _18_ (
    .CLK(tck),
    .D(_02_),
    .Q(\__BoundaryScanRegister_output__2__.sout ),
    .RN(rst)
  );
  DFFRNQ_X1 _19_ (
    .CLK(tck),
    .D(_00_),
    .Q(\__BoundaryScanRegister_output__0__.sout ),
    .RN(rst)
  );
  DFFRNQ_X1 _20_ (
    .CLK(tck),
    .D(_01_),
    .Q(\__BoundaryScanRegister_output__1__.sout ),
    .RN(rst)
  );
  INV_X1 \__uuf__._10_  (
    .I(\__BoundaryScanRegister_output__0__.din ),
    .ZN(\__uuf__._04_ )
  );
  INV_X1 \__uuf__._11_  (
    .I(rst),
    .ZN(\__uuf__._00_ )
  );
  NAND2_X1 \__uuf__._12_  (
    .A1(\__BoundaryScanRegister_output__1__.din ),
    .A2(\__BoundaryScanRegister_output__0__.din ),
    .ZN(\__uuf__._08_ )
  );
  NAND3_X1 \__uuf__._13_  (
    .A1(\__BoundaryScanRegister_output__2__.din ),
    .A2(\__BoundaryScanRegister_output__1__.din ),
    .A3(\__BoundaryScanRegister_output__0__.din ),
    .ZN(\__uuf__._09_ )
  );
  XNOR2_X1 \__uuf__._14_  (
    .A1(\__BoundaryScanRegister_output__0__.sin ),
    .A2(\__uuf__._09_ ),
    .ZN(\__uuf__._07_ )
  );
  XNOR2_X1 \__uuf__._15_  (
    .A1(\__BoundaryScanRegister_output__2__.din ),
    .A2(\__uuf__._08_ ),
    .ZN(\__uuf__._06_ )
  );
  XOR2_X1 \__uuf__._16_  (
    .A1(\__BoundaryScanRegister_output__1__.din ),
    .A2(\__BoundaryScanRegister_output__0__.din ),
    .Z(\__uuf__._05_ )
  );
  INV_X1 \__uuf__._17_  (
    .I(rst),
    .ZN(\__uuf__._01_ )
  );
  INV_X1 \__uuf__._18_  (
    .I(rst),
    .ZN(\__uuf__._02_ )
  );
  INV_X1 \__uuf__._19_  (
    .I(rst),
    .ZN(\__uuf__._03_ )
  );
  DFFRNQ_X1 \__uuf__._20_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_04_),
    .Q(\__BoundaryScanRegister_output__0__.din ),
    .RN(\__uuf__._00_ )
  );
  DFFRNQ_X1 \__uuf__._21_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_05_),
    .Q(\__BoundaryScanRegister_output__1__.din ),
    .RN(\__uuf__._01_ )
  );
  DFFRNQ_X1 \__uuf__._22_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_06_),
    .Q(\__BoundaryScanRegister_output__2__.din ),
    .RN(\__uuf__._02_ )
  );
  DFFRNQ_X1 \__uuf__._23_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_07_),
    .Q(\__BoundaryScanRegister_output__0__.sin ),
    .RN(\__uuf__._03_ )
  );
  assign data_out = { \__BoundaryScanRegister_output__0__.sin , \__BoundaryScanRegister_output__2__.din , \__BoundaryScanRegister_output__1__.din , \__BoundaryScanRegister_output__0__.din  };
endmodule

