/* Generated by Yosys 0.58+35 (git sha1 9a12d9255, clang++ 18.1.3 -fPIC -O3) */

(* top =  1  *)
(* src = "b04.v:1.1-112.10" *)
module b04(RESTART, AVERAGE, ENABLE, DATA_IN, DATA_OUT, RESET, CLOCK);
  (* src = "b04.v:5.7-5.14" *)
  input RESTART;
  wire RESTART;
  (* src = "b04.v:6.7-6.14" *)
  input AVERAGE;
  wire AVERAGE;
  (* src = "b04.v:7.7-7.13" *)
  input ENABLE;
  wire ENABLE;
  (* src = "b04.v:8.20-8.27" *)
  input [7:0] DATA_IN;
  wire [7:0] DATA_IN;
  (* src = "b04.v:10.14-10.22" *)
  output [7:0] DATA_OUT;
  wire [7:0] DATA_OUT;
  (* src = "b04.v:4.7-4.12" *)
  input RESET;
  wire RESET;
  (* src = "b04.v:3.7-3.12" *)
  input CLOCK;
  wire CLOCK;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  wire _335_;
  (* src = "b04.v:20.38-20.42" *)
  wire [31:0] REG1;
  (* src = "b04.v:20.44-20.48" *)
  wire [31:0] REG2;
  (* src = "b04.v:20.50-20.54" *)
  wire [31:0] REG3;
  (* src = "b04.v:20.56-20.60" *)
  wire [31:0] REG4;
  wire [7:0] RLAST;
  (* src = "b04.v:20.19-20.23" *)
  wire [31:0] RMAX;
  (* src = "b04.v:20.25-20.29" *)
  wire [31:0] RMIN;
  (* onehot = 32'd1 *)
  wire [2:0] stato;
  INV_X1 _336_ (
    .I(DATA_IN[7]),
    .ZN(_132_)
  );
  INV_X1 _337_ (
    .I(RMIN[6]),
    .ZN(_133_)
  );
  INV_X1 _338_ (
    .I(DATA_IN[6]),
    .ZN(_134_)
  );
  INV_X1 _339_ (
    .I(RMIN[5]),
    .ZN(_135_)
  );
  INV_X1 _340_ (
    .I(RMIN[4]),
    .ZN(_136_)
  );
  INV_X1 _341_ (
    .I(DATA_IN[4]),
    .ZN(_137_)
  );
  INV_X1 _342_ (
    .I(RMIN[3]),
    .ZN(_138_)
  );
  INV_X1 _343_ (
    .I(DATA_IN[3]),
    .ZN(_139_)
  );
  INV_X1 _344_ (
    .I(DATA_IN[2]),
    .ZN(_140_)
  );
  INV_X1 _345_ (
    .I(DATA_IN[1]),
    .ZN(_141_)
  );
  INV_X1 _346_ (
    .I(DATA_IN[0]),
    .ZN(_142_)
  );
  INV_X1 _347_ (
    .I(RMAX[30]),
    .ZN(_143_)
  );
  INV_X1 _348_ (
    .I(RMAX[6]),
    .ZN(_144_)
  );
  INV_X1 _349_ (
    .I(RMAX[5]),
    .ZN(_145_)
  );
  INV_X1 _350_ (
    .I(RMAX[4]),
    .ZN(_146_)
  );
  INV_X1 _351_ (
    .I(RMAX[2]),
    .ZN(_147_)
  );
  INV_X1 _352_ (
    .I(RMAX[1]),
    .ZN(_148_)
  );
  INV_X1 _353_ (
    .I(RMAX[0]),
    .ZN(_149_)
  );
  INV_X1 _354_ (
    .I(stato[1]),
    .ZN(_150_)
  );
  INV_X1 _355_ (
    .I(ENABLE),
    .ZN(_151_)
  );
  INV_X1 _356_ (
    .I(RESTART),
    .ZN(_152_)
  );
  INV_X1 _357_ (
    .I(RESET),
    .ZN(_001_)
  );
  NOR2_X1 _358_ (
    .A1(stato[2]),
    .A2(stato[1]),
    .ZN(_153_)
  );
  INV_X1 _359_ (
    .I(_153_),
    .ZN(_000_)
  );
  AOI22_X1 _360_ (
    .A1(REG1[6]),
    .A2(stato[1]),
    .B1(_153_),
    .B2(REG2[6]),
    .ZN(_154_)
  );
  INV_X1 _361_ (
    .I(_154_),
    .ZN(_131_)
  );
  AOI22_X1 _362_ (
    .A1(REG1[5]),
    .A2(stato[1]),
    .B1(_153_),
    .B2(REG2[5]),
    .ZN(_155_)
  );
  INV_X1 _363_ (
    .I(_155_),
    .ZN(_130_)
  );
  AOI22_X1 _364_ (
    .A1(REG1[4]),
    .A2(stato[1]),
    .B1(_153_),
    .B2(REG2[4]),
    .ZN(_156_)
  );
  INV_X1 _365_ (
    .I(_156_),
    .ZN(_129_)
  );
  AOI22_X1 _366_ (
    .A1(REG1[3]),
    .A2(stato[1]),
    .B1(_153_),
    .B2(REG2[3]),
    .ZN(_157_)
  );
  INV_X1 _367_ (
    .I(_157_),
    .ZN(_128_)
  );
  AOI22_X1 _368_ (
    .A1(REG1[2]),
    .A2(stato[1]),
    .B1(_153_),
    .B2(REG2[2]),
    .ZN(_158_)
  );
  INV_X1 _369_ (
    .I(_158_),
    .ZN(_127_)
  );
  AOI22_X1 _370_ (
    .A1(REG1[1]),
    .A2(stato[1]),
    .B1(_153_),
    .B2(REG2[1]),
    .ZN(_159_)
  );
  INV_X1 _371_ (
    .I(_159_),
    .ZN(_126_)
  );
  AOI22_X1 _372_ (
    .A1(REG1[0]),
    .A2(stato[1]),
    .B1(_153_),
    .B2(REG2[0]),
    .ZN(_160_)
  );
  INV_X1 _373_ (
    .I(_160_),
    .ZN(_125_)
  );
  AOI22_X1 _374_ (
    .A1(DATA_IN[7]),
    .A2(stato[1]),
    .B1(_153_),
    .B2(REG1[30]),
    .ZN(_161_)
  );
  INV_X1 _375_ (
    .I(_161_),
    .ZN(_124_)
  );
  AOI22_X1 _376_ (
    .A1(DATA_IN[6]),
    .A2(stato[1]),
    .B1(_153_),
    .B2(REG1[6]),
    .ZN(_162_)
  );
  INV_X1 _377_ (
    .I(_162_),
    .ZN(_123_)
  );
  AOI22_X1 _378_ (
    .A1(DATA_IN[5]),
    .A2(stato[1]),
    .B1(_153_),
    .B2(REG1[5]),
    .ZN(_163_)
  );
  INV_X1 _379_ (
    .I(_163_),
    .ZN(_122_)
  );
  AOI22_X1 _380_ (
    .A1(DATA_IN[4]),
    .A2(stato[1]),
    .B1(_153_),
    .B2(REG1[4]),
    .ZN(_164_)
  );
  INV_X1 _381_ (
    .I(_164_),
    .ZN(_121_)
  );
  AOI22_X1 _382_ (
    .A1(DATA_IN[3]),
    .A2(stato[1]),
    .B1(_153_),
    .B2(REG1[3]),
    .ZN(_165_)
  );
  INV_X1 _383_ (
    .I(_165_),
    .ZN(_120_)
  );
  AOI22_X1 _384_ (
    .A1(DATA_IN[2]),
    .A2(stato[1]),
    .B1(_153_),
    .B2(REG1[2]),
    .ZN(_166_)
  );
  INV_X1 _385_ (
    .I(_166_),
    .ZN(_119_)
  );
  AOI22_X1 _386_ (
    .A1(DATA_IN[1]),
    .A2(stato[1]),
    .B1(_153_),
    .B2(REG1[1]),
    .ZN(_167_)
  );
  INV_X1 _387_ (
    .I(_167_),
    .ZN(_118_)
  );
  AOI22_X1 _388_ (
    .A1(DATA_IN[0]),
    .A2(stato[1]),
    .B1(_153_),
    .B2(REG1[0]),
    .ZN(_168_)
  );
  INV_X1 _389_ (
    .I(_168_),
    .ZN(_117_)
  );
  AOI22_X1 _390_ (
    .A1(RMIN[1]),
    .A2(_141_),
    .B1(RMIN[0]),
    .B2(_142_),
    .ZN(_169_)
  );
  OAI22_X1 _391_ (
    .A1(RMIN[2]),
    .A2(_140_),
    .B1(RMIN[1]),
    .B2(_141_),
    .ZN(_170_)
  );
  AOI22_X1 _392_ (
    .A1(RMIN[3]),
    .A2(_139_),
    .B1(RMIN[2]),
    .B2(_140_),
    .ZN(_171_)
  );
  OAI21_X1 _393_ (
    .A1(_169_),
    .A2(_170_),
    .B(_171_),
    .ZN(_172_)
  );
  AOI22_X1 _394_ (
    .A1(_136_),
    .A2(DATA_IN[4]),
    .B1(_138_),
    .B2(DATA_IN[3]),
    .ZN(_173_)
  );
  AOI22_X1 _395_ (
    .A1(RMIN[4]),
    .A2(_137_),
    .B1(_172_),
    .B2(_173_),
    .ZN(_174_)
  );
  AOI21_X1 _396_ (
    .A1(_135_),
    .A2(DATA_IN[5]),
    .B(_174_),
    .ZN(_175_)
  );
  OAI22_X1 _397_ (
    .A1(_133_),
    .A2(DATA_IN[6]),
    .B1(_135_),
    .B2(DATA_IN[5]),
    .ZN(_176_)
  );
  AOI22_X1 _398_ (
    .A1(RMIN[30]),
    .A2(_132_),
    .B1(_133_),
    .B2(DATA_IN[6]),
    .ZN(_177_)
  );
  OAI21_X1 _399_ (
    .A1(_175_),
    .A2(_176_),
    .B(_177_),
    .ZN(_178_)
  );
  OAI21_X1 _400_ (
    .A1(RMIN[30]),
    .A2(_132_),
    .B(_178_),
    .ZN(_179_)
  );
  AOI22_X1 _401_ (
    .A1(DATA_IN[7]),
    .A2(_143_),
    .B1(RMAX[6]),
    .B2(_134_),
    .ZN(_180_)
  );
  AOI22_X1 _402_ (
    .A1(_139_),
    .A2(RMAX[3]),
    .B1(RMAX[2]),
    .B2(_140_),
    .ZN(_181_)
  );
  AOI22_X1 _403_ (
    .A1(DATA_IN[2]),
    .A2(_147_),
    .B1(_148_),
    .B2(DATA_IN[1]),
    .ZN(_182_)
  );
  NOR2_X1 _404_ (
    .A1(DATA_IN[1]),
    .A2(_148_),
    .ZN(_183_)
  );
  NAND2_X1 _405_ (
    .A1(DATA_IN[0]),
    .A2(_149_),
    .ZN(_184_)
  );
  OAI21_X1 _406_ (
    .A1(_183_),
    .A2(_184_),
    .B(_182_),
    .ZN(_185_)
  );
  OAI22_X1 _407_ (
    .A1(_137_),
    .A2(RMAX[4]),
    .B1(RMAX[3]),
    .B2(_139_),
    .ZN(_186_)
  );
  AOI21_X1 _408_ (
    .A1(_181_),
    .A2(_185_),
    .B(_186_),
    .ZN(_187_)
  );
  OAI22_X1 _409_ (
    .A1(DATA_IN[5]),
    .A2(_145_),
    .B1(_146_),
    .B2(DATA_IN[4]),
    .ZN(_188_)
  );
  AOI22_X1 _410_ (
    .A1(DATA_IN[6]),
    .A2(_144_),
    .B1(_145_),
    .B2(DATA_IN[5]),
    .ZN(_189_)
  );
  OAI21_X1 _411_ (
    .A1(_187_),
    .A2(_188_),
    .B(_189_),
    .ZN(_190_)
  );
  AOI22_X1 _412_ (
    .A1(_132_),
    .A2(RMAX[30]),
    .B1(_180_),
    .B2(_190_),
    .ZN(_191_)
  );
  AND2_X1 _413_ (
    .A1(stato[1]),
    .A2(_191_),
    .Z(_192_)
  );
  AOI22_X1 _414_ (
    .A1(stato[2]),
    .A2(_150_),
    .B1(_179_),
    .B2(_192_),
    .ZN(_193_)
  );
  MUX2_X1 _415_ (
    .I0(DATA_IN[7]),
    .I1(RMIN[30]),
    .S(_193_),
    .Z(_116_)
  );
  MUX2_X1 _416_ (
    .I0(DATA_IN[6]),
    .I1(RMIN[6]),
    .S(_193_),
    .Z(_115_)
  );
  MUX2_X1 _417_ (
    .I0(DATA_IN[5]),
    .I1(RMIN[5]),
    .S(_193_),
    .Z(_114_)
  );
  MUX2_X1 _418_ (
    .I0(DATA_IN[4]),
    .I1(RMIN[4]),
    .S(_193_),
    .Z(_113_)
  );
  MUX2_X1 _419_ (
    .I0(DATA_IN[3]),
    .I1(RMIN[3]),
    .S(_193_),
    .Z(_112_)
  );
  MUX2_X1 _420_ (
    .I0(DATA_IN[2]),
    .I1(RMIN[2]),
    .S(_193_),
    .Z(_111_)
  );
  MUX2_X1 _421_ (
    .I0(DATA_IN[1]),
    .I1(RMIN[1]),
    .S(_193_),
    .Z(_110_)
  );
  MUX2_X1 _422_ (
    .I0(DATA_IN[0]),
    .I1(RMIN[0]),
    .S(_193_),
    .Z(_109_)
  );
  AOI21_X1 _423_ (
    .A1(stato[1]),
    .A2(_191_),
    .B(_153_),
    .ZN(_194_)
  );
  NAND2_X1 _424_ (
    .A1(DATA_IN[7]),
    .A2(_194_),
    .ZN(_195_)
  );
  OAI21_X1 _425_ (
    .A1(_143_),
    .A2(_194_),
    .B(_195_),
    .ZN(_108_)
  );
  NAND2_X1 _426_ (
    .A1(DATA_IN[6]),
    .A2(_194_),
    .ZN(_196_)
  );
  OAI21_X1 _427_ (
    .A1(_144_),
    .A2(_194_),
    .B(_196_),
    .ZN(_107_)
  );
  NAND2_X1 _428_ (
    .A1(DATA_IN[5]),
    .A2(_194_),
    .ZN(_197_)
  );
  OAI21_X1 _429_ (
    .A1(_145_),
    .A2(_194_),
    .B(_197_),
    .ZN(_106_)
  );
  NAND2_X1 _430_ (
    .A1(DATA_IN[4]),
    .A2(_194_),
    .ZN(_198_)
  );
  OAI21_X1 _431_ (
    .A1(_146_),
    .A2(_194_),
    .B(_198_),
    .ZN(_105_)
  );
  NOR2_X1 _432_ (
    .A1(RMAX[3]),
    .A2(_194_),
    .ZN(_199_)
  );
  AOI21_X1 _433_ (
    .A1(_139_),
    .A2(_194_),
    .B(_199_),
    .ZN(_104_)
  );
  NAND2_X1 _434_ (
    .A1(DATA_IN[2]),
    .A2(_194_),
    .ZN(_200_)
  );
  OAI21_X1 _435_ (
    .A1(_147_),
    .A2(_194_),
    .B(_200_),
    .ZN(_103_)
  );
  NAND2_X1 _436_ (
    .A1(DATA_IN[1]),
    .A2(_194_),
    .ZN(_201_)
  );
  OAI21_X1 _437_ (
    .A1(_148_),
    .A2(_194_),
    .B(_201_),
    .ZN(_102_)
  );
  NAND2_X1 _438_ (
    .A1(DATA_IN[0]),
    .A2(_194_),
    .ZN(_202_)
  );
  OAI21_X1 _439_ (
    .A1(_149_),
    .A2(_194_),
    .B(_202_),
    .ZN(_101_)
  );
  NAND2_X1 _440_ (
    .A1(DATA_OUT[7]),
    .A2(_153_),
    .ZN(_203_)
  );
  AND2_X1 _441_ (
    .A1(ENABLE),
    .A2(AVERAGE),
    .Z(_204_)
  );
  AOI22_X1 _442_ (
    .A1(RLAST[7]),
    .A2(_151_),
    .B1(_204_),
    .B2(REG4[30]),
    .ZN(_205_)
  );
  NAND2_X1 _443_ (
    .A1(stato[1]),
    .A2(_152_),
    .ZN(_206_)
  );
  OAI21_X1 _444_ (
    .A1(_205_),
    .A2(_206_),
    .B(_203_),
    .ZN(_100_)
  );
  NAND2_X1 _445_ (
    .A1(DATA_OUT[6]),
    .A2(_153_),
    .ZN(_207_)
  );
  AOI22_X1 _446_ (
    .A1(RLAST[6]),
    .A2(_151_),
    .B1(_204_),
    .B2(REG4[6]),
    .ZN(_208_)
  );
  OAI21_X1 _447_ (
    .A1(_206_),
    .A2(_208_),
    .B(_207_),
    .ZN(_099_)
  );
  NAND2_X1 _448_ (
    .A1(DATA_OUT[5]),
    .A2(_153_),
    .ZN(_209_)
  );
  NOR2_X1 _449_ (
    .A1(_151_),
    .A2(AVERAGE),
    .ZN(_210_)
  );
  NAND2_X1 _450_ (
    .A1(DATA_IN[5]),
    .A2(REG4[5]),
    .ZN(_211_)
  );
  AND2_X1 _451_ (
    .A1(DATA_IN[4]),
    .A2(REG4[4]),
    .Z(_212_)
  );
  NAND2_X1 _452_ (
    .A1(DATA_IN[4]),
    .A2(REG4[4]),
    .ZN(_213_)
  );
  NAND2_X1 _453_ (
    .A1(DATA_IN[3]),
    .A2(REG4[3]),
    .ZN(_214_)
  );
  NAND2_X1 _454_ (
    .A1(DATA_IN[2]),
    .A2(REG4[2]),
    .ZN(_215_)
  );
  INV_X1 _455_ (
    .I(_215_),
    .ZN(_216_)
  );
  NAND2_X1 _456_ (
    .A1(DATA_IN[1]),
    .A2(REG4[1]),
    .ZN(_217_)
  );
  NAND2_X1 _457_ (
    .A1(DATA_IN[0]),
    .A2(REG4[0]),
    .ZN(_218_)
  );
  NOR2_X1 _458_ (
    .A1(DATA_IN[1]),
    .A2(REG4[1]),
    .ZN(_219_)
  );
  XOR2_X1 _459_ (
    .A1(DATA_IN[1]),
    .A2(REG4[1]),
    .Z(_220_)
  );
  OAI21_X1 _460_ (
    .A1(_218_),
    .A2(_219_),
    .B(_217_),
    .ZN(_221_)
  );
  XOR2_X1 _461_ (
    .A1(DATA_IN[2]),
    .A2(REG4[2]),
    .Z(_222_)
  );
  NAND2_X1 _462_ (
    .A1(_221_),
    .A2(_222_),
    .ZN(_223_)
  );
  AOI21_X1 _463_ (
    .A1(_221_),
    .A2(_222_),
    .B(_216_),
    .ZN(_224_)
  );
  XNOR2_X1 _464_ (
    .A1(DATA_IN[3]),
    .A2(REG4[3]),
    .ZN(_225_)
  );
  NOR2_X1 _465_ (
    .A1(_224_),
    .A2(_225_),
    .ZN(_226_)
  );
  OAI21_X1 _466_ (
    .A1(_224_),
    .A2(_225_),
    .B(_214_),
    .ZN(_227_)
  );
  OR2_X1 _467_ (
    .A1(DATA_IN[4]),
    .A2(REG4[4]),
    .Z(_228_)
  );
  NAND2_X1 _468_ (
    .A1(_213_),
    .A2(_228_),
    .ZN(_229_)
  );
  AOI21_X1 _469_ (
    .A1(_227_),
    .A2(_228_),
    .B(_212_),
    .ZN(_230_)
  );
  NOR2_X1 _470_ (
    .A1(DATA_IN[5]),
    .A2(REG4[5]),
    .ZN(_231_)
  );
  XOR2_X1 _471_ (
    .A1(DATA_IN[5]),
    .A2(REG4[5]),
    .Z(_232_)
  );
  OAI21_X1 _472_ (
    .A1(_230_),
    .A2(_231_),
    .B(_211_),
    .ZN(_233_)
  );
  XNOR2_X1 _473_ (
    .A1(DATA_IN[6]),
    .A2(REG4[6]),
    .ZN(_234_)
  );
  XNOR2_X1 _474_ (
    .A1(_233_),
    .A2(_234_),
    .ZN(_235_)
  );
  AOI22_X1 _475_ (
    .A1(RLAST[5]),
    .A2(_151_),
    .B1(_204_),
    .B2(REG4[5]),
    .ZN(_236_)
  );
  NAND2_X1 _476_ (
    .A1(_152_),
    .A2(_236_),
    .ZN(_237_)
  );
  AOI21_X1 _477_ (
    .A1(_210_),
    .A2(_235_),
    .B(_237_),
    .ZN(_238_)
  );
  NAND2_X1 _478_ (
    .A1(RMIN[5]),
    .A2(RMAX[5]),
    .ZN(_239_)
  );
  NOR2_X1 _479_ (
    .A1(_136_),
    .A2(_146_),
    .ZN(_240_)
  );
  NAND2_X1 _480_ (
    .A1(RMIN[3]),
    .A2(RMAX[3]),
    .ZN(_241_)
  );
  AND2_X1 _481_ (
    .A1(RMIN[2]),
    .A2(RMAX[2]),
    .Z(_242_)
  );
  NAND2_X1 _482_ (
    .A1(RMIN[1]),
    .A2(RMAX[1]),
    .ZN(_243_)
  );
  NAND2_X1 _483_ (
    .A1(RMIN[0]),
    .A2(RMAX[0]),
    .ZN(_244_)
  );
  XNOR2_X1 _484_ (
    .A1(RMIN[1]),
    .A2(RMAX[1]),
    .ZN(_245_)
  );
  OAI21_X1 _485_ (
    .A1(_244_),
    .A2(_245_),
    .B(_243_),
    .ZN(_246_)
  );
  NOR2_X1 _486_ (
    .A1(RMIN[2]),
    .A2(RMAX[2]),
    .ZN(_247_)
  );
  NOR2_X1 _487_ (
    .A1(_242_),
    .A2(_247_),
    .ZN(_248_)
  );
  AOI21_X1 _488_ (
    .A1(_246_),
    .A2(_248_),
    .B(_242_),
    .ZN(_249_)
  );
  XNOR2_X1 _489_ (
    .A1(RMIN[3]),
    .A2(RMAX[3]),
    .ZN(_250_)
  );
  OAI21_X1 _490_ (
    .A1(_249_),
    .A2(_250_),
    .B(_241_),
    .ZN(_251_)
  );
  NOR2_X1 _491_ (
    .A1(RMIN[4]),
    .A2(RMAX[4]),
    .ZN(_252_)
  );
  NOR2_X1 _492_ (
    .A1(_240_),
    .A2(_252_),
    .ZN(_253_)
  );
  AOI21_X1 _493_ (
    .A1(_251_),
    .A2(_253_),
    .B(_240_),
    .ZN(_254_)
  );
  NOR2_X1 _494_ (
    .A1(RMIN[5]),
    .A2(RMAX[5]),
    .ZN(_255_)
  );
  XOR2_X1 _495_ (
    .A1(RMIN[5]),
    .A2(RMAX[5]),
    .Z(_256_)
  );
  OAI21_X1 _496_ (
    .A1(_254_),
    .A2(_255_),
    .B(_239_),
    .ZN(_257_)
  );
  XNOR2_X1 _497_ (
    .A1(RMIN[6]),
    .A2(RMAX[6]),
    .ZN(_258_)
  );
  AND2_X1 _498_ (
    .A1(_257_),
    .A2(_258_),
    .Z(_259_)
  );
  OAI21_X1 _499_ (
    .A1(_257_),
    .A2(_258_),
    .B(RESTART),
    .ZN(_260_)
  );
  OAI21_X1 _500_ (
    .A1(_259_),
    .A2(_260_),
    .B(stato[1]),
    .ZN(_261_)
  );
  OAI21_X1 _501_ (
    .A1(_238_),
    .A2(_261_),
    .B(_209_),
    .ZN(_098_)
  );
  NAND2_X1 _502_ (
    .A1(DATA_OUT[4]),
    .A2(_153_),
    .ZN(_262_)
  );
  XNOR2_X1 _503_ (
    .A1(_230_),
    .A2(_232_),
    .ZN(_263_)
  );
  NAND2_X1 _504_ (
    .A1(RLAST[4]),
    .A2(_151_),
    .ZN(_264_)
  );
  AOI21_X1 _505_ (
    .A1(REG4[4]),
    .A2(_204_),
    .B(RESTART),
    .ZN(_265_)
  );
  NAND2_X1 _506_ (
    .A1(_264_),
    .A2(_265_),
    .ZN(_266_)
  );
  AOI21_X1 _507_ (
    .A1(_210_),
    .A2(_263_),
    .B(_266_),
    .ZN(_267_)
  );
  XNOR2_X1 _508_ (
    .A1(_254_),
    .A2(_256_),
    .ZN(_268_)
  );
  OAI21_X1 _509_ (
    .A1(_152_),
    .A2(_268_),
    .B(stato[1]),
    .ZN(_269_)
  );
  OAI21_X1 _510_ (
    .A1(_267_),
    .A2(_269_),
    .B(_262_),
    .ZN(_097_)
  );
  NAND2_X1 _511_ (
    .A1(DATA_OUT[3]),
    .A2(_153_),
    .ZN(_270_)
  );
  XNOR2_X1 _512_ (
    .A1(_227_),
    .A2(_229_),
    .ZN(_271_)
  );
  NAND2_X1 _513_ (
    .A1(RLAST[3]),
    .A2(_151_),
    .ZN(_272_)
  );
  AOI21_X1 _514_ (
    .A1(REG4[3]),
    .A2(_204_),
    .B(RESTART),
    .ZN(_273_)
  );
  NAND2_X1 _515_ (
    .A1(_272_),
    .A2(_273_),
    .ZN(_274_)
  );
  AOI21_X1 _516_ (
    .A1(_210_),
    .A2(_271_),
    .B(_274_),
    .ZN(_275_)
  );
  XNOR2_X1 _517_ (
    .A1(_251_),
    .A2(_253_),
    .ZN(_276_)
  );
  NAND2_X1 _518_ (
    .A1(RESTART),
    .A2(_276_),
    .ZN(_277_)
  );
  NAND2_X1 _519_ (
    .A1(stato[1]),
    .A2(_277_),
    .ZN(_278_)
  );
  OAI21_X1 _520_ (
    .A1(_275_),
    .A2(_278_),
    .B(_270_),
    .ZN(_096_)
  );
  NAND2_X1 _521_ (
    .A1(DATA_OUT[2]),
    .A2(_153_),
    .ZN(_279_)
  );
  NAND2_X1 _522_ (
    .A1(_224_),
    .A2(_225_),
    .ZN(_280_)
  );
  NAND2_X1 _523_ (
    .A1(_210_),
    .A2(_280_),
    .ZN(_281_)
  );
  AOI22_X1 _524_ (
    .A1(RLAST[2]),
    .A2(_151_),
    .B1(_204_),
    .B2(REG4[2]),
    .ZN(_282_)
  );
  OAI21_X1 _525_ (
    .A1(_226_),
    .A2(_281_),
    .B(_282_),
    .ZN(_283_)
  );
  XNOR2_X1 _526_ (
    .A1(_249_),
    .A2(_250_),
    .ZN(_284_)
  );
  AOI21_X1 _527_ (
    .A1(RESTART),
    .A2(_284_),
    .B(_150_),
    .ZN(_285_)
  );
  OAI21_X1 _528_ (
    .A1(RESTART),
    .A2(_283_),
    .B(_285_),
    .ZN(_286_)
  );
  NAND2_X1 _529_ (
    .A1(_279_),
    .A2(_286_),
    .ZN(_095_)
  );
  NOR2_X1 _530_ (
    .A1(_221_),
    .A2(_222_),
    .ZN(_287_)
  );
  NAND2_X1 _531_ (
    .A1(_210_),
    .A2(_223_),
    .ZN(_288_)
  );
  AOI22_X1 _532_ (
    .A1(RLAST[1]),
    .A2(_151_),
    .B1(_204_),
    .B2(REG4[1]),
    .ZN(_289_)
  );
  OAI21_X1 _533_ (
    .A1(_287_),
    .A2(_288_),
    .B(_289_),
    .ZN(_290_)
  );
  XNOR2_X1 _534_ (
    .A1(_246_),
    .A2(_248_),
    .ZN(_291_)
  );
  OAI21_X1 _535_ (
    .A1(RESTART),
    .A2(_290_),
    .B(stato[1]),
    .ZN(_292_)
  );
  AOI21_X1 _536_ (
    .A1(RESTART),
    .A2(_291_),
    .B(_292_),
    .ZN(_293_)
  );
  AOI21_X1 _537_ (
    .A1(DATA_OUT[1]),
    .A2(_153_),
    .B(_293_),
    .ZN(_294_)
  );
  INV_X1 _538_ (
    .I(_294_),
    .ZN(_094_)
  );
  XNOR2_X1 _539_ (
    .A1(_218_),
    .A2(_220_),
    .ZN(_295_)
  );
  NAND2_X1 _540_ (
    .A1(REG4[0]),
    .A2(_204_),
    .ZN(_296_)
  );
  AOI22_X1 _541_ (
    .A1(RLAST[0]),
    .A2(_151_),
    .B1(_210_),
    .B2(_295_),
    .ZN(_297_)
  );
  NAND3_X1 _542_ (
    .A1(_152_),
    .A2(_296_),
    .A3(_297_),
    .ZN(_298_)
  );
  XNOR2_X1 _543_ (
    .A1(_244_),
    .A2(_245_),
    .ZN(_299_)
  );
  AOI21_X1 _544_ (
    .A1(RESTART),
    .A2(_299_),
    .B(_150_),
    .ZN(_300_)
  );
  AOI22_X1 _545_ (
    .A1(DATA_OUT[0]),
    .A2(_153_),
    .B1(_298_),
    .B2(_300_),
    .ZN(_301_)
  );
  INV_X1 _546_ (
    .I(_301_),
    .ZN(_093_)
  );
  OAI21_X1 _547_ (
    .A1(_150_),
    .A2(ENABLE),
    .B(_000_),
    .ZN(_302_)
  );
  NAND2_X1 _548_ (
    .A1(RLAST[7]),
    .A2(_302_),
    .ZN(_303_)
  );
  NAND3_X1 _549_ (
    .A1(DATA_IN[7]),
    .A2(stato[1]),
    .A3(ENABLE),
    .ZN(_304_)
  );
  NAND2_X1 _550_ (
    .A1(_303_),
    .A2(_304_),
    .ZN(_092_)
  );
  NAND2_X1 _551_ (
    .A1(RLAST[6]),
    .A2(_302_),
    .ZN(_305_)
  );
  NAND3_X1 _552_ (
    .A1(DATA_IN[6]),
    .A2(stato[1]),
    .A3(ENABLE),
    .ZN(_306_)
  );
  NAND2_X1 _553_ (
    .A1(_305_),
    .A2(_306_),
    .ZN(_091_)
  );
  NAND2_X1 _554_ (
    .A1(RLAST[5]),
    .A2(_302_),
    .ZN(_307_)
  );
  NAND3_X1 _555_ (
    .A1(DATA_IN[5]),
    .A2(stato[1]),
    .A3(ENABLE),
    .ZN(_308_)
  );
  NAND2_X1 _556_ (
    .A1(_307_),
    .A2(_308_),
    .ZN(_090_)
  );
  NAND2_X1 _557_ (
    .A1(RLAST[4]),
    .A2(_302_),
    .ZN(_309_)
  );
  NAND3_X1 _558_ (
    .A1(DATA_IN[4]),
    .A2(stato[1]),
    .A3(ENABLE),
    .ZN(_310_)
  );
  NAND2_X1 _559_ (
    .A1(_309_),
    .A2(_310_),
    .ZN(_089_)
  );
  NAND2_X1 _560_ (
    .A1(RLAST[3]),
    .A2(_302_),
    .ZN(_311_)
  );
  NAND3_X1 _561_ (
    .A1(DATA_IN[3]),
    .A2(stato[1]),
    .A3(ENABLE),
    .ZN(_312_)
  );
  NAND2_X1 _562_ (
    .A1(_311_),
    .A2(_312_),
    .ZN(_088_)
  );
  NAND2_X1 _563_ (
    .A1(RLAST[2]),
    .A2(_302_),
    .ZN(_313_)
  );
  NAND3_X1 _564_ (
    .A1(DATA_IN[2]),
    .A2(stato[1]),
    .A3(ENABLE),
    .ZN(_314_)
  );
  NAND2_X1 _565_ (
    .A1(_313_),
    .A2(_314_),
    .ZN(_087_)
  );
  NAND2_X1 _566_ (
    .A1(RLAST[1]),
    .A2(_302_),
    .ZN(_315_)
  );
  NAND3_X1 _567_ (
    .A1(DATA_IN[1]),
    .A2(stato[1]),
    .A3(ENABLE),
    .ZN(_316_)
  );
  NAND2_X1 _568_ (
    .A1(_315_),
    .A2(_316_),
    .ZN(_086_)
  );
  NAND2_X1 _569_ (
    .A1(RLAST[0]),
    .A2(_302_),
    .ZN(_317_)
  );
  NAND3_X1 _570_ (
    .A1(DATA_IN[0]),
    .A2(stato[1]),
    .A3(ENABLE),
    .ZN(_318_)
  );
  NAND2_X1 _571_ (
    .A1(_317_),
    .A2(_318_),
    .ZN(_085_)
  );
  AOI22_X1 _572_ (
    .A1(REG3[30]),
    .A2(stato[1]),
    .B1(_153_),
    .B2(REG4[30]),
    .ZN(_319_)
  );
  INV_X1 _573_ (
    .I(_319_),
    .ZN(_084_)
  );
  AOI22_X1 _574_ (
    .A1(REG3[6]),
    .A2(stato[1]),
    .B1(_153_),
    .B2(REG4[6]),
    .ZN(_320_)
  );
  INV_X1 _575_ (
    .I(_320_),
    .ZN(_083_)
  );
  AOI22_X1 _576_ (
    .A1(REG3[5]),
    .A2(stato[1]),
    .B1(_153_),
    .B2(REG4[5]),
    .ZN(_321_)
  );
  INV_X1 _577_ (
    .I(_321_),
    .ZN(_082_)
  );
  AOI22_X1 _578_ (
    .A1(REG3[4]),
    .A2(stato[1]),
    .B1(_153_),
    .B2(REG4[4]),
    .ZN(_322_)
  );
  INV_X1 _579_ (
    .I(_322_),
    .ZN(_081_)
  );
  AOI22_X1 _580_ (
    .A1(REG3[3]),
    .A2(stato[1]),
    .B1(_153_),
    .B2(REG4[3]),
    .ZN(_323_)
  );
  INV_X1 _581_ (
    .I(_323_),
    .ZN(_080_)
  );
  AOI22_X1 _582_ (
    .A1(REG3[2]),
    .A2(stato[1]),
    .B1(_153_),
    .B2(REG4[2]),
    .ZN(_324_)
  );
  INV_X1 _583_ (
    .I(_324_),
    .ZN(_079_)
  );
  AOI22_X1 _584_ (
    .A1(REG3[1]),
    .A2(stato[1]),
    .B1(_153_),
    .B2(REG4[1]),
    .ZN(_325_)
  );
  INV_X1 _585_ (
    .I(_325_),
    .ZN(_078_)
  );
  AOI22_X1 _586_ (
    .A1(REG3[0]),
    .A2(stato[1]),
    .B1(_153_),
    .B2(REG4[0]),
    .ZN(_326_)
  );
  INV_X1 _587_ (
    .I(_326_),
    .ZN(_077_)
  );
  AOI22_X1 _588_ (
    .A1(REG2[30]),
    .A2(stato[1]),
    .B1(_153_),
    .B2(REG3[30]),
    .ZN(_327_)
  );
  INV_X1 _589_ (
    .I(_327_),
    .ZN(_076_)
  );
  AOI22_X1 _590_ (
    .A1(REG2[6]),
    .A2(stato[1]),
    .B1(_153_),
    .B2(REG3[6]),
    .ZN(_328_)
  );
  INV_X1 _591_ (
    .I(_328_),
    .ZN(_075_)
  );
  AOI22_X1 _592_ (
    .A1(REG2[5]),
    .A2(stato[1]),
    .B1(_153_),
    .B2(REG3[5]),
    .ZN(_329_)
  );
  INV_X1 _593_ (
    .I(_329_),
    .ZN(_074_)
  );
  AOI22_X1 _594_ (
    .A1(REG2[4]),
    .A2(stato[1]),
    .B1(_153_),
    .B2(REG3[4]),
    .ZN(_330_)
  );
  INV_X1 _595_ (
    .I(_330_),
    .ZN(_073_)
  );
  AOI22_X1 _596_ (
    .A1(REG2[3]),
    .A2(stato[1]),
    .B1(_153_),
    .B2(REG3[3]),
    .ZN(_331_)
  );
  INV_X1 _597_ (
    .I(_331_),
    .ZN(_072_)
  );
  AOI22_X1 _598_ (
    .A1(REG2[2]),
    .A2(stato[1]),
    .B1(_153_),
    .B2(REG3[2]),
    .ZN(_332_)
  );
  INV_X1 _599_ (
    .I(_332_),
    .ZN(_071_)
  );
  AOI22_X1 _600_ (
    .A1(REG2[1]),
    .A2(stato[1]),
    .B1(_153_),
    .B2(REG3[1]),
    .ZN(_333_)
  );
  INV_X1 _601_ (
    .I(_333_),
    .ZN(_070_)
  );
  AOI22_X1 _602_ (
    .A1(REG2[0]),
    .A2(stato[1]),
    .B1(_153_),
    .B2(REG3[0]),
    .ZN(_334_)
  );
  INV_X1 _603_ (
    .I(_334_),
    .ZN(_069_)
  );
  AOI22_X1 _604_ (
    .A1(REG1[30]),
    .A2(stato[1]),
    .B1(_153_),
    .B2(REG2[30]),
    .ZN(_335_)
  );
  INV_X1 _605_ (
    .I(_335_),
    .ZN(_068_)
  );
  INV_X1 _606_ (
    .I(RESET),
    .ZN(_002_)
  );
  INV_X1 _607_ (
    .I(RESET),
    .ZN(_003_)
  );
  INV_X1 _608_ (
    .I(RESET),
    .ZN(_004_)
  );
  INV_X1 _609_ (
    .I(RESET),
    .ZN(_005_)
  );
  INV_X1 _610_ (
    .I(RESET),
    .ZN(_006_)
  );
  INV_X1 _611_ (
    .I(RESET),
    .ZN(_007_)
  );
  INV_X1 _612_ (
    .I(RESET),
    .ZN(_008_)
  );
  INV_X1 _613_ (
    .I(RESET),
    .ZN(_009_)
  );
  INV_X1 _614_ (
    .I(RESET),
    .ZN(_010_)
  );
  INV_X1 _615_ (
    .I(RESET),
    .ZN(_011_)
  );
  INV_X1 _616_ (
    .I(RESET),
    .ZN(_012_)
  );
  INV_X1 _617_ (
    .I(RESET),
    .ZN(_013_)
  );
  INV_X1 _618_ (
    .I(RESET),
    .ZN(_014_)
  );
  INV_X1 _619_ (
    .I(RESET),
    .ZN(_015_)
  );
  INV_X1 _620_ (
    .I(RESET),
    .ZN(_016_)
  );
  INV_X1 _621_ (
    .I(RESET),
    .ZN(_017_)
  );
  INV_X1 _622_ (
    .I(RESET),
    .ZN(_018_)
  );
  INV_X1 _623_ (
    .I(RESET),
    .ZN(_019_)
  );
  INV_X1 _624_ (
    .I(RESET),
    .ZN(_020_)
  );
  INV_X1 _625_ (
    .I(RESET),
    .ZN(_021_)
  );
  INV_X1 _626_ (
    .I(RESET),
    .ZN(_022_)
  );
  INV_X1 _627_ (
    .I(RESET),
    .ZN(_023_)
  );
  INV_X1 _628_ (
    .I(RESET),
    .ZN(_024_)
  );
  INV_X1 _629_ (
    .I(RESET),
    .ZN(_025_)
  );
  INV_X1 _630_ (
    .I(RESET),
    .ZN(_026_)
  );
  INV_X1 _631_ (
    .I(RESET),
    .ZN(_027_)
  );
  INV_X1 _632_ (
    .I(RESET),
    .ZN(_028_)
  );
  INV_X1 _633_ (
    .I(RESET),
    .ZN(_029_)
  );
  INV_X1 _634_ (
    .I(RESET),
    .ZN(_030_)
  );
  INV_X1 _635_ (
    .I(RESET),
    .ZN(_031_)
  );
  INV_X1 _636_ (
    .I(RESET),
    .ZN(_032_)
  );
  INV_X1 _637_ (
    .I(RESET),
    .ZN(_033_)
  );
  INV_X1 _638_ (
    .I(RESET),
    .ZN(_034_)
  );
  INV_X1 _639_ (
    .I(RESET),
    .ZN(_035_)
  );
  INV_X1 _640_ (
    .I(RESET),
    .ZN(_036_)
  );
  INV_X1 _641_ (
    .I(RESET),
    .ZN(_037_)
  );
  INV_X1 _642_ (
    .I(RESET),
    .ZN(_038_)
  );
  INV_X1 _643_ (
    .I(RESET),
    .ZN(_039_)
  );
  INV_X1 _644_ (
    .I(RESET),
    .ZN(_040_)
  );
  INV_X1 _645_ (
    .I(RESET),
    .ZN(_041_)
  );
  INV_X1 _646_ (
    .I(RESET),
    .ZN(_042_)
  );
  INV_X1 _647_ (
    .I(RESET),
    .ZN(_043_)
  );
  INV_X1 _648_ (
    .I(RESET),
    .ZN(_044_)
  );
  INV_X1 _649_ (
    .I(RESET),
    .ZN(_045_)
  );
  INV_X1 _650_ (
    .I(RESET),
    .ZN(_046_)
  );
  INV_X1 _651_ (
    .I(RESET),
    .ZN(_047_)
  );
  INV_X1 _652_ (
    .I(RESET),
    .ZN(_048_)
  );
  INV_X1 _653_ (
    .I(RESET),
    .ZN(_049_)
  );
  INV_X1 _654_ (
    .I(RESET),
    .ZN(_050_)
  );
  INV_X1 _655_ (
    .I(RESET),
    .ZN(_051_)
  );
  INV_X1 _656_ (
    .I(RESET),
    .ZN(_052_)
  );
  INV_X1 _657_ (
    .I(RESET),
    .ZN(_053_)
  );
  INV_X1 _658_ (
    .I(RESET),
    .ZN(_054_)
  );
  INV_X1 _659_ (
    .I(RESET),
    .ZN(_055_)
  );
  INV_X1 _660_ (
    .I(RESET),
    .ZN(_056_)
  );
  INV_X1 _661_ (
    .I(RESET),
    .ZN(_057_)
  );
  INV_X1 _662_ (
    .I(RESET),
    .ZN(_058_)
  );
  INV_X1 _663_ (
    .I(RESET),
    .ZN(_059_)
  );
  INV_X1 _664_ (
    .I(RESET),
    .ZN(_060_)
  );
  INV_X1 _665_ (
    .I(RESET),
    .ZN(_061_)
  );
  INV_X1 _666_ (
    .I(RESET),
    .ZN(_062_)
  );
  INV_X1 _667_ (
    .I(RESET),
    .ZN(_063_)
  );
  INV_X1 _668_ (
    .I(RESET),
    .ZN(_064_)
  );
  INV_X1 _669_ (
    .I(RESET),
    .ZN(_065_)
  );
  INV_X1 _670_ (
    .I(RESET),
    .ZN(_066_)
  );
  INV_X1 _671_ (
    .I(RESET),
    .ZN(_067_)
  );
  (* src = "b04.v:24.1-109.4" *)
  DFFRNQ_X1 _672_ (
    .CLK(CLOCK),
    .D(_068_),
    .Q(REG2[30]),
    .RN(_001_)
  );
  (* src = "b04.v:24.1-109.4" *)
  DFFRNQ_X1 _673_ (
    .CLK(CLOCK),
    .D(_069_),
    .Q(REG3[0]),
    .RN(_002_)
  );
  (* src = "b04.v:24.1-109.4" *)
  DFFRNQ_X1 _674_ (
    .CLK(CLOCK),
    .D(_070_),
    .Q(REG3[1]),
    .RN(_003_)
  );
  (* src = "b04.v:24.1-109.4" *)
  DFFRNQ_X1 _675_ (
    .CLK(CLOCK),
    .D(_071_),
    .Q(REG3[2]),
    .RN(_004_)
  );
  (* src = "b04.v:24.1-109.4" *)
  DFFRNQ_X1 _676_ (
    .CLK(CLOCK),
    .D(_072_),
    .Q(REG3[3]),
    .RN(_005_)
  );
  (* src = "b04.v:24.1-109.4" *)
  DFFRNQ_X1 _677_ (
    .CLK(CLOCK),
    .D(_073_),
    .Q(REG3[4]),
    .RN(_006_)
  );
  (* src = "b04.v:24.1-109.4" *)
  DFFRNQ_X1 _678_ (
    .CLK(CLOCK),
    .D(_074_),
    .Q(REG3[5]),
    .RN(_007_)
  );
  (* src = "b04.v:24.1-109.4" *)
  DFFRNQ_X1 _679_ (
    .CLK(CLOCK),
    .D(_075_),
    .Q(REG3[6]),
    .RN(_008_)
  );
  (* src = "b04.v:24.1-109.4" *)
  DFFRNQ_X1 _680_ (
    .CLK(CLOCK),
    .D(_076_),
    .Q(REG3[30]),
    .RN(_009_)
  );
  (* src = "b04.v:24.1-109.4" *)
  DFFRNQ_X1 _681_ (
    .CLK(CLOCK),
    .D(_077_),
    .Q(REG4[0]),
    .RN(_010_)
  );
  (* src = "b04.v:24.1-109.4" *)
  DFFRNQ_X1 _682_ (
    .CLK(CLOCK),
    .D(_078_),
    .Q(REG4[1]),
    .RN(_011_)
  );
  (* src = "b04.v:24.1-109.4" *)
  DFFRNQ_X1 _683_ (
    .CLK(CLOCK),
    .D(_079_),
    .Q(REG4[2]),
    .RN(_012_)
  );
  (* src = "b04.v:24.1-109.4" *)
  DFFRNQ_X1 _684_ (
    .CLK(CLOCK),
    .D(_080_),
    .Q(REG4[3]),
    .RN(_013_)
  );
  (* src = "b04.v:24.1-109.4" *)
  DFFRNQ_X1 _685_ (
    .CLK(CLOCK),
    .D(_081_),
    .Q(REG4[4]),
    .RN(_014_)
  );
  (* src = "b04.v:24.1-109.4" *)
  DFFRNQ_X1 _686_ (
    .CLK(CLOCK),
    .D(_082_),
    .Q(REG4[5]),
    .RN(_015_)
  );
  (* src = "b04.v:24.1-109.4" *)
  DFFRNQ_X1 _687_ (
    .CLK(CLOCK),
    .D(_083_),
    .Q(REG4[6]),
    .RN(_016_)
  );
  (* src = "b04.v:24.1-109.4" *)
  DFFRNQ_X1 _688_ (
    .CLK(CLOCK),
    .D(_084_),
    .Q(REG4[30]),
    .RN(_017_)
  );
  DFFSNQ_X1 _689_ (
    .CLK(CLOCK),
    .D(1'h0),
    .Q(stato[0]),
    .SN(_018_)
  );
  DFFRNQ_X1 _690_ (
    .CLK(CLOCK),
    .D(_000_),
    .Q(stato[1]),
    .RN(_019_)
  );
  DFFRNQ_X1 _691_ (
    .CLK(CLOCK),
    .D(stato[0]),
    .Q(stato[2]),
    .RN(_020_)
  );
  (* src = "b04.v:24.1-109.4" *)
  DFFRNQ_X1 _692_ (
    .CLK(CLOCK),
    .D(_085_),
    .Q(RLAST[0]),
    .RN(_021_)
  );
  (* src = "b04.v:24.1-109.4" *)
  DFFRNQ_X1 _693_ (
    .CLK(CLOCK),
    .D(_086_),
    .Q(RLAST[1]),
    .RN(_022_)
  );
  (* src = "b04.v:24.1-109.4" *)
  DFFRNQ_X1 _694_ (
    .CLK(CLOCK),
    .D(_087_),
    .Q(RLAST[2]),
    .RN(_023_)
  );
  (* src = "b04.v:24.1-109.4" *)
  DFFRNQ_X1 _695_ (
    .CLK(CLOCK),
    .D(_088_),
    .Q(RLAST[3]),
    .RN(_024_)
  );
  (* src = "b04.v:24.1-109.4" *)
  DFFRNQ_X1 _696_ (
    .CLK(CLOCK),
    .D(_089_),
    .Q(RLAST[4]),
    .RN(_025_)
  );
  (* src = "b04.v:24.1-109.4" *)
  DFFRNQ_X1 _697_ (
    .CLK(CLOCK),
    .D(_090_),
    .Q(RLAST[5]),
    .RN(_026_)
  );
  (* src = "b04.v:24.1-109.4" *)
  DFFRNQ_X1 _698_ (
    .CLK(CLOCK),
    .D(_091_),
    .Q(RLAST[6]),
    .RN(_027_)
  );
  (* src = "b04.v:24.1-109.4" *)
  DFFRNQ_X1 _699_ (
    .CLK(CLOCK),
    .D(_092_),
    .Q(RLAST[7]),
    .RN(_028_)
  );
  (* src = "b04.v:24.1-109.4" *)
  DFFRNQ_X1 _700_ (
    .CLK(CLOCK),
    .D(_093_),
    .Q(DATA_OUT[0]),
    .RN(_029_)
  );
  (* src = "b04.v:24.1-109.4" *)
  DFFRNQ_X1 _701_ (
    .CLK(CLOCK),
    .D(_094_),
    .Q(DATA_OUT[1]),
    .RN(_030_)
  );
  (* src = "b04.v:24.1-109.4" *)
  DFFRNQ_X1 _702_ (
    .CLK(CLOCK),
    .D(_095_),
    .Q(DATA_OUT[2]),
    .RN(_031_)
  );
  (* src = "b04.v:24.1-109.4" *)
  DFFRNQ_X1 _703_ (
    .CLK(CLOCK),
    .D(_096_),
    .Q(DATA_OUT[3]),
    .RN(_032_)
  );
  (* src = "b04.v:24.1-109.4" *)
  DFFRNQ_X1 _704_ (
    .CLK(CLOCK),
    .D(_097_),
    .Q(DATA_OUT[4]),
    .RN(_033_)
  );
  (* src = "b04.v:24.1-109.4" *)
  DFFRNQ_X1 _705_ (
    .CLK(CLOCK),
    .D(_098_),
    .Q(DATA_OUT[5]),
    .RN(_034_)
  );
  (* src = "b04.v:24.1-109.4" *)
  DFFRNQ_X1 _706_ (
    .CLK(CLOCK),
    .D(_099_),
    .Q(DATA_OUT[6]),
    .RN(_035_)
  );
  (* src = "b04.v:24.1-109.4" *)
  DFFRNQ_X1 _707_ (
    .CLK(CLOCK),
    .D(_100_),
    .Q(DATA_OUT[7]),
    .RN(_036_)
  );
  (* src = "b04.v:24.1-109.4" *)
  DFFRNQ_X1 _708_ (
    .CLK(CLOCK),
    .D(_101_),
    .Q(RMAX[0]),
    .RN(_037_)
  );
  (* src = "b04.v:24.1-109.4" *)
  DFFRNQ_X1 _709_ (
    .CLK(CLOCK),
    .D(_102_),
    .Q(RMAX[1]),
    .RN(_038_)
  );
  (* src = "b04.v:24.1-109.4" *)
  DFFRNQ_X1 _710_ (
    .CLK(CLOCK),
    .D(_103_),
    .Q(RMAX[2]),
    .RN(_039_)
  );
  (* src = "b04.v:24.1-109.4" *)
  DFFRNQ_X1 _711_ (
    .CLK(CLOCK),
    .D(_104_),
    .Q(RMAX[3]),
    .RN(_040_)
  );
  (* src = "b04.v:24.1-109.4" *)
  DFFRNQ_X1 _712_ (
    .CLK(CLOCK),
    .D(_105_),
    .Q(RMAX[4]),
    .RN(_041_)
  );
  (* src = "b04.v:24.1-109.4" *)
  DFFRNQ_X1 _713_ (
    .CLK(CLOCK),
    .D(_106_),
    .Q(RMAX[5]),
    .RN(_042_)
  );
  (* src = "b04.v:24.1-109.4" *)
  DFFRNQ_X1 _714_ (
    .CLK(CLOCK),
    .D(_107_),
    .Q(RMAX[6]),
    .RN(_043_)
  );
  (* src = "b04.v:24.1-109.4" *)
  DFFRNQ_X1 _715_ (
    .CLK(CLOCK),
    .D(_108_),
    .Q(RMAX[30]),
    .RN(_044_)
  );
  (* src = "b04.v:24.1-109.4" *)
  DFFRNQ_X1 _716_ (
    .CLK(CLOCK),
    .D(_109_),
    .Q(RMIN[0]),
    .RN(_045_)
  );
  (* src = "b04.v:24.1-109.4" *)
  DFFRNQ_X1 _717_ (
    .CLK(CLOCK),
    .D(_110_),
    .Q(RMIN[1]),
    .RN(_046_)
  );
  (* src = "b04.v:24.1-109.4" *)
  DFFRNQ_X1 _718_ (
    .CLK(CLOCK),
    .D(_111_),
    .Q(RMIN[2]),
    .RN(_047_)
  );
  (* src = "b04.v:24.1-109.4" *)
  DFFRNQ_X1 _719_ (
    .CLK(CLOCK),
    .D(_112_),
    .Q(RMIN[3]),
    .RN(_048_)
  );
  (* src = "b04.v:24.1-109.4" *)
  DFFRNQ_X1 _720_ (
    .CLK(CLOCK),
    .D(_113_),
    .Q(RMIN[4]),
    .RN(_049_)
  );
  (* src = "b04.v:24.1-109.4" *)
  DFFRNQ_X1 _721_ (
    .CLK(CLOCK),
    .D(_114_),
    .Q(RMIN[5]),
    .RN(_050_)
  );
  (* src = "b04.v:24.1-109.4" *)
  DFFRNQ_X1 _722_ (
    .CLK(CLOCK),
    .D(_115_),
    .Q(RMIN[6]),
    .RN(_051_)
  );
  (* src = "b04.v:24.1-109.4" *)
  DFFRNQ_X1 _723_ (
    .CLK(CLOCK),
    .D(_116_),
    .Q(RMIN[30]),
    .RN(_052_)
  );
  (* src = "b04.v:24.1-109.4" *)
  DFFRNQ_X1 _724_ (
    .CLK(CLOCK),
    .D(_117_),
    .Q(REG1[0]),
    .RN(_053_)
  );
  (* src = "b04.v:24.1-109.4" *)
  DFFRNQ_X1 _725_ (
    .CLK(CLOCK),
    .D(_118_),
    .Q(REG1[1]),
    .RN(_054_)
  );
  (* src = "b04.v:24.1-109.4" *)
  DFFRNQ_X1 _726_ (
    .CLK(CLOCK),
    .D(_119_),
    .Q(REG1[2]),
    .RN(_055_)
  );
  (* src = "b04.v:24.1-109.4" *)
  DFFRNQ_X1 _727_ (
    .CLK(CLOCK),
    .D(_120_),
    .Q(REG1[3]),
    .RN(_056_)
  );
  (* src = "b04.v:24.1-109.4" *)
  DFFRNQ_X1 _728_ (
    .CLK(CLOCK),
    .D(_121_),
    .Q(REG1[4]),
    .RN(_057_)
  );
  (* src = "b04.v:24.1-109.4" *)
  DFFRNQ_X1 _729_ (
    .CLK(CLOCK),
    .D(_122_),
    .Q(REG1[5]),
    .RN(_058_)
  );
  (* src = "b04.v:24.1-109.4" *)
  DFFRNQ_X1 _730_ (
    .CLK(CLOCK),
    .D(_123_),
    .Q(REG1[6]),
    .RN(_059_)
  );
  (* src = "b04.v:24.1-109.4" *)
  DFFRNQ_X1 _731_ (
    .CLK(CLOCK),
    .D(_124_),
    .Q(REG1[30]),
    .RN(_060_)
  );
  (* src = "b04.v:24.1-109.4" *)
  DFFRNQ_X1 _732_ (
    .CLK(CLOCK),
    .D(_125_),
    .Q(REG2[0]),
    .RN(_061_)
  );
  (* src = "b04.v:24.1-109.4" *)
  DFFRNQ_X1 _733_ (
    .CLK(CLOCK),
    .D(_126_),
    .Q(REG2[1]),
    .RN(_062_)
  );
  (* src = "b04.v:24.1-109.4" *)
  DFFRNQ_X1 _734_ (
    .CLK(CLOCK),
    .D(_127_),
    .Q(REG2[2]),
    .RN(_063_)
  );
  (* src = "b04.v:24.1-109.4" *)
  DFFRNQ_X1 _735_ (
    .CLK(CLOCK),
    .D(_128_),
    .Q(REG2[3]),
    .RN(_064_)
  );
  (* src = "b04.v:24.1-109.4" *)
  DFFRNQ_X1 _736_ (
    .CLK(CLOCK),
    .D(_129_),
    .Q(REG2[4]),
    .RN(_065_)
  );
  (* src = "b04.v:24.1-109.4" *)
  DFFRNQ_X1 _737_ (
    .CLK(CLOCK),
    .D(_130_),
    .Q(REG2[5]),
    .RN(_066_)
  );
  (* src = "b04.v:24.1-109.4" *)
  DFFRNQ_X1 _738_ (
    .CLK(CLOCK),
    .D(_131_),
    .Q(REG2[6]),
    .RN(_067_)
  );
  assign { REG1[31], REG1[29:7] } = { REG1[30], REG1[30], REG1[30], REG1[30], REG1[30], REG1[30], REG1[30], REG1[30], REG1[30], REG1[30], REG1[30], REG1[30], REG1[30], REG1[30], REG1[30], REG1[30], REG1[30], REG1[30], REG1[30], REG1[30], REG1[30], REG1[30], REG1[30], REG1[30] };
  assign { REG2[31], REG2[29:7] } = { REG2[30], REG2[30], REG2[30], REG2[30], REG2[30], REG2[30], REG2[30], REG2[30], REG2[30], REG2[30], REG2[30], REG2[30], REG2[30], REG2[30], REG2[30], REG2[30], REG2[30], REG2[30], REG2[30], REG2[30], REG2[30], REG2[30], REG2[30], REG2[30] };
  assign { REG3[31], REG3[29:7] } = { REG3[30], REG3[30], REG3[30], REG3[30], REG3[30], REG3[30], REG3[30], REG3[30], REG3[30], REG3[30], REG3[30], REG3[30], REG3[30], REG3[30], REG3[30], REG3[30], REG3[30], REG3[30], REG3[30], REG3[30], REG3[30], REG3[30], REG3[30], REG3[30] };
  assign { REG4[31], REG4[29:7] } = { REG4[30], REG4[30], REG4[30], REG4[30], REG4[30], REG4[30], REG4[30], REG4[30], REG4[30], REG4[30], REG4[30], REG4[30], REG4[30], REG4[30], REG4[30], REG4[30], REG4[30], REG4[30], REG4[30], REG4[30], REG4[30], REG4[30], REG4[30], REG4[30] };
  assign { RMAX[31], RMAX[29:7] } = { RMAX[30], RMAX[30], RMAX[30], RMAX[30], RMAX[30], RMAX[30], RMAX[30], RMAX[30], RMAX[30], RMAX[30], RMAX[30], RMAX[30], RMAX[30], RMAX[30], RMAX[30], RMAX[30], RMAX[30], RMAX[30], RMAX[30], RMAX[30], RMAX[30], RMAX[30], RMAX[30], RMAX[30] };
  assign { RMIN[31], RMIN[29:7] } = { RMIN[30], RMIN[30], RMIN[30], RMIN[30], RMIN[30], RMIN[30], RMIN[30], RMIN[30], RMIN[30], RMIN[30], RMIN[30], RMIN[30], RMIN[30], RMIN[30], RMIN[30], RMIN[30], RMIN[30], RMIN[30], RMIN[30], RMIN[30], RMIN[30], RMIN[30], RMIN[30], RMIN[30] };
endmodule
