/*
    Automatically generated by Fault
    Do not modify.
    Generated on: 2026-02-26 19:18:19
*/
/* FAULT METADATA: '{"shift":"shift","sin":"sin","boundaryCount":2,"order":[{"ordinal":0,"kind":"input","name":"i","width":1},{"ordinal":0,"kind":"dff","name":"_20_","width":1},{"ordinal":0,"kind":"dff","name":"_21_","width":1},{"ordinal":0,"kind":"dff","name":"_22_","width":1},{"ordinal":0,"kind":"output","name":"q","width":1}],"internalCount":3,"sout":"sout"}' END FAULT METADATA */
/* Generated by Yosys 0.58+35 (git sha1 9a12d9255, clang++ 18.1.3 -fPIC -O3) */

module fsm(i, clk, rst, q, sin, shift, sout, tck, test);
  input i;
  wire i;
  input clk;
  wire clk;
  input rst;
  wire rst;
  output q;
  wire q;
  input sin;
  wire sin;
  input shift;
  wire shift;
  output sout;
  wire sout;
  input tck;
  wire tck;
  input test;
  wire test;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire \__BoundaryScanRegister_input__0__.dout ;
  wire \__BoundaryScanRegister_input__0__.sout ;
  wire \__BoundaryScanRegister_output__1__.sin ;
  wire \__uuf__._00_ ;
  wire \__uuf__._01_ ;
  wire \__uuf__._02_ ;
  wire \__uuf__._03_ ;
  wire \__uuf__._04_ ;
  wire \__uuf__._05_ ;
  wire \__uuf__._06_ ;
  wire \__uuf__._07_ ;
  wire \__uuf__._08_ ;
  wire \__uuf__.__clk_source__ ;
  wire \__uuf__.nextState[0] ;
  wire \__uuf__.nextState[1] ;
  wire \__uuf__.state[0] ;
  MUX2_X1 _05_ (
    .I0(i),
    .I1(\__BoundaryScanRegister_input__0__.sout ),
    .S(test),
    .Z(\__BoundaryScanRegister_input__0__.dout )
  );
  MUX2_X1 _06_ (
    .I0(\__BoundaryScanRegister_input__0__.dout ),
    .I1(sin),
    .S(shift),
    .Z(_00_)
  );
  MUX2_X1 _07_ (
    .I0(q),
    .I1(\__BoundaryScanRegister_output__1__.sin ),
    .S(shift),
    .Z(_01_)
  );
  MUX2_X1 _08_ (
    .I0(clk),
    .I1(tck),
    .S(test),
    .Z(\__uuf__.__clk_source__ )
  );
  MUX2_X1 _09_ (
    .I0(\__uuf__.nextState[1] ),
    .I1(\__uuf__.state[0] ),
    .S(shift),
    .Z(_04_)
  );
  MUX2_X1 _10_ (
    .I0(\__uuf__.nextState[0] ),
    .I1(q),
    .S(shift),
    .Z(_03_)
  );
  MUX2_X1 _11_ (
    .I0(\__uuf__._00_ ),
    .I1(\__BoundaryScanRegister_input__0__.sout ),
    .S(shift),
    .Z(_02_)
  );
  DFFRNQ_X1 _12_ (
    .CLK(tck),
    .D(_00_),
    .Q(\__BoundaryScanRegister_input__0__.sout ),
    .RN(rst)
  );
  DFFRNQ_X1 _13_ (
    .CLK(tck),
    .D(_01_),
    .Q(sout),
    .RN(rst)
  );
  INV_X1 \__uuf__._09_  (
    .I(\__uuf__.state[0] ),
    .ZN(\__uuf__._04_ )
  );
  INV_X1 \__uuf__._10_  (
    .I(rst),
    .ZN(\__uuf__._01_ )
  );
  AND3_X1 \__uuf__._11_  (
    .A1(\__BoundaryScanRegister_output__1__.sin ),
    .A2(\__uuf__.state[0] ),
    .A3(\__BoundaryScanRegister_input__0__.dout ),
    .Z(\__uuf__._00_ )
  );
  AND3_X1 \__uuf__._12_  (
    .A1(\__BoundaryScanRegister_output__1__.sin ),
    .A2(\__uuf__._04_ ),
    .A3(\__BoundaryScanRegister_input__0__.dout ),
    .Z(\__uuf__._05_ )
  );
  AOI21_X1 \__uuf__._13_  (
    .A1(\__BoundaryScanRegister_output__1__.sin ),
    .A2(\__uuf__._04_ ),
    .B(\__BoundaryScanRegister_input__0__.dout ),
    .ZN(\__uuf__._06_ )
  );
  NOR2_X1 \__uuf__._14_  (
    .A1(\__BoundaryScanRegister_output__1__.sin ),
    .A2(\__uuf__._04_ ),
    .ZN(\__uuf__._07_ )
  );
  NOR3_X1 \__uuf__._15_  (
    .A1(\__uuf__._05_ ),
    .A2(\__uuf__._06_ ),
    .A3(\__uuf__._07_ ),
    .ZN(\__uuf__.nextState[0] )
  );
  XNOR2_X1 \__uuf__._16_  (
    .A1(\__BoundaryScanRegister_output__1__.sin ),
    .A2(\__uuf__.state[0] ),
    .ZN(\__uuf__._08_ )
  );
  NOR2_X1 \__uuf__._17_  (
    .A1(\__uuf__._06_ ),
    .A2(\__uuf__._08_ ),
    .ZN(\__uuf__.nextState[1] )
  );
  INV_X1 \__uuf__._18_  (
    .I(rst),
    .ZN(\__uuf__._02_ )
  );
  INV_X1 \__uuf__._19_  (
    .I(rst),
    .ZN(\__uuf__._03_ )
  );
  DFFRNQ_X1 \__uuf__._20_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_02_),
    .Q(q),
    .RN(\__uuf__._01_ )
  );
  DFFRNQ_X1 \__uuf__._21_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_03_),
    .Q(\__uuf__.state[0] ),
    .RN(\__uuf__._02_ )
  );
  DFFRNQ_X1 \__uuf__._22_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_04_),
    .Q(\__BoundaryScanRegister_output__1__.sin ),
    .RN(\__uuf__._03_ )
  );
endmodule

