/* Generated by Yosys 0.58+35 (git sha1 9a12d9255, clang++ 18.1.3 -fPIC -O3) */

(* top =  1  *)
(* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/fsm/fsm.v:1.1-38.10" *)
module fsm(i, clk, rst, q);
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/fsm/fsm.v:2.11-2.12" *)
  input i;
  wire i;
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/fsm/fsm.v:3.11-3.14" *)
  input clk;
  wire clk;
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/fsm/fsm.v:4.11-4.14" *)
  input rst;
  wire rst;
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/fsm/fsm.v:5.16-5.17" *)
  output q;
  wire q;
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/fsm/fsm.v:30.5-36.8" *)
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/fsm/fsm.v:9.15-9.24" *)
  wire [1:0] nextState;
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/fsm/fsm.v:8.15-8.20" *)
  wire [1:0] state;
  INV_X1 _09_ (
    .I(state[0]),
    .ZN(_04_)
  );
  INV_X1 _10_ (
    .I(rst),
    .ZN(_01_)
  );
  AND3_X1 _11_ (
    .A1(state[1]),
    .A2(state[0]),
    .A3(i),
    .Z(_00_)
  );
  AND3_X1 _12_ (
    .A1(state[1]),
    .A2(_04_),
    .A3(i),
    .Z(_05_)
  );
  AOI21_X1 _13_ (
    .A1(state[1]),
    .A2(_04_),
    .B(i),
    .ZN(_06_)
  );
  NOR2_X1 _14_ (
    .A1(state[1]),
    .A2(_04_),
    .ZN(_07_)
  );
  NOR3_X1 _15_ (
    .A1(_05_),
    .A2(_06_),
    .A3(_07_),
    .ZN(nextState[0])
  );
  XNOR2_X1 _16_ (
    .A1(state[1]),
    .A2(state[0]),
    .ZN(_08_)
  );
  NOR2_X1 _17_ (
    .A1(_06_),
    .A2(_08_),
    .ZN(nextState[1])
  );
  INV_X1 _18_ (
    .I(rst),
    .ZN(_02_)
  );
  INV_X1 _19_ (
    .I(rst),
    .ZN(_03_)
  );
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/fsm/fsm.v:30.5-36.8" *)
  DFFRNQ_X1 _20_ (
    .CLK(clk),
    .D(_00_),
    .Q(q),
    .RN(_01_)
  );
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/fsm/fsm.v:11.5-18.8" *)
  DFFRNQ_X1 _21_ (
    .CLK(clk),
    .D(nextState[0]),
    .Q(state[0]),
    .RN(_02_)
  );
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/fsm/fsm.v:11.5-18.8" *)
  DFFRNQ_X1 _22_ (
    .CLK(clk),
    .D(nextState[1]),
    .Q(state[1]),
    .RN(_03_)
  );
endmodule
