/*
    Automatically generated by Fault
    Do not modify.
    Generated on: 2026-03-30 16:49:11
*/
/* FAULT METADATA: '{"order":[{"ordinal":0,"name":"x","width":1,"kind":"input"},{"ordinal":0,"name":"_268_","width":1,"kind":"dff"},{"ordinal":0,"name":"_269_","width":1,"kind":"dff"},{"ordinal":0,"name":"_270_","width":1,"kind":"dff"},{"ordinal":0,"name":"_271_","width":1,"kind":"dff"},{"ordinal":0,"name":"_272_","width":1,"kind":"dff"},{"ordinal":0,"name":"_273_","width":1,"kind":"dff"},{"ordinal":0,"name":"_274_","width":1,"kind":"dff"},{"ordinal":0,"name":"_275_","width":1,"kind":"dff"},{"ordinal":0,"name":"_277_","width":1,"kind":"dff"},{"ordinal":0,"name":"_278_","width":1,"kind":"dff"},{"ordinal":0,"name":"_279_","width":1,"kind":"dff"},{"ordinal":0,"name":"_280_","width":1,"kind":"dff"},{"ordinal":0,"name":"_281_","width":1,"kind":"dff"},{"ordinal":0,"name":"_282_","width":1,"kind":"dff"},{"ordinal":0,"name":"_283_","width":1,"kind":"dff"},{"ordinal":0,"name":"_284_","width":1,"kind":"dff"},{"ordinal":0,"name":"_285_","width":1,"kind":"dff"},{"ordinal":0,"name":"_286_","width":1,"kind":"dff"},{"ordinal":0,"name":"_287_","width":1,"kind":"dff"},{"ordinal":0,"name":"_288_","width":1,"kind":"dff"},{"ordinal":0,"name":"_289_","width":1,"kind":"dff"},{"ordinal":0,"name":"_290_","width":1,"kind":"dff"},{"ordinal":0,"name":"_291_","width":1,"kind":"dff"},{"ordinal":0,"name":"_292_","width":1,"kind":"dff"},{"ordinal":0,"name":"_293_","width":1,"kind":"dff"},{"ordinal":0,"name":"_294_","width":1,"kind":"dff"},{"ordinal":0,"name":"_295_","width":1,"kind":"dff"},{"ordinal":0,"name":"_296_","width":1,"kind":"dff"},{"ordinal":0,"name":"_297_","width":1,"kind":"dff"},{"ordinal":0,"name":"y","width":1,"kind":"output"}],"boundaryCount":2,"internalCount":29,"sin":"sin","shift":"shift","sout":"sout"}' END FAULT METADATA */
/* Generated by Yosys 0.58+35 (git sha1 9a12d9255, clang++ 18.1.3 -fPIC -O3) */

module b09_scan(reset, clock, x, y, sin, shift, sout, tck, test);
  input reset;
  wire reset;
  input clock;
  wire clock;
  input x;
  wire x;
  output y;
  wire y;
  input sin;
  wire sin;
  input shift;
  wire shift;
  output sout;
  wire sout;
  input tck;
  wire tck;
  input test;
  wire test;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire \__BoundaryScanRegister_input__0__.dout ;
  wire \__BoundaryScanRegister_input__0__.sout ;
  wire \__BoundaryScanRegister_output__1__.sin ;
  wire \__uuf__._000_ ;
  wire \__uuf__._001_ ;
  wire \__uuf__._002_ ;
  wire \__uuf__._003_ ;
  wire \__uuf__._004_ ;
  wire \__uuf__._005_ ;
  wire \__uuf__._006_ ;
  wire \__uuf__._007_ ;
  wire \__uuf__._008_ ;
  wire \__uuf__._009_ ;
  wire \__uuf__._010_ ;
  wire \__uuf__._011_ ;
  wire \__uuf__._012_ ;
  wire \__uuf__._013_ ;
  wire \__uuf__._014_ ;
  wire \__uuf__._015_ ;
  wire \__uuf__._016_ ;
  wire \__uuf__._017_ ;
  wire \__uuf__._018_ ;
  wire \__uuf__._019_ ;
  wire \__uuf__._020_ ;
  wire \__uuf__._021_ ;
  wire \__uuf__._022_ ;
  wire \__uuf__._023_ ;
  wire \__uuf__._024_ ;
  wire \__uuf__._025_ ;
  wire \__uuf__._026_ ;
  wire \__uuf__._027_ ;
  wire \__uuf__._028_ ;
  wire \__uuf__._029_ ;
  wire \__uuf__._030_ ;
  wire \__uuf__._031_ ;
  wire \__uuf__._032_ ;
  wire \__uuf__._033_ ;
  wire \__uuf__._034_ ;
  wire \__uuf__._035_ ;
  wire \__uuf__._036_ ;
  wire \__uuf__._037_ ;
  wire \__uuf__._038_ ;
  wire \__uuf__._039_ ;
  wire \__uuf__._040_ ;
  wire \__uuf__._041_ ;
  wire \__uuf__._042_ ;
  wire \__uuf__._043_ ;
  wire \__uuf__._044_ ;
  wire \__uuf__._045_ ;
  wire \__uuf__._046_ ;
  wire \__uuf__._047_ ;
  wire \__uuf__._048_ ;
  wire \__uuf__._049_ ;
  wire \__uuf__._050_ ;
  wire \__uuf__._051_ ;
  wire \__uuf__._052_ ;
  wire \__uuf__._053_ ;
  wire \__uuf__._054_ ;
  wire \__uuf__._055_ ;
  wire \__uuf__._056_ ;
  wire \__uuf__._057_ ;
  wire \__uuf__._058_ ;
  wire \__uuf__._059_ ;
  wire \__uuf__._060_ ;
  wire \__uuf__._061_ ;
  wire \__uuf__._062_ ;
  wire \__uuf__._063_ ;
  wire \__uuf__._064_ ;
  wire \__uuf__._065_ ;
  wire \__uuf__._066_ ;
  wire \__uuf__._067_ ;
  wire \__uuf__._068_ ;
  wire \__uuf__._069_ ;
  wire \__uuf__._070_ ;
  wire \__uuf__._071_ ;
  wire \__uuf__._072_ ;
  wire \__uuf__._073_ ;
  wire \__uuf__._074_ ;
  wire \__uuf__._075_ ;
  wire \__uuf__._076_ ;
  wire \__uuf__._077_ ;
  wire \__uuf__._078_ ;
  wire \__uuf__._079_ ;
  wire \__uuf__._080_ ;
  wire \__uuf__._081_ ;
  wire \__uuf__._082_ ;
  wire \__uuf__._083_ ;
  wire \__uuf__._084_ ;
  wire \__uuf__._085_ ;
  wire \__uuf__._086_ ;
  wire \__uuf__._087_ ;
  wire \__uuf__._088_ ;
  wire \__uuf__._089_ ;
  wire \__uuf__._090_ ;
  wire \__uuf__._091_ ;
  wire \__uuf__._092_ ;
  wire \__uuf__._093_ ;
  wire \__uuf__._094_ ;
  wire \__uuf__._095_ ;
  wire \__uuf__._096_ ;
  wire \__uuf__._097_ ;
  wire \__uuf__._098_ ;
  wire \__uuf__._099_ ;
  wire \__uuf__._100_ ;
  wire \__uuf__._101_ ;
  wire \__uuf__._102_ ;
  wire \__uuf__._103_ ;
  wire \__uuf__._104_ ;
  wire \__uuf__._105_ ;
  wire \__uuf__._106_ ;
  wire \__uuf__._107_ ;
  wire \__uuf__._108_ ;
  wire \__uuf__._109_ ;
  wire \__uuf__._110_ ;
  wire \__uuf__._111_ ;
  wire \__uuf__._112_ ;
  wire \__uuf__._113_ ;
  wire \__uuf__._114_ ;
  wire \__uuf__._115_ ;
  wire \__uuf__._116_ ;
  wire \__uuf__._117_ ;
  wire \__uuf__._118_ ;
  wire \__uuf__._119_ ;
  wire \__uuf__._120_ ;
  wire \__uuf__._121_ ;
  wire \__uuf__._122_ ;
  wire \__uuf__._123_ ;
  wire \__uuf__._124_ ;
  wire \__uuf__._125_ ;
  wire \__uuf__._126_ ;
  wire \__uuf__._127_ ;
  wire \__uuf__._128_ ;
  wire \__uuf__._129_ ;
  wire \__uuf__._130_ ;
  wire \__uuf__._131_ ;
  wire \__uuf__._132_ ;
  wire \__uuf__._133_ ;
  wire \__uuf__.__clk_source__ ;
  wire \__uuf__.d_in[0] ;
  wire \__uuf__.d_in[1] ;
  wire \__uuf__.d_in[2] ;
  wire \__uuf__.d_in[3] ;
  wire \__uuf__.d_in[4] ;
  wire \__uuf__.d_in[5] ;
  wire \__uuf__.d_in[6] ;
  wire \__uuf__.d_in[7] ;
  wire \__uuf__.d_in[8] ;
  wire \__uuf__.d_out[0] ;
  wire \__uuf__.d_out[1] ;
  wire \__uuf__.d_out[2] ;
  wire \__uuf__.d_out[3] ;
  wire \__uuf__.d_out[4] ;
  wire \__uuf__.d_out[5] ;
  wire \__uuf__.d_out[6] ;
  wire \__uuf__.old[0] ;
  wire \__uuf__.old[1] ;
  wire \__uuf__.old[2] ;
  wire \__uuf__.old[3] ;
  wire \__uuf__.old[4] ;
  wire \__uuf__.old[5] ;
  wire \__uuf__.old[6] ;
  wire \__uuf__.old[7] ;
  wire \__uuf__.stato[0] ;
  wire \__uuf__.stato[1] ;
  wire \__uuf__.stato[2] ;
  wire \__uuf__.stato[3] ;
  INV_X1 _33_ (
    .I(reset),
    .ZN(_00_)
  );
  MUX2_X1 _34_ (
    .I0(x),
    .I1(\__BoundaryScanRegister_input__0__.sout ),
    .S(test),
    .Z(\__BoundaryScanRegister_input__0__.dout )
  );
  MUX2_X1 _35_ (
    .I0(\__BoundaryScanRegister_input__0__.dout ),
    .I1(sin),
    .S(shift),
    .Z(_02_)
  );
  MUX2_X1 _36_ (
    .I0(y),
    .I1(\__BoundaryScanRegister_output__1__.sin ),
    .S(shift),
    .Z(_03_)
  );
  MUX2_X1 _37_ (
    .I0(clock),
    .I1(tck),
    .S(test),
    .Z(\__uuf__.__clk_source__ )
  );
  MUX2_X1 _38_ (
    .I0(\__uuf__._058_ ),
    .I1(\__uuf__.d_out[6] ),
    .S(shift),
    .Z(_32_)
  );
  MUX2_X1 _39_ (
    .I0(\__uuf__._057_ ),
    .I1(\__uuf__.d_out[5] ),
    .S(shift),
    .Z(_31_)
  );
  MUX2_X1 _40_ (
    .I0(\__uuf__._056_ ),
    .I1(\__uuf__.d_out[4] ),
    .S(shift),
    .Z(_30_)
  );
  MUX2_X1 _41_ (
    .I0(\__uuf__._055_ ),
    .I1(\__uuf__.d_out[3] ),
    .S(shift),
    .Z(_29_)
  );
  MUX2_X1 _42_ (
    .I0(\__uuf__._054_ ),
    .I1(\__uuf__.d_out[2] ),
    .S(shift),
    .Z(_28_)
  );
  MUX2_X1 _43_ (
    .I0(\__uuf__._053_ ),
    .I1(\__uuf__.d_out[1] ),
    .S(shift),
    .Z(_27_)
  );
  MUX2_X1 _44_ (
    .I0(\__uuf__._052_ ),
    .I1(\__uuf__.d_out[0] ),
    .S(shift),
    .Z(_26_)
  );
  MUX2_X1 _45_ (
    .I0(\__uuf__._051_ ),
    .I1(\__uuf__.d_in[8] ),
    .S(shift),
    .Z(_25_)
  );
  MUX2_X1 _46_ (
    .I0(\__uuf__._050_ ),
    .I1(\__uuf__.d_in[7] ),
    .S(shift),
    .Z(_24_)
  );
  MUX2_X1 _47_ (
    .I0(\__uuf__._049_ ),
    .I1(\__uuf__.d_in[6] ),
    .S(shift),
    .Z(_23_)
  );
  MUX2_X1 _48_ (
    .I0(\__uuf__._048_ ),
    .I1(\__uuf__.d_in[5] ),
    .S(shift),
    .Z(_22_)
  );
  MUX2_X1 _49_ (
    .I0(\__uuf__._047_ ),
    .I1(\__uuf__.d_in[4] ),
    .S(shift),
    .Z(_21_)
  );
  MUX2_X1 _50_ (
    .I0(\__uuf__._046_ ),
    .I1(\__uuf__.d_in[3] ),
    .S(shift),
    .Z(_20_)
  );
  MUX2_X1 _51_ (
    .I0(\__uuf__._045_ ),
    .I1(\__uuf__.d_in[2] ),
    .S(shift),
    .Z(_19_)
  );
  MUX2_X1 _52_ (
    .I0(\__uuf__._044_ ),
    .I1(\__uuf__.d_in[1] ),
    .S(shift),
    .Z(_18_)
  );
  MUX2_X1 _53_ (
    .I0(\__uuf__._043_ ),
    .I1(\__uuf__.d_in[0] ),
    .S(shift),
    .Z(_17_)
  );
  MUX2_X1 _54_ (
    .I0(\__uuf__._042_ ),
    .I1(y),
    .S(shift),
    .Z(_16_)
  );
  MUX2_X1 _55_ (
    .I0(\__uuf__._041_ ),
    .I1(\__uuf__.stato[3] ),
    .S(shift),
    .Z(_15_)
  );
  MUX2_X1 _56_ (
    .I0(\__uuf__._002_ ),
    .I1(\__uuf__.stato[2] ),
    .S(shift),
    .Z(_14_)
  );
  MUX2_X1 _57_ (
    .I0(\__uuf__._001_ ),
    .I1(\__uuf__.stato[1] ),
    .S(shift),
    .Z(_13_)
  );
  MUX2_X1 _58_ (
    .I0(\__uuf__._000_ ),
    .I1(\__uuf__.old[7] ),
    .S(shift),
    .Z(_12_)
  );
  MUX2_X1 _59_ (
    .I0(\__uuf__._040_ ),
    .I1(\__uuf__.old[6] ),
    .S(shift),
    .Z(_11_)
  );
  MUX2_X1 _60_ (
    .I0(\__uuf__._039_ ),
    .I1(\__uuf__.old[5] ),
    .S(shift),
    .Z(_10_)
  );
  MUX2_X1 _61_ (
    .I0(\__uuf__._038_ ),
    .I1(\__uuf__.old[4] ),
    .S(shift),
    .Z(_09_)
  );
  MUX2_X1 _62_ (
    .I0(\__uuf__._037_ ),
    .I1(\__uuf__.old[3] ),
    .S(shift),
    .Z(_08_)
  );
  MUX2_X1 _63_ (
    .I0(\__uuf__._036_ ),
    .I1(\__uuf__.old[2] ),
    .S(shift),
    .Z(_07_)
  );
  MUX2_X1 _64_ (
    .I0(\__uuf__._035_ ),
    .I1(\__uuf__.old[1] ),
    .S(shift),
    .Z(_06_)
  );
  MUX2_X1 _65_ (
    .I0(\__uuf__._034_ ),
    .I1(\__uuf__.old[0] ),
    .S(shift),
    .Z(_05_)
  );
  MUX2_X1 _66_ (
    .I0(\__uuf__._033_ ),
    .I1(\__BoundaryScanRegister_input__0__.sout ),
    .S(shift),
    .Z(_04_)
  );
  INV_X1 _67_ (
    .I(reset),
    .ZN(_01_)
  );
  DFFRNQ_X1 _68_ (
    .CLK(tck),
    .D(_02_),
    .Q(\__BoundaryScanRegister_input__0__.sout ),
    .RN(_00_)
  );
  DFFRNQ_X1 _69_ (
    .CLK(tck),
    .D(_03_),
    .Q(sout),
    .RN(_01_)
  );
  INV_X1 \__uuf__._134_  (
    .I(\__uuf__.d_out[0] ),
    .ZN(\__uuf__._126_ )
  );
  INV_X1 \__uuf__._135_  (
    .I(\__uuf__.d_in[0] ),
    .ZN(\__uuf__._127_ )
  );
  INV_X1 \__uuf__._136_  (
    .I(\__uuf__.old[7] ),
    .ZN(\__uuf__._128_ )
  );
  INV_X1 \__uuf__._137_  (
    .I(\__uuf__.old[6] ),
    .ZN(\__uuf__._129_ )
  );
  INV_X1 \__uuf__._138_  (
    .I(\__uuf__.old[5] ),
    .ZN(\__uuf__._130_ )
  );
  INV_X1 \__uuf__._139_  (
    .I(\__uuf__.old[4] ),
    .ZN(\__uuf__._131_ )
  );
  INV_X1 \__uuf__._140_  (
    .I(\__uuf__.old[3] ),
    .ZN(\__uuf__._132_ )
  );
  INV_X1 \__uuf__._141_  (
    .I(\__uuf__.old[2] ),
    .ZN(\__uuf__._133_ )
  );
  INV_X1 \__uuf__._142_  (
    .I(\__uuf__.old[1] ),
    .ZN(\__uuf__._059_ )
  );
  INV_X1 \__uuf__._143_  (
    .I(\__uuf__.old[0] ),
    .ZN(\__uuf__._060_ )
  );
  INV_X1 \__uuf__._144_  (
    .I(\__uuf__.stato[2] ),
    .ZN(\__uuf__._061_ )
  );
  INV_X1 \__uuf__._145_  (
    .I(\__uuf__.stato[3] ),
    .ZN(\__uuf__._062_ )
  );
  INV_X1 \__uuf__._146_  (
    .I(reset),
    .ZN(\__uuf__._003_ )
  );
  OR2_X1 \__uuf__._147_  (
    .A1(\__uuf__.stato[2] ),
    .A2(\__uuf__.stato[3] ),
    .Z(\__uuf__._063_ )
  );
  NOR2_X1 \__uuf__._148_  (
    .A1(\__uuf__.stato[0] ),
    .A2(\__uuf__._063_ ),
    .ZN(\__uuf__._064_ )
  );
  NOR3_X1 \__uuf__._149_  (
    .A1(\__uuf__.stato[1] ),
    .A2(\__uuf__.stato[0] ),
    .A3(\__uuf__._063_ ),
    .ZN(\__uuf__._065_ )
  );
  NOR2_X1 \__uuf__._150_  (
    .A1(\__uuf__.d_in[0] ),
    .A2(\__uuf__._061_ ),
    .ZN(\__uuf__._066_ )
  );
  NOR2_X1 \__uuf__._151_  (
    .A1(\__uuf__._065_ ),
    .A2(\__uuf__._066_ ),
    .ZN(\__uuf__._067_ )
  );
  XOR2_X1 \__uuf__._152_  (
    .A1(\__uuf__.d_in[3] ),
    .A2(\__uuf__.old[2] ),
    .Z(\__uuf__._068_ )
  );
  XOR2_X1 \__uuf__._153_  (
    .A1(\__uuf__.d_in[5] ),
    .A2(\__uuf__.old[4] ),
    .Z(\__uuf__._069_ )
  );
  XOR2_X1 \__uuf__._154_  (
    .A1(\__uuf__.d_in[8] ),
    .A2(\__uuf__.old[7] ),
    .Z(\__uuf__._070_ )
  );
  XOR2_X1 \__uuf__._155_  (
    .A1(\__uuf__.d_in[2] ),
    .A2(\__uuf__.old[1] ),
    .Z(\__uuf__._071_ )
  );
  XOR2_X1 \__uuf__._156_  (
    .A1(\__uuf__.d_in[1] ),
    .A2(\__uuf__.old[0] ),
    .Z(\__uuf__._072_ )
  );
  XOR2_X1 \__uuf__._157_  (
    .A1(\__uuf__.d_in[4] ),
    .A2(\__uuf__.old[3] ),
    .Z(\__uuf__._073_ )
  );
  XOR2_X1 \__uuf__._158_  (
    .A1(\__uuf__.d_in[7] ),
    .A2(\__uuf__.old[6] ),
    .Z(\__uuf__._074_ )
  );
  XOR2_X1 \__uuf__._159_  (
    .A1(\__uuf__.d_in[6] ),
    .A2(\__uuf__.old[5] ),
    .Z(\__uuf__._075_ )
  );
  NOR4_X1 \__uuf__._160_  (
    .A1(\__uuf__._068_ ),
    .A2(\__uuf__._069_ ),
    .A3(\__uuf__._072_ ),
    .A4(\__uuf__._073_ ),
    .ZN(\__uuf__._076_ )
  );
  NOR4_X1 \__uuf__._161_  (
    .A1(\__uuf__._070_ ),
    .A2(\__uuf__._071_ ),
    .A3(\__uuf__._074_ ),
    .A4(\__uuf__._075_ ),
    .ZN(\__uuf__._077_ )
  );
  NAND3_X1 \__uuf__._162_  (
    .A1(\__uuf__.stato[3] ),
    .A2(\__uuf__._076_ ),
    .A3(\__uuf__._077_ ),
    .ZN(\__uuf__._078_ )
  );
  NAND2_X1 \__uuf__._163_  (
    .A1(\__uuf__.d_in[0] ),
    .A2(\__uuf__.stato[1] ),
    .ZN(\__uuf__._079_ )
  );
  NAND2_X1 \__uuf__._164_  (
    .A1(\__uuf__._127_ ),
    .A2(\__uuf__.stato[3] ),
    .ZN(\__uuf__._080_ )
  );
  NAND3_X1 \__uuf__._165_  (
    .A1(\__uuf__._078_ ),
    .A2(\__uuf__._079_ ),
    .A3(\__uuf__._080_ ),
    .ZN(\__uuf__._002_ )
  );
  AND4_X1 \__uuf__._166_  (
    .A1(\__uuf__._067_ ),
    .A2(\__uuf__._078_ ),
    .A3(\__uuf__._079_ ),
    .A4(\__uuf__._080_ ),
    .Z(\__uuf__._081_ )
  );
  AND2_X1 \__uuf__._167_  (
    .A1(\__uuf__.d_in[8] ),
    .A2(\__uuf__._063_ ),
    .Z(\__uuf__._082_ )
  );
  MUX2_X1 \__uuf__._168_  (
    .I0(\__BoundaryScanRegister_output__1__.sin ),
    .I1(\__uuf__._082_ ),
    .S(\__uuf__._081_ ),
    .Z(\__uuf__._058_ )
  );
  NAND2_X1 \__uuf__._169_  (
    .A1(\__BoundaryScanRegister_output__1__.sin ),
    .A2(\__uuf__.stato[1] ),
    .ZN(\__uuf__._083_ )
  );
  NAND2_X1 \__uuf__._170_  (
    .A1(\__uuf__.d_in[7] ),
    .A2(\__uuf__._063_ ),
    .ZN(\__uuf__._084_ )
  );
  NAND2_X1 \__uuf__._171_  (
    .A1(\__uuf__._083_ ),
    .A2(\__uuf__._084_ ),
    .ZN(\__uuf__._085_ )
  );
  MUX2_X1 \__uuf__._172_  (
    .I0(\__uuf__.d_out[6] ),
    .I1(\__uuf__._085_ ),
    .S(\__uuf__._081_ ),
    .Z(\__uuf__._057_ )
  );
  NAND2_X1 \__uuf__._173_  (
    .A1(\__uuf__.d_out[6] ),
    .A2(\__uuf__.stato[1] ),
    .ZN(\__uuf__._086_ )
  );
  NAND2_X1 \__uuf__._174_  (
    .A1(\__uuf__.d_in[6] ),
    .A2(\__uuf__._063_ ),
    .ZN(\__uuf__._087_ )
  );
  NAND2_X1 \__uuf__._175_  (
    .A1(\__uuf__._086_ ),
    .A2(\__uuf__._087_ ),
    .ZN(\__uuf__._088_ )
  );
  MUX2_X1 \__uuf__._176_  (
    .I0(\__uuf__.d_out[5] ),
    .I1(\__uuf__._088_ ),
    .S(\__uuf__._081_ ),
    .Z(\__uuf__._056_ )
  );
  NAND2_X1 \__uuf__._177_  (
    .A1(\__uuf__.d_out[5] ),
    .A2(\__uuf__.stato[1] ),
    .ZN(\__uuf__._089_ )
  );
  NAND2_X1 \__uuf__._178_  (
    .A1(\__uuf__.d_in[5] ),
    .A2(\__uuf__._063_ ),
    .ZN(\__uuf__._090_ )
  );
  NAND2_X1 \__uuf__._179_  (
    .A1(\__uuf__._089_ ),
    .A2(\__uuf__._090_ ),
    .ZN(\__uuf__._091_ )
  );
  MUX2_X1 \__uuf__._180_  (
    .I0(\__uuf__.d_out[4] ),
    .I1(\__uuf__._091_ ),
    .S(\__uuf__._081_ ),
    .Z(\__uuf__._055_ )
  );
  NAND2_X1 \__uuf__._181_  (
    .A1(\__uuf__.d_out[4] ),
    .A2(\__uuf__.stato[1] ),
    .ZN(\__uuf__._092_ )
  );
  NAND2_X1 \__uuf__._182_  (
    .A1(\__uuf__.d_in[4] ),
    .A2(\__uuf__._063_ ),
    .ZN(\__uuf__._093_ )
  );
  NAND2_X1 \__uuf__._183_  (
    .A1(\__uuf__._092_ ),
    .A2(\__uuf__._093_ ),
    .ZN(\__uuf__._094_ )
  );
  MUX2_X1 \__uuf__._184_  (
    .I0(\__uuf__.d_out[3] ),
    .I1(\__uuf__._094_ ),
    .S(\__uuf__._081_ ),
    .Z(\__uuf__._054_ )
  );
  NAND2_X1 \__uuf__._185_  (
    .A1(\__uuf__.d_out[3] ),
    .A2(\__uuf__.stato[1] ),
    .ZN(\__uuf__._095_ )
  );
  NAND2_X1 \__uuf__._186_  (
    .A1(\__uuf__.d_in[3] ),
    .A2(\__uuf__._063_ ),
    .ZN(\__uuf__._096_ )
  );
  NAND2_X1 \__uuf__._187_  (
    .A1(\__uuf__._095_ ),
    .A2(\__uuf__._096_ ),
    .ZN(\__uuf__._097_ )
  );
  MUX2_X1 \__uuf__._188_  (
    .I0(\__uuf__.d_out[2] ),
    .I1(\__uuf__._097_ ),
    .S(\__uuf__._081_ ),
    .Z(\__uuf__._053_ )
  );
  NAND2_X1 \__uuf__._189_  (
    .A1(\__uuf__.d_out[2] ),
    .A2(\__uuf__.stato[1] ),
    .ZN(\__uuf__._098_ )
  );
  NAND2_X1 \__uuf__._190_  (
    .A1(\__uuf__.d_in[2] ),
    .A2(\__uuf__._063_ ),
    .ZN(\__uuf__._099_ )
  );
  NAND2_X1 \__uuf__._191_  (
    .A1(\__uuf__._098_ ),
    .A2(\__uuf__._099_ ),
    .ZN(\__uuf__._100_ )
  );
  MUX2_X1 \__uuf__._192_  (
    .I0(\__uuf__.d_out[1] ),
    .I1(\__uuf__._100_ ),
    .S(\__uuf__._081_ ),
    .Z(\__uuf__._052_ )
  );
  NAND2_X1 \__uuf__._193_  (
    .A1(\__uuf__.d_out[1] ),
    .A2(\__uuf__.stato[1] ),
    .ZN(\__uuf__._101_ )
  );
  NAND2_X1 \__uuf__._194_  (
    .A1(\__uuf__.d_in[1] ),
    .A2(\__uuf__._063_ ),
    .ZN(\__uuf__._102_ )
  );
  NAND2_X1 \__uuf__._195_  (
    .A1(\__uuf__._101_ ),
    .A2(\__uuf__._102_ ),
    .ZN(\__uuf__._103_ )
  );
  MUX2_X1 \__uuf__._196_  (
    .I0(\__uuf__.d_out[0] ),
    .I1(\__uuf__._103_ ),
    .S(\__uuf__._081_ ),
    .Z(\__uuf__._051_ )
  );
  AOI21_X1 \__uuf__._197_  (
    .A1(\__uuf__._076_ ),
    .A2(\__uuf__._077_ ),
    .B(\__uuf__._062_ ),
    .ZN(\__uuf__._104_ )
  );
  NAND2_X1 \__uuf__._198_  (
    .A1(\__uuf__._061_ ),
    .A2(\__uuf__._080_ ),
    .ZN(\__uuf__._105_ )
  );
  OAI22_X1 \__uuf__._199_  (
    .A1(\__uuf__.d_in[0] ),
    .A2(\__BoundaryScanRegister_input__0__.dout ),
    .B1(\__uuf__._104_ ),
    .B2(\__uuf__._105_ ),
    .ZN(\__uuf__._106_ )
  );
  AOI22_X1 \__uuf__._200_  (
    .A1(\__uuf__.stato[1] ),
    .A2(\__BoundaryScanRegister_input__0__.dout ),
    .B1(\__uuf__._065_ ),
    .B2(\__uuf__.d_in[8] ),
    .ZN(\__uuf__._107_ )
  );
  NAND2_X1 \__uuf__._201_  (
    .A1(\__uuf__._106_ ),
    .A2(\__uuf__._107_ ),
    .ZN(\__uuf__._050_ )
  );
  AND2_X1 \__uuf__._202_  (
    .A1(\__uuf__._127_ ),
    .A2(\__uuf__._063_ ),
    .Z(\__uuf__._108_ )
  );
  OR2_X1 \__uuf__._203_  (
    .A1(\__uuf__.stato[1] ),
    .A2(\__uuf__._108_ ),
    .Z(\__uuf__._109_ )
  );
  AOI22_X1 \__uuf__._204_  (
    .A1(\__uuf__.d_in[7] ),
    .A2(\__uuf__._065_ ),
    .B1(\__uuf__._109_ ),
    .B2(\__uuf__.d_in[8] ),
    .ZN(\__uuf__._110_ )
  );
  INV_X1 \__uuf__._205_  (
    .I(\__uuf__._110_ ),
    .ZN(\__uuf__._049_ )
  );
  AOI22_X1 \__uuf__._206_  (
    .A1(\__uuf__.d_in[6] ),
    .A2(\__uuf__._065_ ),
    .B1(\__uuf__._109_ ),
    .B2(\__uuf__.d_in[7] ),
    .ZN(\__uuf__._111_ )
  );
  INV_X1 \__uuf__._207_  (
    .I(\__uuf__._111_ ),
    .ZN(\__uuf__._048_ )
  );
  AOI22_X1 \__uuf__._208_  (
    .A1(\__uuf__.d_in[5] ),
    .A2(\__uuf__._065_ ),
    .B1(\__uuf__._109_ ),
    .B2(\__uuf__.d_in[6] ),
    .ZN(\__uuf__._112_ )
  );
  INV_X1 \__uuf__._209_  (
    .I(\__uuf__._112_ ),
    .ZN(\__uuf__._047_ )
  );
  AOI22_X1 \__uuf__._210_  (
    .A1(\__uuf__.d_in[4] ),
    .A2(\__uuf__._065_ ),
    .B1(\__uuf__._109_ ),
    .B2(\__uuf__.d_in[5] ),
    .ZN(\__uuf__._113_ )
  );
  INV_X1 \__uuf__._211_  (
    .I(\__uuf__._113_ ),
    .ZN(\__uuf__._046_ )
  );
  AOI22_X1 \__uuf__._212_  (
    .A1(\__uuf__.d_in[3] ),
    .A2(\__uuf__._065_ ),
    .B1(\__uuf__._109_ ),
    .B2(\__uuf__.d_in[4] ),
    .ZN(\__uuf__._114_ )
  );
  INV_X1 \__uuf__._213_  (
    .I(\__uuf__._114_ ),
    .ZN(\__uuf__._045_ )
  );
  AOI22_X1 \__uuf__._214_  (
    .A1(\__uuf__.d_in[2] ),
    .A2(\__uuf__._065_ ),
    .B1(\__uuf__._109_ ),
    .B2(\__uuf__.d_in[3] ),
    .ZN(\__uuf__._115_ )
  );
  INV_X1 \__uuf__._215_  (
    .I(\__uuf__._115_ ),
    .ZN(\__uuf__._044_ )
  );
  AOI22_X1 \__uuf__._216_  (
    .A1(\__uuf__.d_in[1] ),
    .A2(\__uuf__._065_ ),
    .B1(\__uuf__._109_ ),
    .B2(\__uuf__.d_in[2] ),
    .ZN(\__uuf__._116_ )
  );
  INV_X1 \__uuf__._217_  (
    .I(\__uuf__._116_ ),
    .ZN(\__uuf__._043_ )
  );
  AOI22_X1 \__uuf__._218_  (
    .A1(\__uuf__.d_in[0] ),
    .A2(\__uuf__._065_ ),
    .B1(\__uuf__._109_ ),
    .B2(\__uuf__.d_in[1] ),
    .ZN(\__uuf__._117_ )
  );
  INV_X1 \__uuf__._219_  (
    .I(\__uuf__._117_ ),
    .ZN(\__uuf__._042_ )
  );
  NOR2_X1 \__uuf__._220_  (
    .A1(y),
    .A2(\__uuf__._067_ ),
    .ZN(\__uuf__._118_ )
  );
  NAND2_X1 \__uuf__._221_  (
    .A1(\__uuf__.d_in[0] ),
    .A2(\__uuf__._104_ ),
    .ZN(\__uuf__._119_ )
  );
  NAND2_X1 \__uuf__._222_  (
    .A1(\__uuf__._127_ ),
    .A2(\__uuf__.stato[1] ),
    .ZN(\__uuf__._120_ )
  );
  NOR2_X1 \__uuf__._223_  (
    .A1(\__uuf__._126_ ),
    .A2(\__uuf__._120_ ),
    .ZN(\__uuf__._121_ )
  );
  NOR3_X1 \__uuf__._224_  (
    .A1(\__uuf__.stato[2] ),
    .A2(\__uuf__._065_ ),
    .A3(\__uuf__._121_ ),
    .ZN(\__uuf__._122_ )
  );
  AOI21_X1 \__uuf__._225_  (
    .A1(\__uuf__._119_ ),
    .A2(\__uuf__._122_ ),
    .B(\__uuf__._118_ ),
    .ZN(\__uuf__._041_ )
  );
  NOR2_X1 \__uuf__._226_  (
    .A1(\__uuf__._064_ ),
    .A2(\__uuf__._108_ ),
    .ZN(\__uuf__._123_ )
  );
  NAND2_X1 \__uuf__._227_  (
    .A1(\__uuf__.d_in[0] ),
    .A2(\__uuf__._082_ ),
    .ZN(\__uuf__._124_ )
  );
  OAI21_X1 \__uuf__._228_  (
    .A1(\__uuf__._128_ ),
    .A2(\__uuf__._123_ ),
    .B(\__uuf__._124_ ),
    .ZN(\__uuf__._040_ )
  );
  OAI22_X1 \__uuf__._229_  (
    .A1(\__uuf__._127_ ),
    .A2(\__uuf__._084_ ),
    .B1(\__uuf__._123_ ),
    .B2(\__uuf__._129_ ),
    .ZN(\__uuf__._039_ )
  );
  OAI22_X1 \__uuf__._230_  (
    .A1(\__uuf__._127_ ),
    .A2(\__uuf__._087_ ),
    .B1(\__uuf__._123_ ),
    .B2(\__uuf__._130_ ),
    .ZN(\__uuf__._038_ )
  );
  OAI22_X1 \__uuf__._231_  (
    .A1(\__uuf__._127_ ),
    .A2(\__uuf__._090_ ),
    .B1(\__uuf__._123_ ),
    .B2(\__uuf__._131_ ),
    .ZN(\__uuf__._037_ )
  );
  OAI22_X1 \__uuf__._232_  (
    .A1(\__uuf__._127_ ),
    .A2(\__uuf__._093_ ),
    .B1(\__uuf__._123_ ),
    .B2(\__uuf__._132_ ),
    .ZN(\__uuf__._036_ )
  );
  OAI22_X1 \__uuf__._233_  (
    .A1(\__uuf__._127_ ),
    .A2(\__uuf__._096_ ),
    .B1(\__uuf__._123_ ),
    .B2(\__uuf__._133_ ),
    .ZN(\__uuf__._035_ )
  );
  OAI22_X1 \__uuf__._234_  (
    .A1(\__uuf__._127_ ),
    .A2(\__uuf__._099_ ),
    .B1(\__uuf__._123_ ),
    .B2(\__uuf__._059_ ),
    .ZN(\__uuf__._034_ )
  );
  OAI22_X1 \__uuf__._235_  (
    .A1(\__uuf__._127_ ),
    .A2(\__uuf__._102_ ),
    .B1(\__uuf__._123_ ),
    .B2(\__uuf__._060_ ),
    .ZN(\__uuf__._033_ )
  );
  NAND2_X1 \__uuf__._236_  (
    .A1(\__uuf__.d_in[0] ),
    .A2(\__uuf__.stato[2] ),
    .ZN(\__uuf__._125_ )
  );
  NAND3_X1 \__uuf__._237_  (
    .A1(\__uuf__._119_ ),
    .A2(\__uuf__._120_ ),
    .A3(\__uuf__._125_ ),
    .ZN(\__uuf__._000_ )
  );
  OR2_X1 \__uuf__._238_  (
    .A1(\__uuf__.stato[0] ),
    .A2(\__uuf__._066_ ),
    .Z(\__uuf__._001_ )
  );
  INV_X1 \__uuf__._239_  (
    .I(reset),
    .ZN(\__uuf__._004_ )
  );
  INV_X1 \__uuf__._240_  (
    .I(reset),
    .ZN(\__uuf__._005_ )
  );
  INV_X1 \__uuf__._241_  (
    .I(reset),
    .ZN(\__uuf__._006_ )
  );
  INV_X1 \__uuf__._242_  (
    .I(reset),
    .ZN(\__uuf__._007_ )
  );
  INV_X1 \__uuf__._243_  (
    .I(reset),
    .ZN(\__uuf__._008_ )
  );
  INV_X1 \__uuf__._244_  (
    .I(reset),
    .ZN(\__uuf__._009_ )
  );
  INV_X1 \__uuf__._245_  (
    .I(reset),
    .ZN(\__uuf__._010_ )
  );
  INV_X1 \__uuf__._246_  (
    .I(reset),
    .ZN(\__uuf__._011_ )
  );
  INV_X1 \__uuf__._247_  (
    .I(reset),
    .ZN(\__uuf__._012_ )
  );
  INV_X1 \__uuf__._248_  (
    .I(reset),
    .ZN(\__uuf__._013_ )
  );
  INV_X1 \__uuf__._249_  (
    .I(reset),
    .ZN(\__uuf__._014_ )
  );
  INV_X1 \__uuf__._250_  (
    .I(reset),
    .ZN(\__uuf__._015_ )
  );
  INV_X1 \__uuf__._251_  (
    .I(reset),
    .ZN(\__uuf__._016_ )
  );
  INV_X1 \__uuf__._252_  (
    .I(reset),
    .ZN(\__uuf__._017_ )
  );
  INV_X1 \__uuf__._253_  (
    .I(reset),
    .ZN(\__uuf__._018_ )
  );
  INV_X1 \__uuf__._254_  (
    .I(reset),
    .ZN(\__uuf__._019_ )
  );
  INV_X1 \__uuf__._255_  (
    .I(reset),
    .ZN(\__uuf__._020_ )
  );
  INV_X1 \__uuf__._256_  (
    .I(reset),
    .ZN(\__uuf__._021_ )
  );
  INV_X1 \__uuf__._257_  (
    .I(reset),
    .ZN(\__uuf__._022_ )
  );
  INV_X1 \__uuf__._258_  (
    .I(reset),
    .ZN(\__uuf__._023_ )
  );
  INV_X1 \__uuf__._259_  (
    .I(reset),
    .ZN(\__uuf__._024_ )
  );
  INV_X1 \__uuf__._260_  (
    .I(reset),
    .ZN(\__uuf__._025_ )
  );
  INV_X1 \__uuf__._261_  (
    .I(reset),
    .ZN(\__uuf__._026_ )
  );
  INV_X1 \__uuf__._262_  (
    .I(reset),
    .ZN(\__uuf__._027_ )
  );
  INV_X1 \__uuf__._263_  (
    .I(reset),
    .ZN(\__uuf__._028_ )
  );
  INV_X1 \__uuf__._264_  (
    .I(reset),
    .ZN(\__uuf__._029_ )
  );
  INV_X1 \__uuf__._265_  (
    .I(reset),
    .ZN(\__uuf__._030_ )
  );
  INV_X1 \__uuf__._266_  (
    .I(reset),
    .ZN(\__uuf__._031_ )
  );
  INV_X1 \__uuf__._267_  (
    .I(reset),
    .ZN(\__uuf__._032_ )
  );
  DFFRNQ_X1 \__uuf__._268_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_04_),
    .Q(\__uuf__.old[0] ),
    .RN(\__uuf__._003_ )
  );
  DFFRNQ_X1 \__uuf__._269_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_05_),
    .Q(\__uuf__.old[1] ),
    .RN(\__uuf__._004_ )
  );
  DFFRNQ_X1 \__uuf__._270_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_06_),
    .Q(\__uuf__.old[2] ),
    .RN(\__uuf__._005_ )
  );
  DFFRNQ_X1 \__uuf__._271_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_07_),
    .Q(\__uuf__.old[3] ),
    .RN(\__uuf__._006_ )
  );
  DFFRNQ_X1 \__uuf__._272_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_08_),
    .Q(\__uuf__.old[4] ),
    .RN(\__uuf__._007_ )
  );
  DFFRNQ_X1 \__uuf__._273_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_09_),
    .Q(\__uuf__.old[5] ),
    .RN(\__uuf__._008_ )
  );
  DFFRNQ_X1 \__uuf__._274_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_10_),
    .Q(\__uuf__.old[6] ),
    .RN(\__uuf__._009_ )
  );
  DFFRNQ_X1 \__uuf__._275_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_11_),
    .Q(\__uuf__.old[7] ),
    .RN(\__uuf__._010_ )
  );
  DFFSNQ_X1 \__uuf__._276_  (
    .CLK(clock),
    .D(1'b0),
    .Q(\__uuf__.stato[0] ),
    .SN(\__uuf__._011_ )
  );
  DFFRNQ_X1 \__uuf__._277_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_12_),
    .Q(\__uuf__.stato[1] ),
    .RN(\__uuf__._012_ )
  );
  DFFRNQ_X1 \__uuf__._278_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_13_),
    .Q(\__uuf__.stato[2] ),
    .RN(\__uuf__._013_ )
  );
  DFFRNQ_X1 \__uuf__._279_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_14_),
    .Q(\__uuf__.stato[3] ),
    .RN(\__uuf__._014_ )
  );
  DFFRNQ_X1 \__uuf__._280_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_15_),
    .Q(y),
    .RN(\__uuf__._015_ )
  );
  DFFRNQ_X1 \__uuf__._281_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_16_),
    .Q(\__uuf__.d_in[0] ),
    .RN(\__uuf__._016_ )
  );
  DFFRNQ_X1 \__uuf__._282_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_17_),
    .Q(\__uuf__.d_in[1] ),
    .RN(\__uuf__._017_ )
  );
  DFFRNQ_X1 \__uuf__._283_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_18_),
    .Q(\__uuf__.d_in[2] ),
    .RN(\__uuf__._018_ )
  );
  DFFRNQ_X1 \__uuf__._284_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_19_),
    .Q(\__uuf__.d_in[3] ),
    .RN(\__uuf__._019_ )
  );
  DFFRNQ_X1 \__uuf__._285_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_20_),
    .Q(\__uuf__.d_in[4] ),
    .RN(\__uuf__._020_ )
  );
  DFFRNQ_X1 \__uuf__._286_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_21_),
    .Q(\__uuf__.d_in[5] ),
    .RN(\__uuf__._021_ )
  );
  DFFRNQ_X1 \__uuf__._287_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_22_),
    .Q(\__uuf__.d_in[6] ),
    .RN(\__uuf__._022_ )
  );
  DFFRNQ_X1 \__uuf__._288_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_23_),
    .Q(\__uuf__.d_in[7] ),
    .RN(\__uuf__._023_ )
  );
  DFFRNQ_X1 \__uuf__._289_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_24_),
    .Q(\__uuf__.d_in[8] ),
    .RN(\__uuf__._024_ )
  );
  DFFRNQ_X1 \__uuf__._290_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_25_),
    .Q(\__uuf__.d_out[0] ),
    .RN(\__uuf__._025_ )
  );
  DFFRNQ_X1 \__uuf__._291_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_26_),
    .Q(\__uuf__.d_out[1] ),
    .RN(\__uuf__._026_ )
  );
  DFFRNQ_X1 \__uuf__._292_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_27_),
    .Q(\__uuf__.d_out[2] ),
    .RN(\__uuf__._027_ )
  );
  DFFRNQ_X1 \__uuf__._293_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_28_),
    .Q(\__uuf__.d_out[3] ),
    .RN(\__uuf__._028_ )
  );
  DFFRNQ_X1 \__uuf__._294_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_29_),
    .Q(\__uuf__.d_out[4] ),
    .RN(\__uuf__._029_ )
  );
  DFFRNQ_X1 \__uuf__._295_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_30_),
    .Q(\__uuf__.d_out[5] ),
    .RN(\__uuf__._030_ )
  );
  DFFRNQ_X1 \__uuf__._296_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_31_),
    .Q(\__uuf__.d_out[6] ),
    .RN(\__uuf__._031_ )
  );
  DFFRNQ_X1 \__uuf__._297_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_32_),
    .Q(\__BoundaryScanRegister_output__1__.sin ),
    .RN(\__uuf__._032_ )
  );
endmodule

