/* Generated by Yosys 0.58+35 (git sha1 9a12d9255, clang++ 18.1.3 -fPIC -O3) */

(* top =  1  *)
(* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/fsm/fsm.v:1.1-38.10" *)
module fsm(i, clk, rst, q);
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/fsm/fsm.v:2.11-2.12" *)
  input i;
  wire i;
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/fsm/fsm.v:3.11-3.14" *)
  input clk;
  wire clk;
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/fsm/fsm.v:4.11-4.14" *)
  input rst;
  wire rst;
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/fsm/fsm.v:5.16-5.17" *)
  output q;
  wire q;
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/fsm/fsm.v:30.5-36.8" *)
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/fsm/fsm.v:9.15-9.24" *)
  wire [1:0] nextState;
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/fsm/fsm.v:8.15-8.20" *)
  wire [1:0] state;
  sg13g2_inv_1 _11_ (
    .A(rst),
    .Y(_01_)
  );
  sg13g2_and3_1 _12_ (
    .A(state[1]),
    .B(state[0]),
    .C(i),
    .X(_00_)
  );
  sg13g2_nor2b_1 _13_ (
    .A(state[0]),
    .B_N(state[1]),
    .Y(_04_)
  );
  sg13g2_nand2b_1 _14_ (
    .A_N(state[1]),
    .B(state[0]),
    .Y(_05_)
  );
  sg13g2_a21oi_1 _15_ (
    .A1(i),
    .A2(_05_),
    .B1(_04_),
    .Y(_06_)
  );
  sg13g2_a21oi_1 _16_ (
    .A1(i),
    .A2(_04_),
    .B1(_06_),
    .Y(nextState[0])
  );
  sg13g2_nand3b_1 _17_ (
    .A_N(state[1]),
    .B(state[0]),
    .C(i),
    .Y(_07_)
  );
  sg13g2_nand2b_1 _18_ (
    .A_N(_04_),
    .B(_07_),
    .Y(nextState[1])
  );
  sg13g2_inv_1 _19_ (
    .A(rst),
    .Y(_02_)
  );
  sg13g2_inv_1 _20_ (
    .A(rst),
    .Y(_03_)
  );
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/fsm/fsm.v:30.5-36.8" *)
  sg13g2_dfrbp_1 _21_ (
    .CLK(clk),
    .D(_00_),
    .Q(q),
    .Q_N(_10_),
    .RESET_B(_01_)
  );
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/fsm/fsm.v:11.5-18.8" *)
  sg13g2_dfrbp_1 _22_ (
    .CLK(clk),
    .D(nextState[0]),
    .Q(state[0]),
    .Q_N(_09_),
    .RESET_B(_02_)
  );
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/fsm/fsm.v:11.5-18.8" *)
  sg13g2_dfrbp_1 _23_ (
    .CLK(clk),
    .D(nextState[1]),
    .Q(state[1]),
    .Q_N(_08_),
    .RESET_B(_03_)
  );
endmodule
