/*
    Automatically generated by Fault
    Do not modify.
    Generated on: 2026-02-26 19:04:13
*/
/* FAULT METADATA: '{"internalCount":3,"order":[{"kind":"input","ordinal":0,"width":1,"name":"i"},{"kind":"dff","ordinal":0,"width":1,"name":"_21_"},{"kind":"dff","ordinal":0,"width":1,"name":"_22_"},{"kind":"dff","ordinal":0,"width":1,"name":"_23_"},{"kind":"output","ordinal":0,"width":1,"name":"q"}],"boundaryCount":2,"sout":"sout","shift":"shift","sin":"sin"}' END FAULT METADATA */
/* Generated by Yosys 0.58+35 (git sha1 9a12d9255, clang++ 18.1.3 -fPIC -O3) */

module fsm(i, clk, rst, q, sin, shift, sout, tck, test);
  input i;
  wire i;
  input clk;
  wire clk;
  input rst;
  wire rst;
  output q;
  wire q;
  input sin;
  wire sin;
  input shift;
  wire shift;
  output sout;
  wire sout;
  input tck;
  wire tck;
  input test;
  wire test;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire \__BoundaryScanRegister_input__0__.dout ;
  wire \__BoundaryScanRegister_input__0__.sout ;
  wire \__BoundaryScanRegister_output__1__.sin ;
  wire \__uuf__._00_ ;
  wire \__uuf__._01_ ;
  wire \__uuf__._02_ ;
  wire \__uuf__._03_ ;
  wire \__uuf__._04_ ;
  wire \__uuf__._05_ ;
  wire \__uuf__._06_ ;
  wire \__uuf__._07_ ;
  wire \__uuf__._08_ ;
  wire \__uuf__._09_ ;
  wire \__uuf__._10_ ;
  wire \__uuf__.__clk_source__ ;
  wire \__uuf__.nextState[0] ;
  wire \__uuf__.nextState[1] ;
  wire \__uuf__.state[0] ;
  sg13g2_mux2_1 _07_ (
    .A0(i),
    .A1(\__BoundaryScanRegister_input__0__.sout ),
    .S(test),
    .X(\__BoundaryScanRegister_input__0__.dout )
  );
  sg13g2_mux2_1 _08_ (
    .A0(\__BoundaryScanRegister_input__0__.dout ),
    .A1(sin),
    .S(shift),
    .X(_00_)
  );
  sg13g2_mux2_1 _09_ (
    .A0(q),
    .A1(\__BoundaryScanRegister_output__1__.sin ),
    .S(shift),
    .X(_01_)
  );
  sg13g2_mux2_1 _10_ (
    .A0(clk),
    .A1(tck),
    .S(test),
    .X(\__uuf__.__clk_source__ )
  );
  sg13g2_mux2_1 _11_ (
    .A0(\__uuf__.nextState[1] ),
    .A1(\__uuf__.state[0] ),
    .S(shift),
    .X(_04_)
  );
  sg13g2_mux2_1 _12_ (
    .A0(\__uuf__.nextState[0] ),
    .A1(q),
    .S(shift),
    .X(_03_)
  );
  sg13g2_mux2_1 _13_ (
    .A0(\__uuf__._00_ ),
    .A1(\__BoundaryScanRegister_input__0__.sout ),
    .S(shift),
    .X(_02_)
  );
  sg13g2_dfrbp_1 _14_ (
    .CLK(tck),
    .D(_00_),
    .Q(\__BoundaryScanRegister_input__0__.sout ),
    .Q_N(_06_),
    .RESET_B(rst)
  );
  sg13g2_dfrbp_1 _15_ (
    .CLK(tck),
    .D(_01_),
    .Q(sout),
    .Q_N(_05_),
    .RESET_B(rst)
  );
  sg13g2_inv_1 \__uuf__._11_  (
    .A(rst),
    .Y(\__uuf__._01_ )
  );
  sg13g2_and3_1 \__uuf__._12_  (
    .A(\__BoundaryScanRegister_output__1__.sin ),
    .B(\__uuf__.state[0] ),
    .C(\__BoundaryScanRegister_input__0__.dout ),
    .X(\__uuf__._00_ )
  );
  sg13g2_nor2b_1 \__uuf__._13_  (
    .A(\__uuf__.state[0] ),
    .B_N(\__BoundaryScanRegister_output__1__.sin ),
    .Y(\__uuf__._04_ )
  );
  sg13g2_nand2b_1 \__uuf__._14_  (
    .A_N(\__BoundaryScanRegister_output__1__.sin ),
    .B(\__uuf__.state[0] ),
    .Y(\__uuf__._05_ )
  );
  sg13g2_a21oi_1 \__uuf__._15_  (
    .A1(\__BoundaryScanRegister_input__0__.dout ),
    .A2(\__uuf__._05_ ),
    .B1(\__uuf__._04_ ),
    .Y(\__uuf__._06_ )
  );
  sg13g2_a21oi_1 \__uuf__._16_  (
    .A1(\__BoundaryScanRegister_input__0__.dout ),
    .A2(\__uuf__._04_ ),
    .B1(\__uuf__._06_ ),
    .Y(\__uuf__.nextState[0] )
  );
  sg13g2_nand3b_1 \__uuf__._17_  (
    .A_N(\__BoundaryScanRegister_output__1__.sin ),
    .B(\__uuf__.state[0] ),
    .C(\__BoundaryScanRegister_input__0__.dout ),
    .Y(\__uuf__._07_ )
  );
  sg13g2_nand2b_1 \__uuf__._18_  (
    .A_N(\__uuf__._04_ ),
    .B(\__uuf__._07_ ),
    .Y(\__uuf__.nextState[1] )
  );
  sg13g2_inv_1 \__uuf__._19_  (
    .A(rst),
    .Y(\__uuf__._02_ )
  );
  sg13g2_inv_1 \__uuf__._20_  (
    .A(rst),
    .Y(\__uuf__._03_ )
  );
  sg13g2_dfrbp_1 \__uuf__._21_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_02_),
    .Q(q),
    .Q_N(\__uuf__._10_ ),
    .RESET_B(\__uuf__._01_ )
  );
  sg13g2_dfrbp_1 \__uuf__._22_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_03_),
    .Q(\__uuf__.state[0] ),
    .Q_N(\__uuf__._09_ ),
    .RESET_B(\__uuf__._02_ )
  );
  sg13g2_dfrbp_1 \__uuf__._23_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_04_),
    .Q(\__BoundaryScanRegister_output__1__.sin ),
    .Q_N(\__uuf__._08_ ),
    .RESET_B(\__uuf__._03_ )
  );
endmodule

