/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "/home/filippo/Scrivania/proveSintesi/fault/ISCAS89/s27/s27.v:16.1-36.10" *)
module s27(CK, rst, G0, G1, G17, G2, G3);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  (* src = "/home/filippo/Scrivania/proveSintesi/fault/ISCAS89/s27/s27.v:17.7-17.9" *)
  input CK;
  wire CK;
  (* hdlname = "DFF_0 CK" *)
  (* src = "/home/filippo/Scrivania/proveSintesi/fault/ISCAS89/s27/s27.v:22.7-22.23|/home/filippo/Scrivania/proveSintesi/fault/ISCAS89/s27/s27.v:9.7-9.9" *)
  wire \DFF_0.CK ;
  (* hdlname = "DFF_0 D" *)
  (* src = "/home/filippo/Scrivania/proveSintesi/fault/ISCAS89/s27/s27.v:22.7-22.23|/home/filippo/Scrivania/proveSintesi/fault/ISCAS89/s27/s27.v:9.10-9.11" *)
  wire \DFF_0.D ;
  (* hdlname = "DFF_0 Q" *)
  (* src = "/home/filippo/Scrivania/proveSintesi/fault/ISCAS89/s27/s27.v:22.7-22.23|/home/filippo/Scrivania/proveSintesi/fault/ISCAS89/s27/s27.v:10.8-10.9" *)
  wire \DFF_0.Q ;
  (* hdlname = "DFF_1 CK" *)
  (* src = "/home/filippo/Scrivania/proveSintesi/fault/ISCAS89/s27/s27.v:23.7-23.23|/home/filippo/Scrivania/proveSintesi/fault/ISCAS89/s27/s27.v:9.7-9.9" *)
  wire \DFF_1.CK ;
  (* hdlname = "DFF_1 D" *)
  (* src = "/home/filippo/Scrivania/proveSintesi/fault/ISCAS89/s27/s27.v:23.7-23.23|/home/filippo/Scrivania/proveSintesi/fault/ISCAS89/s27/s27.v:9.10-9.11" *)
  wire \DFF_1.D ;
  (* hdlname = "DFF_1 Q" *)
  (* src = "/home/filippo/Scrivania/proveSintesi/fault/ISCAS89/s27/s27.v:23.7-23.23|/home/filippo/Scrivania/proveSintesi/fault/ISCAS89/s27/s27.v:10.8-10.9" *)
  wire \DFF_1.Q ;
  (* hdlname = "DFF_2 CK" *)
  (* src = "/home/filippo/Scrivania/proveSintesi/fault/ISCAS89/s27/s27.v:24.7-24.23|/home/filippo/Scrivania/proveSintesi/fault/ISCAS89/s27/s27.v:9.7-9.9" *)
  wire \DFF_2.CK ;
  (* hdlname = "DFF_2 D" *)
  (* src = "/home/filippo/Scrivania/proveSintesi/fault/ISCAS89/s27/s27.v:24.7-24.23|/home/filippo/Scrivania/proveSintesi/fault/ISCAS89/s27/s27.v:9.10-9.11" *)
  wire \DFF_2.D ;
  (* hdlname = "DFF_2 Q" *)
  (* src = "/home/filippo/Scrivania/proveSintesi/fault/ISCAS89/s27/s27.v:24.7-24.23|/home/filippo/Scrivania/proveSintesi/fault/ISCAS89/s27/s27.v:10.8-10.9" *)
  wire \DFF_2.Q ;
  (* src = "/home/filippo/Scrivania/proveSintesi/fault/ISCAS89/s27/s27.v:17.14-17.16" *)
  input G0;
  wire G0;
  (* src = "/home/filippo/Scrivania/proveSintesi/fault/ISCAS89/s27/s27.v:17.17-17.19" *)
  input G1;
  wire G1;
  (* src = "/home/filippo/Scrivania/proveSintesi/fault/ISCAS89/s27/s27.v:20.11-20.14" *)
  wire G10;
  (* src = "/home/filippo/Scrivania/proveSintesi/fault/ISCAS89/s27/s27.v:20.18-20.21" *)
  wire G11;
  (* src = "/home/filippo/Scrivania/proveSintesi/fault/ISCAS89/s27/s27.v:20.25-20.28" *)
  wire G13;
  (* src = "/home/filippo/Scrivania/proveSintesi/fault/ISCAS89/s27/s27.v:18.8-18.11" *)
  output G17;
  wire G17;
  (* src = "/home/filippo/Scrivania/proveSintesi/fault/ISCAS89/s27/s27.v:17.20-17.22" *)
  input G2;
  wire G2;
  (* src = "/home/filippo/Scrivania/proveSintesi/fault/ISCAS89/s27/s27.v:17.23-17.25" *)
  input G3;
  wire G3;
  (* src = "/home/filippo/Scrivania/proveSintesi/fault/ISCAS89/s27/s27.v:20.8-20.10" *)
  wire G5;
  (* src = "/home/filippo/Scrivania/proveSintesi/fault/ISCAS89/s27/s27.v:20.15-20.17" *)
  wire G6;
  (* src = "/home/filippo/Scrivania/proveSintesi/fault/ISCAS89/s27/s27.v:20.22-20.24" *)
  wire G7;
  (* src = "/home/filippo/Scrivania/proveSintesi/fault/ISCAS89/s27/s27.v:17.10-17.13" *)
  input rst;
  wire rst;
  INV_X1 _05_ (
    .I(\DFF_0.Q ),
    .ZN(_00_)
  );
  INV_X1 _06_ (
    .I(G0),
    .ZN(_01_)
  );
  NOR2_X1 _07_ (
    .A1(\DFF_2.Q ),
    .A2(G1),
    .ZN(_02_)
  );
  AND2_X1 _08_ (
    .A1(G3),
    .A2(_02_),
    .Z(_03_)
  );
  AOI22_X1 _09_ (
    .A1(_01_),
    .A2(\DFF_1.Q ),
    .B1(_02_),
    .B2(G3),
    .ZN(_04_)
  );
  NOR2_X1 _10_ (
    .A1(\DFF_0.Q ),
    .A2(_04_),
    .ZN(\DFF_1.D )
  );
  OR2_X1 _11_ (
    .A1(\DFF_0.Q ),
    .A2(_04_),
    .Z(G17)
  );
  AOI21_X1 _12_ (
    .A1(_00_),
    .A2(_03_),
    .B(_01_),
    .ZN(\DFF_0.D )
  );
  NOR2_X1 _13_ (
    .A1(G2),
    .A2(_02_),
    .ZN(\DFF_2.D )
  );
  (* src = "/home/filippo/Scrivania/proveSintesi/fault/ISCAS89/s27/s27.v:22.7-22.23|/home/filippo/Scrivania/proveSintesi/fault/ISCAS89/s27/s27.v:12.1-13.10" *)
  DFFRNQ_X1 _14_ (
    .CLK(CK),
    .D(\DFF_0.D ),
    .Q(\DFF_0.Q ),
    .RN(1'h1)
  );
  (* src = "/home/filippo/Scrivania/proveSintesi/fault/ISCAS89/s27/s27.v:23.7-23.23|/home/filippo/Scrivania/proveSintesi/fault/ISCAS89/s27/s27.v:12.1-13.10" *)
  DFFRNQ_X1 _15_ (
    .CLK(CK),
    .D(\DFF_1.D ),
    .Q(\DFF_1.Q ),
    .RN(1'h1)
  );
  (* src = "/home/filippo/Scrivania/proveSintesi/fault/ISCAS89/s27/s27.v:24.7-24.23|/home/filippo/Scrivania/proveSintesi/fault/ISCAS89/s27/s27.v:12.1-13.10" *)
  DFFRNQ_X1 _16_ (
    .CLK(CK),
    .D(\DFF_2.D ),
    .Q(\DFF_2.Q ),
    .RN(1'h1)
  );
  assign \DFF_0.CK  = CK;
  assign \DFF_1.CK  = CK;
  assign \DFF_2.CK  = CK;
  assign G10 = \DFF_0.D ;
  assign G11 = \DFF_1.D ;
  assign G13 = \DFF_2.D ;
  assign G5 = \DFF_0.Q ;
  assign G6 = \DFF_1.Q ;
  assign G7 = \DFF_2.Q ;
endmodule
