/*
    Automatically generated by Fault
    Do not modify.
    Generated on: 2026-02-26 19:05:47
*/
/* FAULT METADATA: '{"order":[{"width":1,"kind":"dff","ordinal":0,"name":"_20_"},{"width":1,"kind":"dff","ordinal":0,"name":"_21_"},{"width":1,"kind":"dff","ordinal":0,"name":"_22_"},{"width":1,"kind":"dff","ordinal":0,"name":"_23_"},{"width":4,"kind":"output","ordinal":0,"name":"data_out"}],"internalCount":4,"boundaryCount":4,"shift":"shift","sin":"sin","sout":"sout"}' END FAULT METADATA */
/* Generated by Yosys 0.58+35 (git sha1 9a12d9255, clang++ 18.1.3 -fPIC -O3) */

module Counter4Bits(clk, rst, data_out, sin, shift, sout, tck, test);
  input clk;
  wire clk;
  input rst;
  wire rst;
  output [3:0] data_out;
  wire [3:0] data_out;
  input sin;
  wire sin;
  input shift;
  wire shift;
  output sout;
  wire sout;
  input tck;
  wire tck;
  input test;
  wire test;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire \__BoundaryScanRegister_output__0__.din ;
  wire \__BoundaryScanRegister_output__0__.sin ;
  wire \__BoundaryScanRegister_output__0__.sout ;
  wire \__BoundaryScanRegister_output__1__.din ;
  wire \__BoundaryScanRegister_output__1__.sout ;
  wire \__BoundaryScanRegister_output__2__.din ;
  wire \__BoundaryScanRegister_output__2__.sout ;
  wire \__uuf__._00_ ;
  wire \__uuf__._01_ ;
  wire \__uuf__._02_ ;
  wire \__uuf__._03_ ;
  wire \__uuf__._04_ ;
  wire \__uuf__._05_ ;
  wire \__uuf__._06_ ;
  wire \__uuf__._07_ ;
  wire \__uuf__._08_ ;
  wire \__uuf__._09_ ;
  wire \__uuf__.__clk_source__ ;
  wire \__uuf__.d0.Qn ;
  wire \__uuf__.d1.Qn ;
  wire \__uuf__.d2.Qn ;
  wire \__uuf__.d3.Qn ;
  sg13g2_mux2_1 _12_ (
    .A0(\__BoundaryScanRegister_output__0__.din ),
    .A1(\__BoundaryScanRegister_output__0__.sin ),
    .S(shift),
    .X(_00_)
  );
  sg13g2_mux2_1 _13_ (
    .A0(\__BoundaryScanRegister_output__1__.din ),
    .A1(\__BoundaryScanRegister_output__0__.sout ),
    .S(shift),
    .X(_01_)
  );
  sg13g2_mux2_1 _14_ (
    .A0(\__BoundaryScanRegister_output__2__.din ),
    .A1(\__BoundaryScanRegister_output__1__.sout ),
    .S(shift),
    .X(_02_)
  );
  sg13g2_mux2_1 _15_ (
    .A0(\__BoundaryScanRegister_output__0__.sin ),
    .A1(\__BoundaryScanRegister_output__2__.sout ),
    .S(shift),
    .X(_03_)
  );
  sg13g2_mux2_1 _16_ (
    .A0(clk),
    .A1(tck),
    .S(test),
    .X(\__uuf__.__clk_source__ )
  );
  sg13g2_mux2_1 _17_ (
    .A0(\__uuf__._07_ ),
    .A1(\__BoundaryScanRegister_output__2__.din ),
    .S(shift),
    .X(_07_)
  );
  sg13g2_mux2_1 _18_ (
    .A0(\__uuf__._06_ ),
    .A1(\__BoundaryScanRegister_output__1__.din ),
    .S(shift),
    .X(_06_)
  );
  sg13g2_mux2_1 _19_ (
    .A0(\__uuf__._05_ ),
    .A1(\__BoundaryScanRegister_output__0__.din ),
    .S(shift),
    .X(_05_)
  );
  sg13g2_mux2_1 _20_ (
    .A0(\__uuf__._04_ ),
    .A1(sin),
    .S(shift),
    .X(_04_)
  );
  sg13g2_dfrbp_1 _21_ (
    .CLK(tck),
    .D(_03_),
    .Q(sout),
    .Q_N(_09_),
    .RESET_B(rst)
  );
  sg13g2_dfrbp_1 _22_ (
    .CLK(tck),
    .D(_02_),
    .Q(\__BoundaryScanRegister_output__2__.sout ),
    .Q_N(_10_),
    .RESET_B(rst)
  );
  sg13g2_dfrbp_1 _23_ (
    .CLK(tck),
    .D(_00_),
    .Q(\__BoundaryScanRegister_output__0__.sout ),
    .Q_N(_11_),
    .RESET_B(rst)
  );
  sg13g2_dfrbp_1 _24_ (
    .CLK(tck),
    .D(_01_),
    .Q(\__BoundaryScanRegister_output__1__.sout ),
    .Q_N(_08_),
    .RESET_B(rst)
  );
  sg13g2_inv_1 \__uuf__._10_  (
    .A(rst),
    .Y(\__uuf__._00_ )
  );
  sg13g2_nand2_1 \__uuf__._11_  (
    .A(\__BoundaryScanRegister_output__1__.din ),
    .B(\__BoundaryScanRegister_output__0__.din ),
    .Y(\__uuf__._08_ )
  );
  sg13g2_nand3_1 \__uuf__._12_  (
    .A(\__BoundaryScanRegister_output__2__.din ),
    .B(\__BoundaryScanRegister_output__1__.din ),
    .C(\__BoundaryScanRegister_output__0__.din ),
    .Y(\__uuf__._09_ )
  );
  sg13g2_mux2_1 \__uuf__._13_  (
    .A0(\__uuf__.d3.Qn ),
    .A1(\__BoundaryScanRegister_output__0__.sin ),
    .S(\__uuf__._09_ ),
    .X(\__uuf__._07_ )
  );
  sg13g2_mux2_1 \__uuf__._14_  (
    .A0(\__uuf__.d2.Qn ),
    .A1(\__BoundaryScanRegister_output__2__.din ),
    .S(\__uuf__._08_ ),
    .X(\__uuf__._06_ )
  );
  sg13g2_mux2_1 \__uuf__._15_  (
    .A0(\__BoundaryScanRegister_output__1__.din ),
    .A1(\__uuf__.d1.Qn ),
    .S(\__BoundaryScanRegister_output__0__.din ),
    .X(\__uuf__._05_ )
  );
  sg13g2_buf_1 \__uuf__._16_  (
    .A(\__uuf__.d0.Qn ),
    .X(\__uuf__._04_ )
  );
  sg13g2_inv_1 \__uuf__._17_  (
    .A(rst),
    .Y(\__uuf__._01_ )
  );
  sg13g2_inv_1 \__uuf__._18_  (
    .A(rst),
    .Y(\__uuf__._02_ )
  );
  sg13g2_inv_1 \__uuf__._19_  (
    .A(rst),
    .Y(\__uuf__._03_ )
  );
  sg13g2_dfrbp_1 \__uuf__._20_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_04_),
    .Q(\__BoundaryScanRegister_output__0__.din ),
    .Q_N(\__uuf__.d0.Qn ),
    .RESET_B(\__uuf__._00_ )
  );
  sg13g2_dfrbp_1 \__uuf__._21_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_05_),
    .Q(\__BoundaryScanRegister_output__1__.din ),
    .Q_N(\__uuf__.d1.Qn ),
    .RESET_B(\__uuf__._01_ )
  );
  sg13g2_dfrbp_1 \__uuf__._22_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_06_),
    .Q(\__BoundaryScanRegister_output__2__.din ),
    .Q_N(\__uuf__.d2.Qn ),
    .RESET_B(\__uuf__._02_ )
  );
  sg13g2_dfrbp_1 \__uuf__._23_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_07_),
    .Q(\__BoundaryScanRegister_output__0__.sin ),
    .Q_N(\__uuf__.d3.Qn ),
    .RESET_B(\__uuf__._03_ )
  );
  assign data_out = { \__BoundaryScanRegister_output__0__.sin , \__BoundaryScanRegister_output__2__.din , \__BoundaryScanRegister_output__1__.din , \__BoundaryScanRegister_output__0__.din  };
endmodule

