/* Generated by Yosys 0.58+35 (git sha1 9a12d9255, clang++ 18.1.3 -fPIC -O3) */

(* top =  1  *)
(* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/counter/Counter4Bits.v:1.1-48.10" *)
module Counter4Bits(clk, rst, data_out);
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/counter/Counter4Bits.v:2.11-2.14" *)
  input clk;
  wire clk;
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/counter/Counter4Bits.v:3.11-3.14" *)
  input rst;
  wire rst;
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/counter/Counter4Bits.v:4.18-4.26" *)
  output [3:0] data_out;
  wire [3:0] data_out;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/counter/Counter4Bits.v:7.10-7.15" *)
  (* unused_bits = "0" *)
  wire andD2;
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/counter/Counter4Bits.v:7.17-7.22" *)
  (* unused_bits = "0" *)
  wire andD3;
  (* hdlname = "d0 J" *)
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/counter/JkFlipFlop.v:2.11-2.12" *)
  wire \d0.J ;
  (* hdlname = "d0 K" *)
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/counter/JkFlipFlop.v:3.11-3.12" *)
  wire \d0.K ;
  (* hdlname = "d0 Q" *)
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/counter/JkFlipFlop.v:6.16-6.17" *)
  wire \d0.Q ;
  (* hdlname = "d0 Qn" *)
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/counter/JkFlipFlop.v:7.12-7.14" *)
  wire \d0.Qn ;
  (* hdlname = "d0 clk" *)
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/counter/JkFlipFlop.v:4.11-4.14" *)
  wire \d0.clk ;
  (* hdlname = "d0 rst" *)
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/counter/JkFlipFlop.v:5.11-5.14" *)
  wire \d0.rst ;
  (* hdlname = "d1 J" *)
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/counter/JkFlipFlop.v:2.11-2.12" *)
  wire \d1.J ;
  (* hdlname = "d1 K" *)
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/counter/JkFlipFlop.v:3.11-3.12" *)
  wire \d1.K ;
  (* hdlname = "d1 Q" *)
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/counter/JkFlipFlop.v:6.16-6.17" *)
  wire \d1.Q ;
  (* hdlname = "d1 Qn" *)
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/counter/JkFlipFlop.v:7.12-7.14" *)
  wire \d1.Qn ;
  (* hdlname = "d1 clk" *)
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/counter/JkFlipFlop.v:4.11-4.14" *)
  wire \d1.clk ;
  (* hdlname = "d1 rst" *)
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/counter/JkFlipFlop.v:5.11-5.14" *)
  wire \d1.rst ;
  (* hdlname = "d2 J" *)
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/counter/JkFlipFlop.v:2.11-2.12" *)
  (* unused_bits = "0" *)
  wire \d2.J ;
  (* hdlname = "d2 K" *)
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/counter/JkFlipFlop.v:3.11-3.12" *)
  (* unused_bits = "0" *)
  wire \d2.K ;
  (* hdlname = "d2 Q" *)
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/counter/JkFlipFlop.v:6.16-6.17" *)
  wire \d2.Q ;
  (* hdlname = "d2 Qn" *)
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/counter/JkFlipFlop.v:7.12-7.14" *)
  wire \d2.Qn ;
  (* hdlname = "d2 clk" *)
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/counter/JkFlipFlop.v:4.11-4.14" *)
  wire \d2.clk ;
  (* hdlname = "d2 rst" *)
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/counter/JkFlipFlop.v:5.11-5.14" *)
  wire \d2.rst ;
  (* hdlname = "d3 J" *)
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/counter/JkFlipFlop.v:2.11-2.12" *)
  (* unused_bits = "0" *)
  wire \d3.J ;
  (* hdlname = "d3 K" *)
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/counter/JkFlipFlop.v:3.11-3.12" *)
  (* unused_bits = "0" *)
  wire \d3.K ;
  (* hdlname = "d3 Q" *)
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/counter/JkFlipFlop.v:6.16-6.17" *)
  wire \d3.Q ;
  (* hdlname = "d3 Qn" *)
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/counter/JkFlipFlop.v:7.12-7.14" *)
  wire \d3.Qn ;
  (* hdlname = "d3 clk" *)
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/counter/JkFlipFlop.v:4.11-4.14" *)
  wire \d3.clk ;
  (* hdlname = "d3 rst" *)
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/counter/JkFlipFlop.v:5.11-5.14" *)
  wire \d3.rst ;
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/counter/Counter4Bits.v:6.10-6.14" *)
  wire high;
  sg13g2_inv_1 _10_ (
    .A(rst),
    .Y(_00_)
  );
  sg13g2_nand2_1 _11_ (
    .A(\d1.Q ),
    .B(\d0.Q ),
    .Y(_08_)
  );
  sg13g2_nand3_1 _12_ (
    .A(\d2.Q ),
    .B(\d1.Q ),
    .C(\d0.Q ),
    .Y(_09_)
  );
  sg13g2_mux2_1 _13_ (
    .A0(\d3.Qn ),
    .A1(\d3.Q ),
    .S(_09_),
    .X(_07_)
  );
  sg13g2_mux2_1 _14_ (
    .A0(\d2.Qn ),
    .A1(\d2.Q ),
    .S(_08_),
    .X(_06_)
  );
  sg13g2_mux2_1 _15_ (
    .A0(\d1.Q ),
    .A1(\d1.Qn ),
    .S(\d0.Q ),
    .X(_05_)
  );
  sg13g2_buf_1 _16_ (
    .A(\d0.Qn ),
    .X(_04_)
  );
  sg13g2_inv_1 _17_ (
    .A(rst),
    .Y(_01_)
  );
  sg13g2_inv_1 _18_ (
    .A(rst),
    .Y(_02_)
  );
  sg13g2_inv_1 _19_ (
    .A(rst),
    .Y(_03_)
  );
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/counter/JkFlipFlop.v:11.5-25.8" *)
  sg13g2_dfrbp_1 _20_ (
    .CLK(clk),
    .D(_04_),
    .Q(\d0.Q ),
    .Q_N(\d0.Qn ),
    .RESET_B(_00_)
  );
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/counter/JkFlipFlop.v:11.5-25.8" *)
  sg13g2_dfrbp_1 _21_ (
    .CLK(clk),
    .D(_05_),
    .Q(\d1.Q ),
    .Q_N(\d1.Qn ),
    .RESET_B(_01_)
  );
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/counter/JkFlipFlop.v:11.5-25.8" *)
  sg13g2_dfrbp_1 _22_ (
    .CLK(clk),
    .D(_06_),
    .Q(\d2.Q ),
    .Q_N(\d2.Qn ),
    .RESET_B(_02_)
  );
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/counter/JkFlipFlop.v:11.5-25.8" *)
  sg13g2_dfrbp_1 _23_ (
    .CLK(clk),
    .D(_07_),
    .Q(\d3.Q ),
    .Q_N(\d3.Qn ),
    .RESET_B(_03_)
  );
  assign \d1.rst  = rst;
  assign \d1.clk  = clk;
  assign \d1.K  = \d0.Q ;
  assign \d1.J  = \d0.Q ;
  assign \d2.rst  = rst;
  assign \d2.clk  = clk;
  assign \d2.K  = andD2;
  assign \d2.J  = andD2;
  assign \d0.clk  = clk;
  assign \d0.K  = 1'h1;
  assign \d3.rst  = rst;
  assign \d3.clk  = clk;
  assign \d3.K  = andD3;
  assign \d3.J  = andD3;
  assign \d0.J  = 1'h1;
  assign \d0.rst  = rst;
  assign data_out = { \d3.Q , \d2.Q , \d1.Q , \d0.Q  };
  assign high = 1'h1;
endmodule
