/* Generated by Yosys 0.58+35 (git sha1 9a12d9255, clang++ 18.1.3 -fPIC -O3) */

(* top =  1  *)
(* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/register/register.v:1.1-15.10" *)
module register(clk, rst, D, Q);
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/register/register.v:2.11-2.14" *)
  input clk;
  wire clk;
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/register/register.v:3.11-3.14" *)
  input rst;
  wire rst;
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/register/register.v:4.11-4.12" *)
  input D;
  wire D;
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/register/register.v:5.16-5.17" *)
  output Q;
  wire Q;
  wire _0_;
  wire _1_;
  sg13g2_inv_1 _2_ (
    .A(rst),
    .Y(_0_)
  );
  (* src = "/home/filippo/Desktop/ode4ec/faultTests/circuits/register/register.v:8.5-13.8" *)
  sg13g2_dfrbp_1 _3_ (
    .CLK(clk),
    .D(D),
    .Q(Q),
    .Q_N(_1_),
    .RESET_B(_0_)
  );
endmodule
