/* Generated by Yosys 0.58+35 (git sha1 9a12d9255, clang++ 18.1.3 -fPIC -O3) */

(* top =  1  *)
(* src = "b10.v:1.1-178.10" *)
module b10(r_button, g_button, key, start, reset, test, cts, ctr, rts, rtr, clock, v_in, v_out);
  (* src = "b10.v:4.7-4.15" *)
  input r_button;
  wire r_button;
  (* src = "b10.v:5.7-5.15" *)
  input g_button;
  wire g_button;
  (* src = "b10.v:6.7-6.10" *)
  input key;
  wire key;
  (* src = "b10.v:7.7-7.12" *)
  input start;
  wire start;
  (* src = "b10.v:3.7-3.12" *)
  input reset;
  wire reset;
  (* src = "b10.v:8.7-8.11" *)
  input test;
  wire test;
  (* src = "b10.v:19.12-19.15" *)
  output cts;
  wire cts;
  (* src = "b10.v:20.12-20.15" *)
  output ctr;
  wire ctr;
  (* src = "b10.v:9.7-9.10" *)
  input rts;
  wire rts;
  (* src = "b10.v:10.7-10.10" *)
  input rtr;
  wire rtr;
  (* src = "b10.v:2.7-2.12" *)
  input clock;
  wire clock;
  (* src = "b10.v:11.13-11.17" *)
  input [3:0] v_in;
  wire [3:0] v_in;
  (* src = "b10.v:14.18-14.23" *)
  output [3:0] v_out;
  wire [3:0] v_out;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  (* src = "b10.v:18.5-18.11" *)
  wire last_g;
  (* src = "b10.v:18.13-18.19" *)
  wire last_r;
  (* src = "b10.v:17.11-17.15" *)
  wire [3:0] sign;
  (* onehot = 32'd1 *)
  wire [10:0] stato;
  (* src = "b10.v:16.5-16.10" *)
  wire voto0;
  (* src = "b10.v:16.12-16.17" *)
  wire voto1;
  (* src = "b10.v:16.19-16.24" *)
  wire voto2;
  (* src = "b10.v:16.26-16.31" *)
  wire voto3;
  INV_X1 _119_ (
    .I(cts),
    .ZN(_104_)
  );
  INV_X1 _120_ (
    .I(r_button),
    .ZN(_105_)
  );
  INV_X1 _121_ (
    .I(g_button),
    .ZN(_106_)
  );
  INV_X1 _122_ (
    .I(voto3),
    .ZN(_107_)
  );
  INV_X1 _123_ (
    .I(voto0),
    .ZN(_108_)
  );
  INV_X1 _124_ (
    .I(sign[3]),
    .ZN(_109_)
  );
  INV_X1 _125_ (
    .I(stato[7]),
    .ZN(_110_)
  );
  INV_X1 _126_ (
    .I(rts),
    .ZN(_111_)
  );
  INV_X1 _127_ (
    .I(stato[3]),
    .ZN(_112_)
  );
  INV_X1 _128_ (
    .I(stato[6]),
    .ZN(_113_)
  );
  INV_X1 _129_ (
    .I(start),
    .ZN(_114_)
  );
  INV_X1 _130_ (
    .I(rtr),
    .ZN(_115_)
  );
  INV_X1 _131_ (
    .I(test),
    .ZN(_116_)
  );
  INV_X1 _132_ (
    .I(reset),
    .ZN(_010_)
  );
  OR2_X1 _133_ (
    .A1(stato[2]),
    .A2(rtr),
    .Z(_117_)
  );
  NOR2_X1 _134_ (
    .A1(stato[10]),
    .A2(stato[1]),
    .ZN(_118_)
  );
  NAND2_X1 _135_ (
    .A1(rtr),
    .A2(_118_),
    .ZN(_047_)
  );
  NOR2_X1 _136_ (
    .A1(stato[6]),
    .A2(stato[2]),
    .ZN(_048_)
  );
  NOR3_X1 _137_ (
    .A1(stato[6]),
    .A2(stato[2]),
    .A3(stato[0]),
    .ZN(_049_)
  );
  AOI22_X1 _138_ (
    .A1(_117_),
    .A2(_047_),
    .B1(_049_),
    .B2(_118_),
    .ZN(_050_)
  );
  OAI22_X1 _139_ (
    .A1(_047_),
    .A2(_048_),
    .B1(_050_),
    .B2(_104_),
    .ZN(_046_)
  );
  AND2_X1 _140_ (
    .A1(stato[3]),
    .A2(key),
    .Z(_051_)
  );
  NAND2_X1 _141_ (
    .A1(stato[3]),
    .A2(key),
    .ZN(_052_)
  );
  NAND2_X1 _142_ (
    .A1(start),
    .A2(_051_),
    .ZN(_053_)
  );
  NAND2_X1 _143_ (
    .A1(last_r),
    .A2(_053_),
    .ZN(_054_)
  );
  OAI21_X1 _144_ (
    .A1(_105_),
    .A2(_053_),
    .B(_054_),
    .ZN(_045_)
  );
  NAND2_X1 _145_ (
    .A1(last_g),
    .A2(_053_),
    .ZN(_055_)
  );
  OAI21_X1 _146_ (
    .A1(_106_),
    .A2(_053_),
    .B(_055_),
    .ZN(_044_)
  );
  XOR2_X1 _147_ (
    .A1(voto1),
    .A2(voto0),
    .Z(_056_)
  );
  AND2_X1 _148_ (
    .A1(voto2),
    .A2(_056_),
    .Z(_057_)
  );
  OAI21_X1 _149_ (
    .A1(voto2),
    .A2(_056_),
    .B(stato[9]),
    .ZN(_058_)
  );
  OR4_X1 _150_ (
    .A1(stato[7]),
    .A2(stato[5]),
    .A3(stato[3]),
    .A4(stato[6]),
    .Z(_059_)
  );
  OR2_X1 _151_ (
    .A1(stato[0]),
    .A2(_059_),
    .Z(_060_)
  );
  NOR3_X1 _152_ (
    .A1(stato[0]),
    .A2(stato[9]),
    .A3(_059_),
    .ZN(_061_)
  );
  AND2_X1 _153_ (
    .A1(stato[5]),
    .A2(_111_),
    .Z(_062_)
  );
  NAND2_X1 _154_ (
    .A1(stato[5]),
    .A2(_111_),
    .ZN(_063_)
  );
  NOR2_X1 _155_ (
    .A1(_112_),
    .A2(start),
    .ZN(_003_)
  );
  OAI21_X1 _156_ (
    .A1(stato[3]),
    .A2(stato[6]),
    .B(_114_),
    .ZN(_064_)
  );
  AOI21_X1 _157_ (
    .A1(_112_),
    .A2(_113_),
    .B(start),
    .ZN(_065_)
  );
  NOR4_X1 _158_ (
    .A1(_051_),
    .A2(_061_),
    .A3(_062_),
    .A4(_065_),
    .ZN(_066_)
  );
  OAI21_X1 _159_ (
    .A1(stato[7]),
    .A2(stato[5]),
    .B(v_in[3]),
    .ZN(_067_)
  );
  OAI21_X1 _160_ (
    .A1(_057_),
    .A2(_058_),
    .B(_067_),
    .ZN(_068_)
  );
  MUX2_X1 _161_ (
    .I0(voto3),
    .I1(_068_),
    .S(_066_),
    .Z(_043_)
  );
  OAI21_X1 _162_ (
    .A1(last_r),
    .A2(_105_),
    .B(_051_),
    .ZN(_069_)
  );
  NAND4_X1 _163_ (
    .A1(_060_),
    .A2(_063_),
    .A3(_064_),
    .A4(_069_),
    .ZN(_070_)
  );
  OAI21_X1 _164_ (
    .A1(stato[7]),
    .A2(stato[5]),
    .B(v_in[2]),
    .ZN(_071_)
  );
  OAI21_X1 _165_ (
    .A1(voto2),
    .A2(_052_),
    .B(_071_),
    .ZN(_072_)
  );
  MUX2_X1 _166_ (
    .I0(_072_),
    .I1(voto2),
    .S(_070_),
    .Z(_042_)
  );
  OAI21_X1 _167_ (
    .A1(last_g),
    .A2(_106_),
    .B(_051_),
    .ZN(_073_)
  );
  NAND4_X1 _168_ (
    .A1(_060_),
    .A2(_063_),
    .A3(_064_),
    .A4(_073_),
    .ZN(_074_)
  );
  OAI21_X1 _169_ (
    .A1(stato[7]),
    .A2(stato[5]),
    .B(v_in[1]),
    .ZN(_075_)
  );
  OAI21_X1 _170_ (
    .A1(voto1),
    .A2(_052_),
    .B(_075_),
    .ZN(_076_)
  );
  MUX2_X1 _171_ (
    .I0(_076_),
    .I1(voto1),
    .S(_074_),
    .Z(_041_)
  );
  NOR2_X1 _172_ (
    .A1(stato[4]),
    .A2(stato[9]),
    .ZN(_077_)
  );
  OR4_X1 _173_ (
    .A1(stato[0]),
    .A2(stato[4]),
    .A3(stato[9]),
    .A4(_059_),
    .Z(_078_)
  );
  NAND3_X1 _174_ (
    .A1(_063_),
    .A2(_064_),
    .A3(_078_),
    .ZN(_079_)
  );
  OAI21_X1 _175_ (
    .A1(stato[7]),
    .A2(stato[5]),
    .B(v_in[0]),
    .ZN(_080_)
  );
  AOI21_X1 _176_ (
    .A1(_109_),
    .A2(stato[4]),
    .B(_051_),
    .ZN(_081_)
  );
  NAND2_X1 _177_ (
    .A1(_080_),
    .A2(_081_),
    .ZN(_082_)
  );
  MUX2_X1 _178_ (
    .I0(_082_),
    .I1(voto0),
    .S(_079_),
    .Z(_040_)
  );
  NAND2_X1 _179_ (
    .A1(stato[2]),
    .A2(rtr),
    .ZN(_083_)
  );
  NAND2_X1 _180_ (
    .A1(v_out[3]),
    .A2(_083_),
    .ZN(_084_)
  );
  OAI21_X1 _181_ (
    .A1(_107_),
    .A2(_083_),
    .B(_084_),
    .ZN(_039_)
  );
  MUX2_X1 _182_ (
    .I0(voto2),
    .I1(v_out[2]),
    .S(_083_),
    .Z(_038_)
  );
  MUX2_X1 _183_ (
    .I0(voto1),
    .I1(v_out[1]),
    .S(_083_),
    .Z(_037_)
  );
  NAND2_X1 _184_ (
    .A1(v_out[0]),
    .A2(_083_),
    .ZN(_085_)
  );
  OAI21_X1 _185_ (
    .A1(_108_),
    .A2(_083_),
    .B(_085_),
    .ZN(_036_)
  );
  NOR2_X1 _186_ (
    .A1(stato[8]),
    .A2(stato[5]),
    .ZN(_086_)
  );
  NOR3_X1 _187_ (
    .A1(stato[8]),
    .A2(stato[5]),
    .A3(stato[0]),
    .ZN(_087_)
  );
  NOR3_X1 _188_ (
    .A1(stato[5]),
    .A2(rts),
    .A3(_087_),
    .ZN(_088_)
  );
  NOR2_X1 _189_ (
    .A1(ctr),
    .A2(_088_),
    .ZN(_089_)
  );
  NOR3_X1 _190_ (
    .A1(stato[8]),
    .A2(_062_),
    .A3(_087_),
    .ZN(_090_)
  );
  NOR2_X1 _191_ (
    .A1(_089_),
    .A2(_090_),
    .ZN(_035_)
  );
  NAND2_X1 _192_ (
    .A1(stato[0]),
    .A2(_116_),
    .ZN(_091_)
  );
  NAND2_X1 _193_ (
    .A1(stato[0]),
    .A2(test),
    .ZN(_092_)
  );
  AOI22_X1 _194_ (
    .A1(sign[3]),
    .A2(_091_),
    .B1(_092_),
    .B2(stato[7]),
    .ZN(_093_)
  );
  INV_X1 _195_ (
    .I(_093_),
    .ZN(_034_)
  );
  NOR2_X1 _196_ (
    .A1(rts),
    .A2(_086_),
    .ZN(_002_)
  );
  NAND4_X1 _197_ (
    .A1(v_in[0]),
    .A2(v_in[1]),
    .A3(v_in[2]),
    .A4(v_in[3]),
    .ZN(_094_)
  );
  NOR2_X1 _198_ (
    .A1(_110_),
    .A2(_094_),
    .ZN(_001_)
  );
  OAI21_X1 _199_ (
    .A1(stato[3]),
    .A2(stato[6]),
    .B(start),
    .ZN(_095_)
  );
  INV_X1 _200_ (
    .I(_095_),
    .ZN(_000_)
  );
  NOR2_X1 _201_ (
    .A1(stato[2]),
    .A2(stato[10]),
    .ZN(_096_)
  );
  OAI21_X1 _202_ (
    .A1(rtr),
    .A2(_096_),
    .B(_077_),
    .ZN(_006_)
  );
  NAND2_X1 _203_ (
    .A1(rtr),
    .A2(stato[1]),
    .ZN(_097_)
  );
  NAND4_X1 _204_ (
    .A1(_107_),
    .A2(voto2),
    .A3(voto1),
    .A4(_108_),
    .ZN(_098_)
  );
  OAI21_X1 _205_ (
    .A1(_083_),
    .A2(_098_),
    .B(_097_),
    .ZN(_005_)
  );
  AOI22_X1 _206_ (
    .A1(stato[6]),
    .A2(_114_),
    .B1(_115_),
    .B2(stato[1]),
    .ZN(_099_)
  );
  NAND2_X1 _207_ (
    .A1(_092_),
    .A2(_099_),
    .ZN(_007_)
  );
  NAND2_X1 _208_ (
    .A1(stato[7]),
    .A2(_094_),
    .ZN(_100_)
  );
  NAND2_X1 _209_ (
    .A1(_091_),
    .A2(_100_),
    .ZN(_008_)
  );
  NAND2_X1 _210_ (
    .A1(stato[8]),
    .A2(rts),
    .ZN(_101_)
  );
  NAND3_X1 _211_ (
    .A1(stato[2]),
    .A2(rtr),
    .A3(_098_),
    .ZN(_102_)
  );
  NAND2_X1 _212_ (
    .A1(_101_),
    .A2(_102_),
    .ZN(_009_)
  );
  AOI22_X1 _213_ (
    .A1(stato[5]),
    .A2(rts),
    .B1(rtr),
    .B2(stato[10]),
    .ZN(_103_)
  );
  INV_X1 _214_ (
    .I(_103_),
    .ZN(_004_)
  );
  INV_X1 _215_ (
    .I(reset),
    .ZN(_011_)
  );
  INV_X1 _216_ (
    .I(reset),
    .ZN(_012_)
  );
  INV_X1 _217_ (
    .I(reset),
    .ZN(_013_)
  );
  INV_X1 _218_ (
    .I(reset),
    .ZN(_014_)
  );
  INV_X1 _219_ (
    .I(reset),
    .ZN(_015_)
  );
  INV_X1 _220_ (
    .I(reset),
    .ZN(_016_)
  );
  INV_X1 _221_ (
    .I(reset),
    .ZN(_017_)
  );
  INV_X1 _222_ (
    .I(reset),
    .ZN(_018_)
  );
  INV_X1 _223_ (
    .I(reset),
    .ZN(_019_)
  );
  INV_X1 _224_ (
    .I(reset),
    .ZN(_020_)
  );
  INV_X1 _225_ (
    .I(reset),
    .ZN(_021_)
  );
  INV_X1 _226_ (
    .I(reset),
    .ZN(_022_)
  );
  INV_X1 _227_ (
    .I(reset),
    .ZN(_023_)
  );
  INV_X1 _228_ (
    .I(reset),
    .ZN(_024_)
  );
  INV_X1 _229_ (
    .I(reset),
    .ZN(_025_)
  );
  INV_X1 _230_ (
    .I(reset),
    .ZN(_026_)
  );
  INV_X1 _231_ (
    .I(reset),
    .ZN(_027_)
  );
  INV_X1 _232_ (
    .I(reset),
    .ZN(_028_)
  );
  INV_X1 _233_ (
    .I(reset),
    .ZN(_029_)
  );
  INV_X1 _234_ (
    .I(reset),
    .ZN(_030_)
  );
  INV_X1 _235_ (
    .I(reset),
    .ZN(_031_)
  );
  INV_X1 _236_ (
    .I(reset),
    .ZN(_032_)
  );
  INV_X1 _237_ (
    .I(reset),
    .ZN(_033_)
  );
  (* src = "b10.v:35.1-175.4" *)
  DFFRNQ_X1 _238_ (
    .CLK(clock),
    .D(_034_),
    .Q(sign[3]),
    .RN(_010_)
  );
  (* src = "b10.v:35.1-175.4" *)
  DFFRNQ_X1 _239_ (
    .CLK(clock),
    .D(_035_),
    .Q(ctr),
    .RN(_011_)
  );
  (* src = "b10.v:35.1-175.4" *)
  DFFRNQ_X1 _240_ (
    .CLK(clock),
    .D(_036_),
    .Q(v_out[0]),
    .RN(_012_)
  );
  (* src = "b10.v:35.1-175.4" *)
  DFFRNQ_X1 _241_ (
    .CLK(clock),
    .D(_037_),
    .Q(v_out[1]),
    .RN(_013_)
  );
  (* src = "b10.v:35.1-175.4" *)
  DFFRNQ_X1 _242_ (
    .CLK(clock),
    .D(_038_),
    .Q(v_out[2]),
    .RN(_014_)
  );
  (* src = "b10.v:35.1-175.4" *)
  DFFRNQ_X1 _243_ (
    .CLK(clock),
    .D(_039_),
    .Q(v_out[3]),
    .RN(_015_)
  );
  (* src = "b10.v:35.1-175.4" *)
  DFFRNQ_X1 _244_ (
    .CLK(clock),
    .D(_040_),
    .Q(voto0),
    .RN(_016_)
  );
  (* src = "b10.v:35.1-175.4" *)
  DFFRNQ_X1 _245_ (
    .CLK(clock),
    .D(_041_),
    .Q(voto1),
    .RN(_017_)
  );
  (* src = "b10.v:35.1-175.4" *)
  DFFRNQ_X1 _246_ (
    .CLK(clock),
    .D(_042_),
    .Q(voto2),
    .RN(_018_)
  );
  (* src = "b10.v:35.1-175.4" *)
  DFFRNQ_X1 _247_ (
    .CLK(clock),
    .D(_043_),
    .Q(voto3),
    .RN(_019_)
  );
  (* src = "b10.v:35.1-175.4" *)
  DFFRNQ_X1 _248_ (
    .CLK(clock),
    .D(_044_),
    .Q(last_g),
    .RN(_020_)
  );
  (* src = "b10.v:35.1-175.4" *)
  DFFRNQ_X1 _249_ (
    .CLK(clock),
    .D(_045_),
    .Q(last_r),
    .RN(_021_)
  );
  (* src = "b10.v:35.1-175.4" *)
  DFFRNQ_X1 _250_ (
    .CLK(clock),
    .D(_046_),
    .Q(cts),
    .RN(_022_)
  );
  DFFSNQ_X1 _251_ (
    .CLK(clock),
    .D(1'h0),
    .Q(stato[0]),
    .SN(_023_)
  );
  DFFRNQ_X1 _252_ (
    .CLK(clock),
    .D(_005_),
    .Q(stato[1]),
    .RN(_024_)
  );
  DFFRNQ_X1 _253_ (
    .CLK(clock),
    .D(_006_),
    .Q(stato[2]),
    .RN(_025_)
  );
  DFFRNQ_X1 _254_ (
    .CLK(clock),
    .D(_000_),
    .Q(stato[3]),
    .RN(_026_)
  );
  DFFRNQ_X1 _255_ (
    .CLK(clock),
    .D(_001_),
    .Q(stato[4]),
    .RN(_027_)
  );
  DFFRNQ_X1 _256_ (
    .CLK(clock),
    .D(_002_),
    .Q(stato[5]),
    .RN(_028_)
  );
  DFFRNQ_X1 _257_ (
    .CLK(clock),
    .D(_007_),
    .Q(stato[6]),
    .RN(_029_)
  );
  DFFRNQ_X1 _258_ (
    .CLK(clock),
    .D(_008_),
    .Q(stato[7]),
    .RN(_030_)
  );
  DFFRNQ_X1 _259_ (
    .CLK(clock),
    .D(_009_),
    .Q(stato[8]),
    .RN(_031_)
  );
  DFFRNQ_X1 _260_ (
    .CLK(clock),
    .D(_003_),
    .Q(stato[9]),
    .RN(_032_)
  );
  DFFRNQ_X1 _261_ (
    .CLK(clock),
    .D(_004_),
    .Q(stato[10]),
    .RN(_033_)
  );
  assign sign[2:0] = 3'h0;
endmodule
