/* Generated by Yosys 0.58+35 (git sha1 9a12d9255, clang++ 18.1.3 -fPIC -O3) */

(* top =  1  *)
(* src = "b13.v:1.1-319.10" *)
module b13(reset, eoc, soc, load_dato, add_mpx2, canale, mux_en, clock, data_in, dsr, errorr, data_out);
  (* src = "b13.v:4.7-4.12" *)
  input reset;
  wire reset;
  (* src = "b13.v:5.7-5.10" *)
  input eoc;
  wire eoc;
  (* src = "b13.v:9.12-9.15" *)
  output soc;
  wire soc;
  (* src = "b13.v:10.12-10.21" *)
  output load_dato;
  wire load_dato;
  (* src = "b13.v:11.12-11.20" *)
  output add_mpx2;
  wire add_mpx2;
  (* src = "b13.v:15.18-15.24" *)
  output [3:0] canale;
  wire [3:0] canale;
  (* src = "b13.v:12.12-12.18" *)
  output mux_en;
  wire mux_en;
  (* src = "b13.v:3.7-3.12" *)
  input clock;
  wire clock;
  (* src = "b13.v:7.13-7.20" *)
  input [7:0] data_in;
  wire [7:0] data_in;
  (* src = "b13.v:6.7-6.10" *)
  input dsr;
  wire dsr;
  (* src = "b13.v:13.12-13.18" *)
  output errorr;
  wire errorr;
  (* src = "b13.v:14.12-14.20" *)
  output data_out;
  wire data_out;
  (* src = "b13.v:255.1-316.4" *)
  wire _000_;
  (* src = "b13.v:222.1-253.4" *)
  wire _001_;
  (* src = "b13.v:222.1-253.4" *)
  wire _002_;
  (* src = "b13.v:255.1-316.4" *)
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  (* onehot = 32'd1 *)
  wire [7:0] S1;
  (* onehot = 32'd1 *)
  wire [3:0] S2;
  (* src = "b13.v:55.5-55.12" *)
  wire confirm;
  (* src = "b13.v:66.11-66.20" *)
  wire [7:0] conta_tmp;
  (* onehot = 32'd1 *)
  wire [3:0] itfc_state;
  (* src = "b13.v:64.15-64.19" *)
  wire load;
  (* src = "b13.v:51.5-51.8" *)
  wire mpx;
  (* onehot = 32'd1 *)
  wire [9:0] next_bit;
  (* src = "b13.v:60.11-60.18" *)
  wire [7:0] out_reg;
  (* src = "b13.v:52.5-52.8" *)
  wire rdy;
  (* src = "b13.v:64.5-64.9" *)
  wire send;
  (* src = "b13.v:53.5-53.14" *)
  wire send_data;
  (* src = "b13.v:58.5-58.12" *)
  wire send_en;
  (* src = "b13.v:56.5-56.9" *)
  wire shot;
  (* src = "b13.v:59.5-59.8" *)
  wire tre;
  (* src = "b13.v:65.12-65.20" *)
  wire [31:0] tx_conta;
  (* src = "b13.v:62.5-62.11" *)
  wire tx_end;
  INV_X1 _265_ (
    .I(canale[2]),
    .ZN(_175_)
  );
  INV_X1 _266_ (
    .I(shot),
    .ZN(_176_)
  );
  INV_X1 _267_ (
    .I(mpx),
    .ZN(_177_)
  );
  INV_X1 _268_ (
    .I(add_mpx2),
    .ZN(_178_)
  );
  INV_X1 _269_ (
    .I(send),
    .ZN(_179_)
  );
  INV_X1 _270_ (
    .I(itfc_state[3]),
    .ZN(_180_)
  );
  INV_X1 _271_ (
    .I(send_en),
    .ZN(_181_)
  );
  INV_X1 _272_ (
    .I(tx_conta[8]),
    .ZN(_182_)
  );
  INV_X1 _273_ (
    .I(S1[6]),
    .ZN(_183_)
  );
  INV_X1 _274_ (
    .I(S2[1]),
    .ZN(_184_)
  );
  INV_X1 _275_ (
    .I(S1[5]),
    .ZN(_185_)
  );
  INV_X1 _276_ (
    .I(itfc_state[1]),
    .ZN(_186_)
  );
  INV_X1 _277_ (
    .I(S2[0]),
    .ZN(_187_)
  );
  INV_X1 _278_ (
    .I(S2[3]),
    .ZN(_188_)
  );
  INV_X1 _279_ (
    .I(S1[1]),
    .ZN(_189_)
  );
  INV_X1 _280_ (
    .I(tre),
    .ZN(_190_)
  );
  INV_X1 _281_ (
    .I(reset),
    .ZN(_025_)
  );
  AND4_X1 _282_ (
    .A1(conta_tmp[3]),
    .A2(canale[2]),
    .A3(canale[1]),
    .A4(canale[0]),
    .Z(_191_)
  );
  NAND2_X1 _283_ (
    .A1(conta_tmp[4]),
    .A2(_191_),
    .ZN(_192_)
  );
  NAND3_X1 _284_ (
    .A1(conta_tmp[5]),
    .A2(conta_tmp[4]),
    .A3(_191_),
    .ZN(_193_)
  );
  NAND4_X1 _285_ (
    .A1(conta_tmp[6]),
    .A2(conta_tmp[5]),
    .A3(conta_tmp[4]),
    .A4(_191_),
    .ZN(_194_)
  );
  XOR2_X1 _286_ (
    .A1(conta_tmp[7]),
    .A2(_194_),
    .Z(_195_)
  );
  NOR2_X1 _287_ (
    .A1(conta_tmp[7]),
    .A2(S1[3]),
    .ZN(_196_)
  );
  AOI21_X1 _288_ (
    .A1(S1[3]),
    .A2(_195_),
    .B(_196_),
    .ZN(_174_)
  );
  XOR2_X1 _289_ (
    .A1(conta_tmp[6]),
    .A2(_193_),
    .Z(_197_)
  );
  NOR2_X1 _290_ (
    .A1(S1[3]),
    .A2(conta_tmp[6]),
    .ZN(_198_)
  );
  AOI21_X1 _291_ (
    .A1(S1[3]),
    .A2(_197_),
    .B(_198_),
    .ZN(_173_)
  );
  XOR2_X1 _292_ (
    .A1(conta_tmp[5]),
    .A2(_192_),
    .Z(_199_)
  );
  NOR2_X1 _293_ (
    .A1(S1[3]),
    .A2(conta_tmp[5]),
    .ZN(_200_)
  );
  AOI21_X1 _294_ (
    .A1(S1[3]),
    .A2(_199_),
    .B(_200_),
    .ZN(_172_)
  );
  XNOR2_X1 _295_ (
    .A1(conta_tmp[4]),
    .A2(_191_),
    .ZN(_201_)
  );
  NOR2_X1 _296_ (
    .A1(S1[3]),
    .A2(conta_tmp[4]),
    .ZN(_202_)
  );
  AOI21_X1 _297_ (
    .A1(S1[3]),
    .A2(_201_),
    .B(_202_),
    .ZN(_171_)
  );
  NAND2_X1 _298_ (
    .A1(S1[3]),
    .A2(canale[0]),
    .ZN(_203_)
  );
  NAND3_X1 _299_ (
    .A1(S1[3]),
    .A2(canale[1]),
    .A3(canale[0]),
    .ZN(_204_)
  );
  NOR2_X1 _300_ (
    .A1(_175_),
    .A2(_204_),
    .ZN(_205_)
  );
  NAND4_X1 _301_ (
    .A1(_195_),
    .A2(_197_),
    .A3(_199_),
    .A4(_201_),
    .ZN(_206_)
  );
  AOI21_X1 _302_ (
    .A1(_205_),
    .A2(_206_),
    .B(conta_tmp[3]),
    .ZN(_207_)
  );
  AOI21_X1 _303_ (
    .A1(conta_tmp[3]),
    .A2(_205_),
    .B(_207_),
    .ZN(_170_)
  );
  AND2_X1 _304_ (
    .A1(rdy),
    .A2(S1[6]),
    .Z(_004_)
  );
  AOI21_X1 _305_ (
    .A1(_183_),
    .A2(S1[7]),
    .B(send_data),
    .ZN(_208_)
  );
  NOR2_X1 _306_ (
    .A1(_004_),
    .A2(_208_),
    .ZN(_169_)
  );
  XNOR2_X1 _307_ (
    .A1(canale[2]),
    .A2(_204_),
    .ZN(_168_)
  );
  XNOR2_X1 _308_ (
    .A1(canale[1]),
    .A2(_203_),
    .ZN(_167_)
  );
  XOR2_X1 _309_ (
    .A1(S1[3]),
    .A2(canale[0]),
    .Z(_166_)
  );
  NOR2_X1 _310_ (
    .A1(_185_),
    .A2(eoc),
    .ZN(_005_)
  );
  AOI21_X1 _311_ (
    .A1(_185_),
    .A2(S1[0]),
    .B(mux_en),
    .ZN(_209_)
  );
  NOR2_X1 _312_ (
    .A1(_005_),
    .A2(_209_),
    .ZN(_165_)
  );
  NAND2_X1 _313_ (
    .A1(S1[5]),
    .A2(eoc),
    .ZN(_210_)
  );
  NOR2_X1 _314_ (
    .A1(load_dato),
    .A2(_005_),
    .ZN(_211_)
  );
  AOI21_X1 _315_ (
    .A1(S1[3]),
    .A2(_210_),
    .B(_211_),
    .ZN(_164_)
  );
  NOR2_X1 _316_ (
    .A1(soc),
    .A2(S1[2]),
    .ZN(_212_)
  );
  NOR2_X1 _317_ (
    .A1(S1[3]),
    .A2(_212_),
    .ZN(_163_)
  );
  NOR2_X1 _318_ (
    .A1(confirm),
    .A2(_184_),
    .ZN(_213_)
  );
  AOI21_X1 _319_ (
    .A1(_184_),
    .A2(S2[2]),
    .B(shot),
    .ZN(_214_)
  );
  NOR2_X1 _320_ (
    .A1(_213_),
    .A2(_214_),
    .ZN(_162_)
  );
  NAND2_X1 _321_ (
    .A1(confirm),
    .A2(S2[1]),
    .ZN(_215_)
  );
  NOR2_X1 _322_ (
    .A1(_177_),
    .A2(_215_),
    .ZN(_006_)
  );
  OAI21_X1 _323_ (
    .A1(send_data),
    .A2(_187_),
    .B(_006_),
    .ZN(_216_)
  );
  NAND2_X1 _324_ (
    .A1(send_data),
    .A2(S2[0]),
    .ZN(_217_)
  );
  NOR2_X1 _325_ (
    .A1(S2[1]),
    .A2(_217_),
    .ZN(_218_)
  );
  OAI21_X1 _326_ (
    .A1(rdy),
    .A2(_218_),
    .B(_216_),
    .ZN(_219_)
  );
  INV_X1 _327_ (
    .I(_219_),
    .ZN(_161_)
  );
  XNOR2_X1 _328_ (
    .A1(mpx),
    .A2(_215_),
    .ZN(_160_)
  );
  OAI21_X1 _329_ (
    .A1(mpx),
    .A2(_215_),
    .B(_178_),
    .ZN(_159_)
  );
  NAND2_X1 _330_ (
    .A1(_176_),
    .A2(itfc_state[0]),
    .ZN(_220_)
  );
  AND2_X1 _331_ (
    .A1(shot),
    .A2(itfc_state[0]),
    .Z(_007_)
  );
  NOR2_X1 _332_ (
    .A1(load),
    .A2(_007_),
    .ZN(_221_)
  );
  AOI21_X1 _333_ (
    .A1(itfc_state[2]),
    .A2(_220_),
    .B(_221_),
    .ZN(_158_)
  );
  NOR2_X1 _334_ (
    .A1(send),
    .A2(itfc_state[2]),
    .ZN(_222_)
  );
  NOR2_X1 _335_ (
    .A1(itfc_state[1]),
    .A2(_222_),
    .ZN(_157_)
  );
  NAND2_X1 _336_ (
    .A1(itfc_state[3]),
    .A2(tx_end),
    .ZN(_223_)
  );
  AOI21_X1 _337_ (
    .A1(itfc_state[3]),
    .A2(tx_end),
    .B(confirm),
    .ZN(_224_)
  );
  AOI21_X1 _338_ (
    .A1(_180_),
    .A2(itfc_state[0]),
    .B(_224_),
    .ZN(_156_)
  );
  NAND2_X1 _339_ (
    .A1(load),
    .A2(_190_),
    .ZN(_225_)
  );
  MUX2_X1 _340_ (
    .I0(data_in[7]),
    .I1(out_reg[7]),
    .S(_225_),
    .Z(_155_)
  );
  MUX2_X1 _341_ (
    .I0(data_in[6]),
    .I1(out_reg[6]),
    .S(_225_),
    .Z(_154_)
  );
  MUX2_X1 _342_ (
    .I0(data_in[5]),
    .I1(out_reg[5]),
    .S(_225_),
    .Z(_153_)
  );
  MUX2_X1 _343_ (
    .I0(data_in[4]),
    .I1(out_reg[4]),
    .S(_225_),
    .Z(_152_)
  );
  MUX2_X1 _344_ (
    .I0(data_in[3]),
    .I1(out_reg[3]),
    .S(_225_),
    .Z(_151_)
  );
  MUX2_X1 _345_ (
    .I0(data_in[2]),
    .I1(out_reg[2]),
    .S(_225_),
    .Z(_150_)
  );
  MUX2_X1 _346_ (
    .I0(data_in[1]),
    .I1(out_reg[1]),
    .S(_225_),
    .Z(_149_)
  );
  MUX2_X1 _347_ (
    .I0(data_in[0]),
    .I1(out_reg[0]),
    .S(_225_),
    .Z(_148_)
  );
  AND2_X1 _348_ (
    .A1(send),
    .A2(dsr),
    .Z(_226_)
  );
  NAND2_X1 _349_ (
    .A1(send),
    .A2(dsr),
    .ZN(_227_)
  );
  OAI21_X1 _350_ (
    .A1(load),
    .A2(errorr),
    .B(_225_),
    .ZN(_228_)
  );
  AOI22_X1 _351_ (
    .A1(tre),
    .A2(_226_),
    .B1(_228_),
    .B2(_179_),
    .ZN(_147_)
  );
  AND2_X1 _352_ (
    .A1(tx_conta[31]),
    .A2(_181_),
    .Z(_146_)
  );
  AND2_X1 _353_ (
    .A1(_181_),
    .A2(tx_conta[30]),
    .Z(_145_)
  );
  AND2_X1 _354_ (
    .A1(_181_),
    .A2(tx_conta[29]),
    .Z(_144_)
  );
  AND2_X1 _355_ (
    .A1(_181_),
    .A2(tx_conta[28]),
    .Z(_143_)
  );
  AND2_X1 _356_ (
    .A1(_181_),
    .A2(tx_conta[27]),
    .Z(_142_)
  );
  AND2_X1 _357_ (
    .A1(_181_),
    .A2(tx_conta[26]),
    .Z(_141_)
  );
  AND2_X1 _358_ (
    .A1(_181_),
    .A2(tx_conta[25]),
    .Z(_140_)
  );
  AND2_X1 _359_ (
    .A1(_181_),
    .A2(tx_conta[24]),
    .Z(_139_)
  );
  AND2_X1 _360_ (
    .A1(_181_),
    .A2(tx_conta[23]),
    .Z(_138_)
  );
  AND2_X1 _361_ (
    .A1(_181_),
    .A2(tx_conta[22]),
    .Z(_137_)
  );
  AND2_X1 _362_ (
    .A1(_181_),
    .A2(tx_conta[21]),
    .Z(_136_)
  );
  AND2_X1 _363_ (
    .A1(_181_),
    .A2(tx_conta[20]),
    .Z(_135_)
  );
  AND2_X1 _364_ (
    .A1(_181_),
    .A2(tx_conta[19]),
    .Z(_134_)
  );
  AND2_X1 _365_ (
    .A1(_181_),
    .A2(tx_conta[18]),
    .Z(_133_)
  );
  AND2_X1 _366_ (
    .A1(_181_),
    .A2(tx_conta[17]),
    .Z(_132_)
  );
  AND2_X1 _367_ (
    .A1(_181_),
    .A2(tx_conta[16]),
    .Z(_131_)
  );
  AND2_X1 _368_ (
    .A1(_181_),
    .A2(tx_conta[15]),
    .Z(_130_)
  );
  AND2_X1 _369_ (
    .A1(_181_),
    .A2(tx_conta[14]),
    .Z(_129_)
  );
  AND2_X1 _370_ (
    .A1(_181_),
    .A2(tx_conta[13]),
    .Z(_128_)
  );
  AND2_X1 _371_ (
    .A1(_181_),
    .A2(tx_conta[12]),
    .Z(_127_)
  );
  AND2_X1 _372_ (
    .A1(_181_),
    .A2(tx_conta[11]),
    .Z(_126_)
  );
  AND2_X1 _373_ (
    .A1(_181_),
    .A2(tx_conta[10]),
    .Z(_125_)
  );
  AND2_X1 _374_ (
    .A1(_181_),
    .A2(tx_conta[9]),
    .Z(_124_)
  );
  NOR2_X1 _375_ (
    .A1(send_en),
    .A2(_182_),
    .ZN(_123_)
  );
  AND2_X1 _376_ (
    .A1(_181_),
    .A2(tx_conta[7]),
    .Z(_122_)
  );
  NAND2_X1 _377_ (
    .A1(tx_conta[6]),
    .A2(tx_conta[5]),
    .ZN(_229_)
  );
  OR3_X1 _378_ (
    .A1(tx_conta[2]),
    .A2(tx_conta[1]),
    .A3(tx_conta[0]),
    .Z(_230_)
  );
  AOI21_X1 _379_ (
    .A1(tx_conta[3]),
    .A2(_230_),
    .B(tx_conta[4]),
    .ZN(_231_)
  );
  NOR2_X1 _380_ (
    .A1(_229_),
    .A2(_231_),
    .ZN(_232_)
  );
  NOR2_X1 _381_ (
    .A1(tx_conta[9]),
    .A2(tx_conta[7]),
    .ZN(_233_)
  );
  NOR4_X1 _382_ (
    .A1(tx_conta[13]),
    .A2(tx_conta[12]),
    .A3(tx_conta[11]),
    .A4(tx_conta[10]),
    .ZN(_234_)
  );
  NOR4_X1 _383_ (
    .A1(tx_conta[17]),
    .A2(tx_conta[16]),
    .A3(tx_conta[15]),
    .A4(tx_conta[14]),
    .ZN(_235_)
  );
  NAND4_X1 _384_ (
    .A1(_182_),
    .A2(_233_),
    .A3(_234_),
    .A4(_235_),
    .ZN(_236_)
  );
  NOR2_X1 _385_ (
    .A1(tx_conta[31]),
    .A2(tx_conta[30]),
    .ZN(_237_)
  );
  NOR4_X1 _386_ (
    .A1(tx_conta[29]),
    .A2(tx_conta[28]),
    .A3(tx_conta[27]),
    .A4(tx_conta[26]),
    .ZN(_238_)
  );
  NOR4_X1 _387_ (
    .A1(tx_conta[21]),
    .A2(tx_conta[20]),
    .A3(tx_conta[19]),
    .A4(tx_conta[18]),
    .ZN(_239_)
  );
  NOR4_X1 _388_ (
    .A1(tx_conta[25]),
    .A2(tx_conta[24]),
    .A3(tx_conta[23]),
    .A4(tx_conta[22]),
    .ZN(_240_)
  );
  NAND4_X1 _389_ (
    .A1(_237_),
    .A2(_238_),
    .A3(_239_),
    .A4(_240_),
    .ZN(_241_)
  );
  NOR3_X1 _390_ (
    .A1(_232_),
    .A2(_236_),
    .A3(_241_),
    .ZN(_242_)
  );
  NOR2_X1 _391_ (
    .A1(_181_),
    .A2(_242_),
    .ZN(_243_)
  );
  AND2_X1 _392_ (
    .A1(send_en),
    .A2(tx_conta[0]),
    .Z(_244_)
  );
  AND3_X1 _393_ (
    .A1(tx_conta[2]),
    .A2(tx_conta[1]),
    .A3(_244_),
    .Z(_245_)
  );
  AND2_X1 _394_ (
    .A1(tx_conta[3]),
    .A2(_245_),
    .Z(_246_)
  );
  AND2_X1 _395_ (
    .A1(tx_conta[4]),
    .A2(_246_),
    .Z(_247_)
  );
  AOI21_X1 _396_ (
    .A1(tx_conta[5]),
    .A2(_247_),
    .B(tx_conta[6]),
    .ZN(_248_)
  );
  NOR2_X1 _397_ (
    .A1(_243_),
    .A2(_248_),
    .ZN(_121_)
  );
  XNOR2_X1 _398_ (
    .A1(tx_conta[5]),
    .A2(_247_),
    .ZN(_249_)
  );
  NOR2_X1 _399_ (
    .A1(_243_),
    .A2(_249_),
    .ZN(_120_)
  );
  NOR2_X1 _400_ (
    .A1(tx_conta[4]),
    .A2(_246_),
    .ZN(_250_)
  );
  NOR3_X1 _401_ (
    .A1(_243_),
    .A2(_247_),
    .A3(_250_),
    .ZN(_119_)
  );
  NOR2_X1 _402_ (
    .A1(tx_conta[3]),
    .A2(_245_),
    .ZN(_251_)
  );
  NOR3_X1 _403_ (
    .A1(_243_),
    .A2(_246_),
    .A3(_251_),
    .ZN(_118_)
  );
  AOI21_X1 _404_ (
    .A1(tx_conta[1]),
    .A2(_244_),
    .B(tx_conta[2]),
    .ZN(_252_)
  );
  NOR3_X1 _405_ (
    .A1(_243_),
    .A2(_245_),
    .A3(_252_),
    .ZN(_117_)
  );
  XNOR2_X1 _406_ (
    .A1(tx_conta[1]),
    .A2(_244_),
    .ZN(_253_)
  );
  NOR2_X1 _407_ (
    .A1(_243_),
    .A2(_253_),
    .ZN(_116_)
  );
  NOR2_X1 _408_ (
    .A1(send_en),
    .A2(tx_conta[0]),
    .ZN(_254_)
  );
  NOR3_X1 _409_ (
    .A1(_243_),
    .A2(_244_),
    .A3(_254_),
    .ZN(_115_)
  );
  AND2_X1 _410_ (
    .A1(next_bit[5]),
    .A2(_243_),
    .Z(_003_)
  );
  MUX2_X1 _411_ (
    .I0(next_bit[7]),
    .I1(next_bit[2]),
    .S(_243_),
    .Z(_022_)
  );
  OAI21_X1 _412_ (
    .A1(_180_),
    .A2(tx_end),
    .B(_186_),
    .ZN(_014_)
  );
  OAI21_X1 _413_ (
    .A1(send_data),
    .A2(_187_),
    .B(_188_),
    .ZN(_010_)
  );
  MUX2_X1 _414_ (
    .I0(next_bit[2]),
    .I1(next_bit[8]),
    .S(_243_),
    .Z(_017_)
  );
  MUX2_X1 _415_ (
    .I0(next_bit[6]),
    .I1(next_bit[1]),
    .S(_243_),
    .Z(_021_)
  );
  NAND2_X1 _416_ (
    .A1(_220_),
    .A2(_223_),
    .ZN(_013_)
  );
  OR2_X1 _417_ (
    .A1(S2[2]),
    .A2(_213_),
    .Z(_011_)
  );
  OAI21_X1 _418_ (
    .A1(rdy),
    .A2(_183_),
    .B(_189_),
    .ZN(_009_)
  );
  MUX2_X1 _419_ (
    .I0(next_bit[5]),
    .I1(next_bit[6]),
    .S(_243_),
    .Z(_020_)
  );
  AOI21_X1 _420_ (
    .A1(S1[5]),
    .A2(eoc),
    .B(S1[2]),
    .ZN(_255_)
  );
  INV_X1 _421_ (
    .I(_255_),
    .ZN(_008_)
  );
  MUX2_X1 _422_ (
    .I0(next_bit[1]),
    .I1(next_bit[9]),
    .S(_243_),
    .Z(_016_)
  );
  MUX2_X1 _423_ (
    .I0(next_bit[4]),
    .I1(next_bit[7]),
    .S(_243_),
    .Z(_019_)
  );
  MUX2_X1 _424_ (
    .I0(next_bit[3]),
    .I1(next_bit[0]),
    .S(_243_),
    .Z(_018_)
  );
  OAI21_X1 _425_ (
    .A1(mpx),
    .A2(_215_),
    .B(_217_),
    .ZN(_012_)
  );
  MUX2_X1 _426_ (
    .I0(next_bit[9]),
    .I1(next_bit[4]),
    .S(_243_),
    .Z(_024_)
  );
  MUX2_X1 _427_ (
    .I0(next_bit[0]),
    .I1(next_bit[5]),
    .S(_243_),
    .Z(_015_)
  );
  MUX2_X1 _428_ (
    .I0(next_bit[8]),
    .I1(next_bit[3]),
    .S(_243_),
    .Z(_023_)
  );
  NOR2_X1 _429_ (
    .A1(next_bit[4]),
    .A2(next_bit[3]),
    .ZN(_256_)
  );
  OR4_X1 _430_ (
    .A1(next_bit[2]),
    .A2(next_bit[8]),
    .A3(next_bit[1]),
    .A4(next_bit[6]),
    .Z(_257_)
  );
  NOR4_X1 _431_ (
    .A1(next_bit[7]),
    .A2(next_bit[9]),
    .A3(next_bit[0]),
    .A4(_257_),
    .ZN(_258_)
  );
  AOI22_X1 _432_ (
    .A1(out_reg[6]),
    .A2(next_bit[8]),
    .B1(next_bit[6]),
    .B2(out_reg[0]),
    .ZN(_259_)
  );
  AOI22_X1 _433_ (
    .A1(out_reg[1]),
    .A2(next_bit[1]),
    .B1(next_bit[9]),
    .B2(out_reg[2]),
    .ZN(_260_)
  );
  AOI22_X1 _434_ (
    .A1(out_reg[4]),
    .A2(next_bit[7]),
    .B1(next_bit[3]),
    .B2(out_reg[7]),
    .ZN(_261_)
  );
  AOI22_X1 _435_ (
    .A1(out_reg[5]),
    .A2(next_bit[2]),
    .B1(next_bit[4]),
    .B2(out_reg[3]),
    .ZN(_262_)
  );
  NAND4_X1 _436_ (
    .A1(_259_),
    .A2(_260_),
    .A3(_261_),
    .A4(_262_),
    .ZN(_263_)
  );
  AOI21_X1 _437_ (
    .A1(_256_),
    .A2(_258_),
    .B(_263_),
    .ZN(_264_)
  );
  NAND2_X1 _438_ (
    .A1(_243_),
    .A2(_264_),
    .ZN(_000_)
  );
  OR3_X1 _439_ (
    .A1(load),
    .A2(tx_end),
    .A3(tre),
    .Z(_002_)
  );
  OAI22_X1 _440_ (
    .A1(_181_),
    .A2(tx_end),
    .B1(_190_),
    .B2(_227_),
    .ZN(_001_)
  );
  INV_X1 _441_ (
    .I(reset),
    .ZN(_026_)
  );
  INV_X1 _442_ (
    .I(reset),
    .ZN(_027_)
  );
  INV_X1 _443_ (
    .I(reset),
    .ZN(_028_)
  );
  INV_X1 _444_ (
    .I(reset),
    .ZN(_029_)
  );
  INV_X1 _445_ (
    .I(reset),
    .ZN(_030_)
  );
  INV_X1 _446_ (
    .I(reset),
    .ZN(_031_)
  );
  INV_X1 _447_ (
    .I(reset),
    .ZN(_032_)
  );
  INV_X1 _448_ (
    .I(reset),
    .ZN(_033_)
  );
  INV_X1 _449_ (
    .I(reset),
    .ZN(_034_)
  );
  INV_X1 _450_ (
    .I(reset),
    .ZN(_035_)
  );
  INV_X1 _451_ (
    .I(reset),
    .ZN(_036_)
  );
  INV_X1 _452_ (
    .I(reset),
    .ZN(_037_)
  );
  INV_X1 _453_ (
    .I(reset),
    .ZN(_038_)
  );
  INV_X1 _454_ (
    .I(reset),
    .ZN(_039_)
  );
  INV_X1 _455_ (
    .I(reset),
    .ZN(_040_)
  );
  INV_X1 _456_ (
    .I(reset),
    .ZN(_041_)
  );
  INV_X1 _457_ (
    .I(reset),
    .ZN(_042_)
  );
  INV_X1 _458_ (
    .I(reset),
    .ZN(_043_)
  );
  INV_X1 _459_ (
    .I(reset),
    .ZN(_044_)
  );
  INV_X1 _460_ (
    .I(reset),
    .ZN(_045_)
  );
  INV_X1 _461_ (
    .I(reset),
    .ZN(_046_)
  );
  INV_X1 _462_ (
    .I(reset),
    .ZN(_047_)
  );
  INV_X1 _463_ (
    .I(reset),
    .ZN(_048_)
  );
  INV_X1 _464_ (
    .I(reset),
    .ZN(_049_)
  );
  INV_X1 _465_ (
    .I(reset),
    .ZN(_050_)
  );
  INV_X1 _466_ (
    .I(reset),
    .ZN(_051_)
  );
  INV_X1 _467_ (
    .I(reset),
    .ZN(_052_)
  );
  INV_X1 _468_ (
    .I(reset),
    .ZN(_053_)
  );
  INV_X1 _469_ (
    .I(reset),
    .ZN(_054_)
  );
  INV_X1 _470_ (
    .I(reset),
    .ZN(_055_)
  );
  INV_X1 _471_ (
    .I(reset),
    .ZN(_056_)
  );
  INV_X1 _472_ (
    .I(reset),
    .ZN(_057_)
  );
  INV_X1 _473_ (
    .I(reset),
    .ZN(_058_)
  );
  INV_X1 _474_ (
    .I(reset),
    .ZN(_059_)
  );
  INV_X1 _475_ (
    .I(reset),
    .ZN(_060_)
  );
  INV_X1 _476_ (
    .I(reset),
    .ZN(_061_)
  );
  INV_X1 _477_ (
    .I(reset),
    .ZN(_062_)
  );
  INV_X1 _478_ (
    .I(reset),
    .ZN(_063_)
  );
  INV_X1 _479_ (
    .I(reset),
    .ZN(_064_)
  );
  INV_X1 _480_ (
    .I(reset),
    .ZN(_065_)
  );
  INV_X1 _481_ (
    .I(reset),
    .ZN(_066_)
  );
  INV_X1 _482_ (
    .I(reset),
    .ZN(_067_)
  );
  INV_X1 _483_ (
    .I(reset),
    .ZN(_068_)
  );
  INV_X1 _484_ (
    .I(reset),
    .ZN(_069_)
  );
  INV_X1 _485_ (
    .I(reset),
    .ZN(_070_)
  );
  INV_X1 _486_ (
    .I(reset),
    .ZN(_071_)
  );
  INV_X1 _487_ (
    .I(reset),
    .ZN(_072_)
  );
  INV_X1 _488_ (
    .I(reset),
    .ZN(_073_)
  );
  INV_X1 _489_ (
    .I(reset),
    .ZN(_074_)
  );
  INV_X1 _490_ (
    .I(reset),
    .ZN(_075_)
  );
  INV_X1 _491_ (
    .I(reset),
    .ZN(_076_)
  );
  INV_X1 _492_ (
    .I(reset),
    .ZN(_077_)
  );
  INV_X1 _493_ (
    .I(reset),
    .ZN(_078_)
  );
  INV_X1 _494_ (
    .I(reset),
    .ZN(_079_)
  );
  INV_X1 _495_ (
    .I(reset),
    .ZN(_080_)
  );
  INV_X1 _496_ (
    .I(reset),
    .ZN(_081_)
  );
  INV_X1 _497_ (
    .I(reset),
    .ZN(_082_)
  );
  INV_X1 _498_ (
    .I(reset),
    .ZN(_083_)
  );
  INV_X1 _499_ (
    .I(reset),
    .ZN(_084_)
  );
  INV_X1 _500_ (
    .I(reset),
    .ZN(_085_)
  );
  INV_X1 _501_ (
    .I(reset),
    .ZN(_086_)
  );
  INV_X1 _502_ (
    .I(reset),
    .ZN(_087_)
  );
  INV_X1 _503_ (
    .I(reset),
    .ZN(_088_)
  );
  INV_X1 _504_ (
    .I(reset),
    .ZN(_089_)
  );
  INV_X1 _505_ (
    .I(reset),
    .ZN(_090_)
  );
  INV_X1 _506_ (
    .I(reset),
    .ZN(_091_)
  );
  INV_X1 _507_ (
    .I(reset),
    .ZN(_092_)
  );
  INV_X1 _508_ (
    .I(reset),
    .ZN(_093_)
  );
  INV_X1 _509_ (
    .I(reset),
    .ZN(_094_)
  );
  INV_X1 _510_ (
    .I(reset),
    .ZN(_095_)
  );
  INV_X1 _511_ (
    .I(reset),
    .ZN(_096_)
  );
  INV_X1 _512_ (
    .I(reset),
    .ZN(_097_)
  );
  INV_X1 _513_ (
    .I(reset),
    .ZN(_098_)
  );
  INV_X1 _514_ (
    .I(reset),
    .ZN(_099_)
  );
  INV_X1 _515_ (
    .I(reset),
    .ZN(_100_)
  );
  INV_X1 _516_ (
    .I(reset),
    .ZN(_101_)
  );
  INV_X1 _517_ (
    .I(reset),
    .ZN(_102_)
  );
  INV_X1 _518_ (
    .I(reset),
    .ZN(_103_)
  );
  INV_X1 _519_ (
    .I(reset),
    .ZN(_104_)
  );
  INV_X1 _520_ (
    .I(reset),
    .ZN(_105_)
  );
  INV_X1 _521_ (
    .I(reset),
    .ZN(_106_)
  );
  INV_X1 _522_ (
    .I(reset),
    .ZN(_107_)
  );
  INV_X1 _523_ (
    .I(reset),
    .ZN(_108_)
  );
  INV_X1 _524_ (
    .I(reset),
    .ZN(_109_)
  );
  INV_X1 _525_ (
    .I(reset),
    .ZN(_110_)
  );
  INV_X1 _526_ (
    .I(reset),
    .ZN(_111_)
  );
  INV_X1 _527_ (
    .I(reset),
    .ZN(_112_)
  );
  INV_X1 _528_ (
    .I(reset),
    .ZN(_113_)
  );
  INV_X1 _529_ (
    .I(reset),
    .ZN(_114_)
  );
  DFFSNQ_X1 _530_ (
    .CLK(clock),
    .D(_015_),
    .Q(next_bit[0]),
    .SN(_025_)
  );
  DFFRNQ_X1 _531_ (
    .CLK(clock),
    .D(_016_),
    .Q(next_bit[1]),
    .RN(_026_)
  );
  DFFRNQ_X1 _532_ (
    .CLK(clock),
    .D(_017_),
    .Q(next_bit[2]),
    .RN(_027_)
  );
  DFFRNQ_X1 _533_ (
    .CLK(clock),
    .D(_018_),
    .Q(next_bit[3]),
    .RN(_028_)
  );
  DFFRNQ_X1 _534_ (
    .CLK(clock),
    .D(_019_),
    .Q(next_bit[4]),
    .RN(_029_)
  );
  DFFRNQ_X1 _535_ (
    .CLK(clock),
    .D(_020_),
    .Q(next_bit[5]),
    .RN(_030_)
  );
  DFFRNQ_X1 _536_ (
    .CLK(clock),
    .D(_021_),
    .Q(next_bit[6]),
    .RN(_031_)
  );
  DFFRNQ_X1 _537_ (
    .CLK(clock),
    .D(_022_),
    .Q(next_bit[7]),
    .RN(_032_)
  );
  DFFRNQ_X1 _538_ (
    .CLK(clock),
    .D(_023_),
    .Q(next_bit[8]),
    .RN(_033_)
  );
  DFFRNQ_X1 _539_ (
    .CLK(clock),
    .D(_024_),
    .Q(next_bit[9]),
    .RN(_034_)
  );
  DFFSNQ_X1 _540_ (
    .CLK(clock),
    .D(_010_),
    .Q(S2[0]),
    .SN(_035_)
  );
  DFFRNQ_X1 _541_ (
    .CLK(clock),
    .D(_011_),
    .Q(S2[1]),
    .RN(_036_)
  );
  DFFRNQ_X1 _542_ (
    .CLK(clock),
    .D(_012_),
    .Q(S2[2]),
    .RN(_037_)
  );
  DFFRNQ_X1 _543_ (
    .CLK(clock),
    .D(_006_),
    .Q(S2[3]),
    .RN(_038_)
  );
  DFFSNQ_X1 _544_ (
    .CLK(clock),
    .D(_004_),
    .Q(S1[0]),
    .SN(_039_)
  );
  DFFRNQ_X1 _545_ (
    .CLK(clock),
    .D(S1[7]),
    .Q(S1[1]),
    .RN(_040_)
  );
  DFFRNQ_X1 _546_ (
    .CLK(clock),
    .D(S1[4]),
    .Q(S1[2]),
    .RN(_041_)
  );
  DFFRNQ_X1 _547_ (
    .CLK(clock),
    .D(_005_),
    .Q(S1[3]),
    .RN(_042_)
  );
  DFFRNQ_X1 _548_ (
    .CLK(clock),
    .D(S1[0]),
    .Q(S1[4]),
    .RN(_043_)
  );
  DFFRNQ_X1 _549_ (
    .CLK(clock),
    .D(_008_),
    .Q(S1[5]),
    .RN(_044_)
  );
  DFFRNQ_X1 _550_ (
    .CLK(clock),
    .D(_009_),
    .Q(S1[6]),
    .RN(_045_)
  );
  DFFRNQ_X1 _551_ (
    .CLK(clock),
    .D(S1[3]),
    .Q(S1[7]),
    .RN(_046_)
  );
  DFFSNQ_X1 _552_ (
    .CLK(clock),
    .D(_013_),
    .Q(itfc_state[0]),
    .SN(_047_)
  );
  DFFRNQ_X1 _553_ (
    .CLK(clock),
    .D(itfc_state[2]),
    .Q(itfc_state[1]),
    .RN(_048_)
  );
  DFFRNQ_X1 _554_ (
    .CLK(clock),
    .D(_007_),
    .Q(itfc_state[2]),
    .RN(_049_)
  );
  DFFRNQ_X1 _555_ (
    .CLK(clock),
    .D(_014_),
    .Q(itfc_state[3]),
    .RN(_050_)
  );
  (* src = "b13.v:255.1-316.4" *)
  DFFRNQ_X1 _556_ (
    .CLK(clock),
    .D(_000_),
    .Q(data_out),
    .RN(_051_)
  );
  (* src = "b13.v:255.1-316.4" *)
  DFFRNQ_X1 _557_ (
    .CLK(clock),
    .D(_003_),
    .Q(tx_end),
    .RN(_052_)
  );
  (* src = "b13.v:255.1-316.4" *)
  DFFRNQ_X1 _558_ (
    .CLK(clock),
    .D(_115_),
    .Q(tx_conta[0]),
    .RN(_053_)
  );
  (* src = "b13.v:255.1-316.4" *)
  DFFRNQ_X1 _559_ (
    .CLK(clock),
    .D(_116_),
    .Q(tx_conta[1]),
    .RN(_054_)
  );
  (* src = "b13.v:255.1-316.4" *)
  DFFRNQ_X1 _560_ (
    .CLK(clock),
    .D(_117_),
    .Q(tx_conta[2]),
    .RN(_055_)
  );
  (* src = "b13.v:255.1-316.4" *)
  DFFRNQ_X1 _561_ (
    .CLK(clock),
    .D(_118_),
    .Q(tx_conta[3]),
    .RN(_056_)
  );
  (* src = "b13.v:255.1-316.4" *)
  DFFRNQ_X1 _562_ (
    .CLK(clock),
    .D(_119_),
    .Q(tx_conta[4]),
    .RN(_057_)
  );
  (* src = "b13.v:255.1-316.4" *)
  DFFRNQ_X1 _563_ (
    .CLK(clock),
    .D(_120_),
    .Q(tx_conta[5]),
    .RN(_058_)
  );
  (* src = "b13.v:255.1-316.4" *)
  DFFRNQ_X1 _564_ (
    .CLK(clock),
    .D(_121_),
    .Q(tx_conta[6]),
    .RN(_059_)
  );
  (* src = "b13.v:255.1-316.4" *)
  DFFRNQ_X1 _565_ (
    .CLK(clock),
    .D(_122_),
    .Q(tx_conta[7]),
    .RN(_060_)
  );
  (* src = "b13.v:255.1-316.4" *)
  DFFRNQ_X1 _566_ (
    .CLK(clock),
    .D(_123_),
    .Q(tx_conta[8]),
    .RN(_061_)
  );
  (* src = "b13.v:255.1-316.4" *)
  DFFRNQ_X1 _567_ (
    .CLK(clock),
    .D(_124_),
    .Q(tx_conta[9]),
    .RN(_062_)
  );
  (* src = "b13.v:255.1-316.4" *)
  DFFRNQ_X1 _568_ (
    .CLK(clock),
    .D(_125_),
    .Q(tx_conta[10]),
    .RN(_063_)
  );
  (* src = "b13.v:255.1-316.4" *)
  DFFRNQ_X1 _569_ (
    .CLK(clock),
    .D(_126_),
    .Q(tx_conta[11]),
    .RN(_064_)
  );
  (* src = "b13.v:255.1-316.4" *)
  DFFRNQ_X1 _570_ (
    .CLK(clock),
    .D(_127_),
    .Q(tx_conta[12]),
    .RN(_065_)
  );
  (* src = "b13.v:255.1-316.4" *)
  DFFRNQ_X1 _571_ (
    .CLK(clock),
    .D(_128_),
    .Q(tx_conta[13]),
    .RN(_066_)
  );
  (* src = "b13.v:255.1-316.4" *)
  DFFRNQ_X1 _572_ (
    .CLK(clock),
    .D(_129_),
    .Q(tx_conta[14]),
    .RN(_067_)
  );
  (* src = "b13.v:255.1-316.4" *)
  DFFRNQ_X1 _573_ (
    .CLK(clock),
    .D(_130_),
    .Q(tx_conta[15]),
    .RN(_068_)
  );
  (* src = "b13.v:255.1-316.4" *)
  DFFRNQ_X1 _574_ (
    .CLK(clock),
    .D(_131_),
    .Q(tx_conta[16]),
    .RN(_069_)
  );
  (* src = "b13.v:255.1-316.4" *)
  DFFRNQ_X1 _575_ (
    .CLK(clock),
    .D(_132_),
    .Q(tx_conta[17]),
    .RN(_070_)
  );
  (* src = "b13.v:255.1-316.4" *)
  DFFRNQ_X1 _576_ (
    .CLK(clock),
    .D(_133_),
    .Q(tx_conta[18]),
    .RN(_071_)
  );
  (* src = "b13.v:255.1-316.4" *)
  DFFRNQ_X1 _577_ (
    .CLK(clock),
    .D(_134_),
    .Q(tx_conta[19]),
    .RN(_072_)
  );
  (* src = "b13.v:255.1-316.4" *)
  DFFRNQ_X1 _578_ (
    .CLK(clock),
    .D(_135_),
    .Q(tx_conta[20]),
    .RN(_073_)
  );
  (* src = "b13.v:255.1-316.4" *)
  DFFRNQ_X1 _579_ (
    .CLK(clock),
    .D(_136_),
    .Q(tx_conta[21]),
    .RN(_074_)
  );
  (* src = "b13.v:255.1-316.4" *)
  DFFRNQ_X1 _580_ (
    .CLK(clock),
    .D(_137_),
    .Q(tx_conta[22]),
    .RN(_075_)
  );
  (* src = "b13.v:255.1-316.4" *)
  DFFRNQ_X1 _581_ (
    .CLK(clock),
    .D(_138_),
    .Q(tx_conta[23]),
    .RN(_076_)
  );
  (* src = "b13.v:255.1-316.4" *)
  DFFRNQ_X1 _582_ (
    .CLK(clock),
    .D(_139_),
    .Q(tx_conta[24]),
    .RN(_077_)
  );
  (* src = "b13.v:255.1-316.4" *)
  DFFRNQ_X1 _583_ (
    .CLK(clock),
    .D(_140_),
    .Q(tx_conta[25]),
    .RN(_078_)
  );
  (* src = "b13.v:255.1-316.4" *)
  DFFRNQ_X1 _584_ (
    .CLK(clock),
    .D(_141_),
    .Q(tx_conta[26]),
    .RN(_079_)
  );
  (* src = "b13.v:255.1-316.4" *)
  DFFRNQ_X1 _585_ (
    .CLK(clock),
    .D(_142_),
    .Q(tx_conta[27]),
    .RN(_080_)
  );
  (* src = "b13.v:255.1-316.4" *)
  DFFRNQ_X1 _586_ (
    .CLK(clock),
    .D(_143_),
    .Q(tx_conta[28]),
    .RN(_081_)
  );
  (* src = "b13.v:255.1-316.4" *)
  DFFRNQ_X1 _587_ (
    .CLK(clock),
    .D(_144_),
    .Q(tx_conta[29]),
    .RN(_082_)
  );
  (* src = "b13.v:255.1-316.4" *)
  DFFRNQ_X1 _588_ (
    .CLK(clock),
    .D(_145_),
    .Q(tx_conta[30]),
    .RN(_083_)
  );
  (* src = "b13.v:255.1-316.4" *)
  DFFRNQ_X1 _589_ (
    .CLK(clock),
    .D(_146_),
    .Q(tx_conta[31]),
    .RN(_084_)
  );
  (* src = "b13.v:222.1-253.4" *)
  DFFRNQ_X1 _590_ (
    .CLK(clock),
    .D(_001_),
    .Q(send_en),
    .RN(_085_)
  );
  (* src = "b13.v:222.1-253.4" *)
  DFFRNQ_X1 _591_ (
    .CLK(clock),
    .D(_002_),
    .Q(tre),
    .RN(_086_)
  );
  (* src = "b13.v:222.1-253.4" *)
  DFFRNQ_X1 _592_ (
    .CLK(clock),
    .D(_147_),
    .Q(errorr),
    .RN(_087_)
  );
  (* src = "b13.v:222.1-253.4" *)
  DFFRNQ_X1 _593_ (
    .CLK(clock),
    .D(_148_),
    .Q(out_reg[0]),
    .RN(_088_)
  );
  (* src = "b13.v:222.1-253.4" *)
  DFFRNQ_X1 _594_ (
    .CLK(clock),
    .D(_149_),
    .Q(out_reg[1]),
    .RN(_089_)
  );
  (* src = "b13.v:222.1-253.4" *)
  DFFRNQ_X1 _595_ (
    .CLK(clock),
    .D(_150_),
    .Q(out_reg[2]),
    .RN(_090_)
  );
  (* src = "b13.v:222.1-253.4" *)
  DFFRNQ_X1 _596_ (
    .CLK(clock),
    .D(_151_),
    .Q(out_reg[3]),
    .RN(_091_)
  );
  (* src = "b13.v:222.1-253.4" *)
  DFFRNQ_X1 _597_ (
    .CLK(clock),
    .D(_152_),
    .Q(out_reg[4]),
    .RN(_092_)
  );
  (* src = "b13.v:222.1-253.4" *)
  DFFRNQ_X1 _598_ (
    .CLK(clock),
    .D(_153_),
    .Q(out_reg[5]),
    .RN(_093_)
  );
  (* src = "b13.v:222.1-253.4" *)
  DFFRNQ_X1 _599_ (
    .CLK(clock),
    .D(_154_),
    .Q(out_reg[6]),
    .RN(_094_)
  );
  (* src = "b13.v:222.1-253.4" *)
  DFFRNQ_X1 _600_ (
    .CLK(clock),
    .D(_155_),
    .Q(out_reg[7]),
    .RN(_095_)
  );
  (* src = "b13.v:182.1-220.4" *)
  DFFRNQ_X1 _601_ (
    .CLK(clock),
    .D(_156_),
    .Q(confirm),
    .RN(_096_)
  );
  (* src = "b13.v:182.1-220.4" *)
  DFFRNQ_X1 _602_ (
    .CLK(clock),
    .D(_157_),
    .Q(send),
    .RN(_097_)
  );
  (* src = "b13.v:182.1-220.4" *)
  DFFRNQ_X1 _603_ (
    .CLK(clock),
    .D(_158_),
    .Q(load),
    .RN(_098_)
  );
  (* src = "b13.v:133.1-180.4" *)
  DFFRNQ_X1 _604_ (
    .CLK(clock),
    .D(_159_),
    .Q(add_mpx2),
    .RN(_099_)
  );
  (* src = "b13.v:133.1-180.4" *)
  DFFRNQ_X1 _605_ (
    .CLK(clock),
    .D(_160_),
    .Q(mpx),
    .RN(_100_)
  );
  (* src = "b13.v:133.1-180.4" *)
  DFFRNQ_X1 _606_ (
    .CLK(clock),
    .D(_161_),
    .Q(rdy),
    .RN(_101_)
  );
  (* src = "b13.v:133.1-180.4" *)
  DFFRNQ_X1 _607_ (
    .CLK(clock),
    .D(_162_),
    .Q(shot),
    .RN(_102_)
  );
  (* src = "b13.v:67.1-131.4" *)
  DFFRNQ_X1 _608_ (
    .CLK(clock),
    .D(_163_),
    .Q(soc),
    .RN(_103_)
  );
  (* src = "b13.v:67.1-131.4" *)
  DFFRNQ_X1 _609_ (
    .CLK(clock),
    .D(_164_),
    .Q(load_dato),
    .RN(_104_)
  );
  (* src = "b13.v:67.1-131.4" *)
  DFFRNQ_X1 _610_ (
    .CLK(clock),
    .D(_165_),
    .Q(mux_en),
    .RN(_105_)
  );
  (* src = "b13.v:67.1-131.4" *)
  DFFRNQ_X1 _611_ (
    .CLK(clock),
    .D(_166_),
    .Q(canale[0]),
    .RN(_106_)
  );
  (* src = "b13.v:67.1-131.4" *)
  DFFRNQ_X1 _612_ (
    .CLK(clock),
    .D(_167_),
    .Q(canale[1]),
    .RN(_107_)
  );
  (* src = "b13.v:67.1-131.4" *)
  DFFRNQ_X1 _613_ (
    .CLK(clock),
    .D(_168_),
    .Q(canale[2]),
    .RN(_108_)
  );
  (* src = "b13.v:67.1-131.4" *)
  DFFRNQ_X1 _614_ (
    .CLK(clock),
    .D(_169_),
    .Q(send_data),
    .RN(_109_)
  );
  (* src = "b13.v:67.1-131.4" *)
  DFFRNQ_X1 _615_ (
    .CLK(clock),
    .D(_170_),
    .Q(conta_tmp[3]),
    .RN(_110_)
  );
  (* src = "b13.v:67.1-131.4" *)
  DFFRNQ_X1 _616_ (
    .CLK(clock),
    .D(_171_),
    .Q(conta_tmp[4]),
    .RN(_111_)
  );
  (* src = "b13.v:67.1-131.4" *)
  DFFRNQ_X1 _617_ (
    .CLK(clock),
    .D(_172_),
    .Q(conta_tmp[5]),
    .RN(_112_)
  );
  (* src = "b13.v:67.1-131.4" *)
  DFFRNQ_X1 _618_ (
    .CLK(clock),
    .D(_173_),
    .Q(conta_tmp[6]),
    .RN(_113_)
  );
  (* src = "b13.v:67.1-131.4" *)
  DFFRNQ_X1 _619_ (
    .CLK(clock),
    .D(_174_),
    .Q(conta_tmp[7]),
    .RN(_114_)
  );
  assign canale[3] = conta_tmp[3];
  assign conta_tmp[2:0] = canale[2:0];
endmodule
