/*
    Automatically generated by Fault
    Do not modify.
    Generated on: 2025-12-20 15:48:20
*/
/* FAULT METADATA: '{"sin":"sin","boundaryCount":2,"sout":"sout","internalCount":0,"order":[{"width":1,"ordinal":0,"kind":"input","name":"D"},{"width":1,"ordinal":0,"kind":"output","name":"Q"}],"shift":"shift"}' END FAULT METADATA */
/* Generated by Yosys 0.58+35 (git sha1 9a12d9255, clang++ 18.1.3 -fPIC -O3) */

module registersQueue(clk, rst, D, Q, sin, shift, sout, tck, test);
  input clk;
  wire clk;
  input rst;
  wire rst;
  input D;
  wire D;
  output Q;
  wire Q;
  input sin;
  wire sin;
  input shift;
  wire shift;
  output sout;
  wire sout;
  input tck;
  wire tck;
  input test;
  wire test;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire D__dout;
  wire \__BoundaryScanRegister_input__0__.sout ;
  wire \__uuf__.Q1 ;
  wire \__uuf__._0_ ;
  wire \__uuf__._1_ ;
  INV_X1 _04_ (
    .I(rst),
    .ZN(_00_)
  );
  MUX2_X1 _05_ (
    .I0(D),
    .I1(\__BoundaryScanRegister_input__0__.sout ),
    .S(test),
    .Z(D__dout)
  );
  MUX2_X1 _06_ (
    .I0(D__dout),
    .I1(sin),
    .S(shift),
    .Z(_02_)
  );
  MUX2_X1 _07_ (
    .I0(Q),
    .I1(\__BoundaryScanRegister_input__0__.sout ),
    .S(shift),
    .Z(_03_)
  );
  INV_X1 _08_ (
    .I(rst),
    .ZN(_01_)
  );
  DFFRNQ_X1 _09_ (
    .CLK(tck),
    .D(_02_),
    .Q(\__BoundaryScanRegister_input__0__.sout ),
    .RN(_00_)
  );
  DFFRNQ_X1 _10_ (
    .CLK(tck),
    .D(_03_),
    .Q(sout),
    .RN(_01_)
  );
  INV_X1 \__uuf__._2_  (
    .I(rst),
    .ZN(\__uuf__._0_ )
  );
  INV_X1 \__uuf__._3_  (
    .I(rst),
    .ZN(\__uuf__._1_ )
  );
  DFFRNQ_X1 \__uuf__._4_  (
    .CLK(clk),
    .D(D__dout),
    .Q(\__uuf__.Q1 ),
    .RN(\__uuf__._0_ )
  );
  DFFRNQ_X1 \__uuf__._5_  (
    .CLK(clk),
    .D(\__uuf__.Q1 ),
    .Q(Q),
    .RN(\__uuf__._1_ )
  );
endmodule

