/*
    Automatically generated by Fault
    Do not modify.
    Generated on: 2026-02-26 19:25:39
*/
/* FAULT METADATA: '{"order":[{"ordinal":0,"width":1,"kind":"input","name":"D"},{"ordinal":0,"width":1,"kind":"dff","name":"_2_"},{"ordinal":0,"width":1,"kind":"output","name":"Q"}],"sin":"sin","shift":"shift","boundaryCount":2,"internalCount":1,"sout":"sout"}' END FAULT METADATA */
/* Generated by Yosys 0.58+35 (git sha1 9a12d9255, clang++ 18.1.3 -fPIC -O3) */

module register(clk, rst, D, Q, sin, shift, sout, tck, test);
  input clk;
  wire clk;
  input rst;
  wire rst;
  input D;
  wire D;
  output Q;
  wire Q;
  input sin;
  wire sin;
  input shift;
  wire shift;
  output sout;
  wire sout;
  input tck;
  wire tck;
  input test;
  wire test;
  wire _0_;
  wire _1_;
  wire _2_;
  wire \__BoundaryScanRegister_input__0__.sout ;
  wire \__uuf__._0_ ;
  wire \__uuf__.__clk_source__ ;
  MUX2_X1 _3_ (
    .I0(D),
    .I1(\__BoundaryScanRegister_input__0__.sout ),
    .S(test),
    .Z(_2_)
  );
  MUX2_X1 _4_ (
    .I0(_2_),
    .I1(sin),
    .S(shift),
    .Z(_0_)
  );
  MUX2_X1 _5_ (
    .I0(clk),
    .I1(tck),
    .S(test),
    .Z(\__uuf__.__clk_source__ )
  );
  MUX2_X1 _6_ (
    .I0(_2_),
    .I1(\__BoundaryScanRegister_input__0__.sout ),
    .S(shift),
    .Z(_1_)
  );
  DFFRNQ_X1 _7_ (
    .CLK(tck),
    .D(_0_),
    .Q(\__BoundaryScanRegister_input__0__.sout ),
    .RN(rst)
  );
  DFFRNQ_X1 _8_ (
    .CLK(tck),
    .D(Q),
    .Q(sout),
    .RN(rst)
  );
  INV_X1 \__uuf__._1_  (
    .I(rst),
    .ZN(\__uuf__._0_ )
  );
  DFFRNQ_X1 \__uuf__._2_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_1_),
    .Q(Q),
    .RN(\__uuf__._0_ )
  );
endmodule

