/* Generated by Yosys 0.58+35 (git sha1 9a12d9255, clang++ 18.1.3 -fPIC -O3) */

(* top =  1  *)
(* src = "/home/filippo/Desktop/ode4ec/proveSintesi/ITC99/b02/b02.v:1.1-74.10" *)
module b02(reset, clock, linea, u);
  (* src = "/home/filippo/Desktop/ode4ec/proveSintesi/ITC99/b02/b02.v:4.7-4.12" *)
  input reset;
  wire reset;
  (* src = "/home/filippo/Desktop/ode4ec/proveSintesi/ITC99/b02/b02.v:3.7-3.12" *)
  input clock;
  wire clock;
  (* src = "/home/filippo/Desktop/ode4ec/proveSintesi/ITC99/b02/b02.v:5.7-5.12" *)
  input linea;
  wire linea;
  (* src = "/home/filippo/Desktop/ode4ec/proveSintesi/ITC99/b02/b02.v:6.12-6.13" *)
  output u;
  wire u;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire \stato[0] ;
  wire \stato[1] ;
  wire \stato[2] ;
  wire \stato[3] ;
  wire \stato[4] ;
  wire \stato[5] ;
  wire \stato[6] ;
  INV_X1 _23_ (
    .I(\stato[2] ),
    .ZN(_16_)
  );
  INV_X1 _24_ (
    .I(\stato[4] ),
    .ZN(_17_)
  );
  INV_X1 _25_ (
    .I(\stato[3] ),
    .ZN(_18_)
  );
  INV_X1 _26_ (
    .I(\stato[6] ),
    .ZN(_19_)
  );
  INV_X1 _27_ (
    .I(reset),
    .ZN(_07_)
  );
  NOR2_X1 _28_ (
    .A1(u),
    .A2(\stato[1] ),
    .ZN(_20_)
  );
  OR4_X1 _29_ (
    .A1(\stato[3] ),
    .A2(\stato[0] ),
    .A3(\stato[5] ),
    .A4(\stato[6] ),
    .Z(_21_)
  );
  NOR4_X1 _30_ (
    .A1(\stato[2] ),
    .A2(\stato[4] ),
    .A3(_20_),
    .A4(_21_),
    .ZN(_15_)
  );
  NOR2_X1 _31_ (
    .A1(_16_),
    .A2(linea),
    .ZN(_03_)
  );
  NOR2_X1 _32_ (
    .A1(linea),
    .A2(_17_),
    .ZN(_01_)
  );
  AND2_X1 _33_ (
    .A1(linea),
    .A2(\stato[3] ),
    .Z(_00_)
  );
  AND2_X1 _34_ (
    .A1(linea),
    .A2(\stato[4] ),
    .Z(_02_)
  );
  OR2_X1 _35_ (
    .A1(\stato[1] ),
    .A2(\stato[0] ),
    .Z(_06_)
  );
  AOI21_X1 _36_ (
    .A1(\stato[2] ),
    .A2(linea),
    .B(\stato[5] ),
    .ZN(_22_)
  );
  INV_X1 _37_ (
    .I(_22_),
    .ZN(_05_)
  );
  OAI21_X1 _38_ (
    .A1(linea),
    .A2(_18_),
    .B(_19_),
    .ZN(_04_)
  );
  INV_X1 _39_ (
    .I(reset),
    .ZN(_08_)
  );
  INV_X1 _40_ (
    .I(reset),
    .ZN(_09_)
  );
  INV_X1 _41_ (
    .I(reset),
    .ZN(_10_)
  );
  INV_X1 _42_ (
    .I(reset),
    .ZN(_11_)
  );
  INV_X1 _43_ (
    .I(reset),
    .ZN(_12_)
  );
  INV_X1 _44_ (
    .I(reset),
    .ZN(_13_)
  );
  INV_X1 _45_ (
    .I(reset),
    .ZN(_14_)
  );
  (* src = "/home/filippo/Desktop/ode4ec/proveSintesi/ITC99/b02/b02.v:18.1-71.4" *)
  DFFRNQ_X1 _46_ (
    .CLK(clock),
    .D(_15_),
    .Q(u),
    .RN(_07_)
  );
  DFFSNQ_X1 _47_ (
    .CLK(clock),
    .D(_00_),
    .Q(\stato[0] ),
    .SN(_08_)
  );
  DFFRNQ_X1 _48_ (
    .CLK(clock),
    .D(_04_),
    .Q(\stato[1] ),
    .RN(_09_)
  );
  DFFRNQ_X1 _49_ (
    .CLK(clock),
    .D(_01_),
    .Q(\stato[2] ),
    .RN(_10_)
  );
  DFFRNQ_X1 _50_ (
    .CLK(clock),
    .D(_05_),
    .Q(\stato[3] ),
    .RN(_11_)
  );
  DFFRNQ_X1 _51_ (
    .CLK(clock),
    .D(_06_),
    .Q(\stato[4] ),
    .RN(_12_)
  );
  DFFRNQ_X1 _52_ (
    .CLK(clock),
    .D(_02_),
    .Q(\stato[5] ),
    .RN(_13_)
  );
  DFFRNQ_X1 _53_ (
    .CLK(clock),
    .D(_03_),
    .Q(\stato[6] ),
    .RN(_14_)
  );
endmodule
