/*
    Automatically generated by Fault
    Do not modify.
    Generated on: 2026-03-05 14:52:27
*/
/* FAULT METADATA: '{"sin":"sin","internalCount":3,"sout":"sout","boundaryCount":5,"shift":"shift","order":[{"width":1,"ordinal":0,"name":"G0","kind":"input"},{"width":1,"ordinal":0,"name":"G1","kind":"input"},{"width":1,"ordinal":0,"name":"G2","kind":"input"},{"width":1,"ordinal":0,"name":"G3","kind":"input"},{"width":1,"ordinal":0,"name":"_14_","kind":"dff"},{"width":1,"ordinal":0,"name":"_15_","kind":"dff"},{"width":1,"ordinal":0,"name":"_16_","kind":"dff"},{"width":1,"ordinal":0,"name":"G17","kind":"output"}]}' END FAULT METADATA */
/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module s27_scan(CK, rst, G0, G1, G17, G2, G3, sin, shift, sout, tck, test);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  input CK;
  wire CK;
  input G0;
  wire G0;
  input G1;
  wire G1;
  output G17;
  wire G17;
  input G2;
  wire G2;
  input G3;
  wire G3;
  wire \__BoundaryScanRegister_input__0__.dout ;
  wire \__BoundaryScanRegister_input__0__.sout ;
  wire \__BoundaryScanRegister_input__1__.dout ;
  wire \__BoundaryScanRegister_input__1__.sout ;
  wire \__BoundaryScanRegister_input__2__.dout ;
  wire \__BoundaryScanRegister_input__2__.sout ;
  wire \__BoundaryScanRegister_input__3__.dout ;
  wire \__BoundaryScanRegister_input__3__.sout ;
  wire \__BoundaryScanRegister_output__4__.sin ;
  wire \__uuf__.DFF_0.D ;
  wire \__uuf__.DFF_0.Q ;
  wire \__uuf__.DFF_1.D ;
  wire \__uuf__.DFF_1.Q ;
  wire \__uuf__.DFF_2.D ;
  wire \__uuf__._00_ ;
  wire \__uuf__._01_ ;
  wire \__uuf__._02_ ;
  wire \__uuf__._03_ ;
  wire \__uuf__._04_ ;
  wire \__uuf__.__clk_source__ ;
  input rst;
  wire rst;
  input shift;
  wire shift;
  input sin;
  wire sin;
  output sout;
  wire sout;
  input tck;
  wire tck;
  input test;
  wire test;
  INV_X1 _13_ (
    .I(rst),
    .ZN(_00_)
  );
  MUX2_X1 _14_ (
    .I0(G1),
    .I1(\__BoundaryScanRegister_input__1__.sout ),
    .S(test),
    .Z(\__BoundaryScanRegister_input__1__.dout )
  );
  MUX2_X1 _15_ (
    .I0(\__BoundaryScanRegister_input__1__.dout ),
    .I1(\__BoundaryScanRegister_input__0__.sout ),
    .S(shift),
    .Z(_06_)
  );
  MUX2_X1 _16_ (
    .I0(G2),
    .I1(\__BoundaryScanRegister_input__2__.sout ),
    .S(test),
    .Z(\__BoundaryScanRegister_input__2__.dout )
  );
  MUX2_X1 _17_ (
    .I0(\__BoundaryScanRegister_input__2__.dout ),
    .I1(\__BoundaryScanRegister_input__1__.sout ),
    .S(shift),
    .Z(_07_)
  );
  MUX2_X1 _18_ (
    .I0(G3),
    .I1(\__BoundaryScanRegister_input__3__.sout ),
    .S(test),
    .Z(\__BoundaryScanRegister_input__3__.dout )
  );
  MUX2_X1 _19_ (
    .I0(\__BoundaryScanRegister_input__3__.dout ),
    .I1(\__BoundaryScanRegister_input__2__.sout ),
    .S(shift),
    .Z(_08_)
  );
  MUX2_X1 _20_ (
    .I0(G17),
    .I1(\__BoundaryScanRegister_output__4__.sin ),
    .S(shift),
    .Z(_09_)
  );
  MUX2_X1 _21_ (
    .I0(CK),
    .I1(tck),
    .S(test),
    .Z(\__uuf__.__clk_source__ )
  );
  MUX2_X1 _22_ (
    .I0(\__uuf__.DFF_2.D ),
    .I1(\__uuf__.DFF_1.Q ),
    .S(shift),
    .Z(_12_)
  );
  MUX2_X1 _23_ (
    .I0(\__uuf__.DFF_1.D ),
    .I1(\__uuf__.DFF_0.Q ),
    .S(shift),
    .Z(_11_)
  );
  MUX2_X1 _24_ (
    .I0(\__uuf__.DFF_0.D ),
    .I1(\__BoundaryScanRegister_input__3__.sout ),
    .S(shift),
    .Z(_10_)
  );
  MUX2_X1 _25_ (
    .I0(G0),
    .I1(\__BoundaryScanRegister_input__0__.sout ),
    .S(test),
    .Z(\__BoundaryScanRegister_input__0__.dout )
  );
  MUX2_X1 _26_ (
    .I0(\__BoundaryScanRegister_input__0__.dout ),
    .I1(sin),
    .S(shift),
    .Z(_05_)
  );
  INV_X1 _27_ (
    .I(rst),
    .ZN(_01_)
  );
  INV_X1 _28_ (
    .I(rst),
    .ZN(_02_)
  );
  INV_X1 _29_ (
    .I(rst),
    .ZN(_03_)
  );
  INV_X1 _30_ (
    .I(rst),
    .ZN(_04_)
  );
  DFFRNQ_X1 _31_ (
    .CLK(tck),
    .D(_05_),
    .Q(\__BoundaryScanRegister_input__0__.sout ),
    .RN(_00_)
  );
  DFFRNQ_X1 _32_ (
    .CLK(tck),
    .D(_06_),
    .Q(\__BoundaryScanRegister_input__1__.sout ),
    .RN(_01_)
  );
  DFFRNQ_X1 _33_ (
    .CLK(tck),
    .D(_07_),
    .Q(\__BoundaryScanRegister_input__2__.sout ),
    .RN(_02_)
  );
  DFFRNQ_X1 _34_ (
    .CLK(tck),
    .D(_08_),
    .Q(\__BoundaryScanRegister_input__3__.sout ),
    .RN(_03_)
  );
  DFFRNQ_X1 _35_ (
    .CLK(tck),
    .D(_09_),
    .Q(sout),
    .RN(_04_)
  );
  INV_X1 \__uuf__._05_  (
    .I(\__uuf__.DFF_0.Q ),
    .ZN(\__uuf__._00_ )
  );
  INV_X1 \__uuf__._06_  (
    .I(\__BoundaryScanRegister_input__0__.dout ),
    .ZN(\__uuf__._01_ )
  );
  NOR2_X1 \__uuf__._07_  (
    .A1(\__BoundaryScanRegister_output__4__.sin ),
    .A2(\__BoundaryScanRegister_input__1__.dout ),
    .ZN(\__uuf__._02_ )
  );
  AND2_X1 \__uuf__._08_  (
    .A1(\__BoundaryScanRegister_input__3__.dout ),
    .A2(\__uuf__._02_ ),
    .Z(\__uuf__._03_ )
  );
  AOI22_X1 \__uuf__._09_  (
    .A1(\__uuf__._01_ ),
    .A2(\__uuf__.DFF_1.Q ),
    .B1(\__uuf__._02_ ),
    .B2(\__BoundaryScanRegister_input__3__.dout ),
    .ZN(\__uuf__._04_ )
  );
  NOR2_X1 \__uuf__._10_  (
    .A1(\__uuf__.DFF_0.Q ),
    .A2(\__uuf__._04_ ),
    .ZN(\__uuf__.DFF_1.D )
  );
  OR2_X1 \__uuf__._11_  (
    .A1(\__uuf__.DFF_0.Q ),
    .A2(\__uuf__._04_ ),
    .Z(G17)
  );
  AOI21_X1 \__uuf__._12_  (
    .A1(\__uuf__._00_ ),
    .A2(\__uuf__._03_ ),
    .B(\__uuf__._01_ ),
    .ZN(\__uuf__.DFF_0.D )
  );
  NOR2_X1 \__uuf__._13_  (
    .A1(\__BoundaryScanRegister_input__2__.dout ),
    .A2(\__uuf__._02_ ),
    .ZN(\__uuf__.DFF_2.D )
  );
  DFFRNQ_X1 \__uuf__._14_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_10_),
    .Q(\__uuf__.DFF_0.Q ),
    .RN(1'b1)
  );
  DFFRNQ_X1 \__uuf__._15_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_11_),
    .Q(\__uuf__.DFF_1.Q ),
    .RN(1'b1)
  );
  DFFRNQ_X1 \__uuf__._16_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_12_),
    .Q(\__BoundaryScanRegister_output__4__.sin ),
    .RN(1'b1)
  );
endmodule

