/* Generated by Yosys 0.58+35 (git sha1 9a12d9255, clang++ 18.1.3 -fPIC -O3) */

(* top =  1  *)
(* src = "b06.v:1.1-130.10" *)
module b06(cc_mux, eql, uscite, clock, enable_count, ackout, reset, cont_eql);
  (* src = "b06.v:8.18-8.24" *)
  output [2:1] cc_mux;
  wire [2:1] cc_mux;
  (* src = "b06.v:5.7-5.10" *)
  input eql;
  wire eql;
  (* src = "b06.v:9.18-9.24" *)
  output [2:1] uscite;
  wire [2:1] uscite;
  (* src = "b06.v:3.7-3.12" *)
  input clock;
  wire clock;
  (* src = "b06.v:10.12-10.24" *)
  output enable_count;
  wire enable_count;
  (* src = "b06.v:11.12-11.18" *)
  output ackout;
  wire ackout;
  (* src = "b06.v:4.7-4.12" *)
  input reset;
  wire reset;
  (* src = "b06.v:6.7-6.15" *)
  input cont_eql;
  wire cont_eql;
  (* src = "b06.v:27.1-127.4" *)
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  (* force_downto = 32'd1 *)
  (* src = "b06.v:112.7-112.7|b06.v:45.3-125.10|/usr/local/bin/../share/yosys/techmap.v:583.21-583.22" *)
  (* unused_bits = "0" *)
  wire [1:0] _044_;
  (* onehot = 32'd1 *)
  wire [6:0] state;
  INV_X1 _045_ (
    .I(cc_mux[2]),
    .ZN(_022_)
  );
  INV_X1 _046_ (
    .I(cc_mux[1]),
    .ZN(_023_)
  );
  INV_X1 _047_ (
    .I(eql),
    .ZN(_024_)
  );
  INV_X1 _048_ (
    .I(state[0]),
    .ZN(_025_)
  );
  INV_X1 _049_ (
    .I(reset),
    .ZN(_006_)
  );
  OR2_X1 _050_ (
    .A1(state[0]),
    .A2(state[6]),
    .Z(_026_)
  );
  NOR3_X1 _051_ (
    .A1(state[0]),
    .A2(state[6]),
    .A3(state[3]),
    .ZN(_027_)
  );
  NOR4_X1 _052_ (
    .A1(state[5]),
    .A2(state[1]),
    .A3(state[4]),
    .A4(state[2]),
    .ZN(_028_)
  );
  AND2_X1 _053_ (
    .A1(_027_),
    .A2(_028_),
    .Z(_029_)
  );
  NOR2_X1 _054_ (
    .A1(state[1]),
    .A2(state[4]),
    .ZN(_030_)
  );
  NAND2_X1 _055_ (
    .A1(eql),
    .A2(state[3]),
    .ZN(_031_)
  );
  AND2_X1 _056_ (
    .A1(_030_),
    .A2(_031_),
    .Z(_032_)
  );
  OAI21_X1 _057_ (
    .A1(eql),
    .A2(_028_),
    .B(_027_),
    .ZN(_033_)
  );
  AOI22_X1 _058_ (
    .A1(_022_),
    .A2(_029_),
    .B1(_032_),
    .B2(_033_),
    .ZN(_021_)
  );
  OAI22_X1 _059_ (
    .A1(state[1]),
    .A2(state[4]),
    .B1(state[3]),
    .B2(eql),
    .ZN(_034_)
  );
  AOI21_X1 _060_ (
    .A1(_030_),
    .A2(_031_),
    .B(_026_),
    .ZN(_035_)
  );
  AOI22_X1 _061_ (
    .A1(_023_),
    .A2(_029_),
    .B1(_034_),
    .B2(_035_),
    .ZN(_020_)
  );
  NAND2_X1 _062_ (
    .A1(state[1]),
    .A2(_024_),
    .ZN(_036_)
  );
  NAND2_X1 _063_ (
    .A1(_031_),
    .A2(_036_),
    .ZN(_044_[1])
  );
  NAND3_X1 _064_ (
    .A1(uscite[2]),
    .A2(_027_),
    .A3(_028_),
    .ZN(_037_)
  );
  NAND3_X1 _065_ (
    .A1(_031_),
    .A2(_036_),
    .A3(_037_),
    .ZN(_019_)
  );
  AND2_X1 _066_ (
    .A1(uscite[1]),
    .A2(_028_),
    .Z(_038_)
  );
  OR2_X1 _067_ (
    .A1(_033_),
    .A2(_038_),
    .Z(_018_)
  );
  OAI21_X1 _068_ (
    .A1(state[5]),
    .A2(state[1]),
    .B(eql),
    .ZN(_039_)
  );
  INV_X1 _069_ (
    .I(_039_),
    .ZN(_001_)
  );
  AND2_X1 _070_ (
    .A1(_024_),
    .A2(state[4]),
    .Z(_003_)
  );
  OAI21_X1 _071_ (
    .A1(state[4]),
    .A2(state[2]),
    .B(eql),
    .ZN(_040_)
  );
  INV_X1 _072_ (
    .I(_040_),
    .ZN(_002_)
  );
  NOR3_X1 _073_ (
    .A1(state[5]),
    .A2(state[6]),
    .A3(state[3]),
    .ZN(_041_)
  );
  OAI21_X1 _074_ (
    .A1(eql),
    .A2(_041_),
    .B(_025_),
    .ZN(_004_)
  );
  NAND2_X1 _075_ (
    .A1(_024_),
    .A2(state[2]),
    .ZN(_042_)
  );
  NAND2_X1 _076_ (
    .A1(eql),
    .A2(state[6]),
    .ZN(_043_)
  );
  NAND2_X1 _077_ (
    .A1(_042_),
    .A2(_043_),
    .ZN(_005_)
  );
  NAND2_X1 _078_ (
    .A1(cont_eql),
    .A2(_042_),
    .ZN(_000_)
  );
  INV_X1 _079_ (
    .I(reset),
    .ZN(_007_)
  );
  INV_X1 _080_ (
    .I(reset),
    .ZN(_008_)
  );
  INV_X1 _081_ (
    .I(reset),
    .ZN(_009_)
  );
  INV_X1 _082_ (
    .I(reset),
    .ZN(_010_)
  );
  INV_X1 _083_ (
    .I(reset),
    .ZN(_011_)
  );
  INV_X1 _084_ (
    .I(reset),
    .ZN(_012_)
  );
  INV_X1 _085_ (
    .I(reset),
    .ZN(_013_)
  );
  INV_X1 _086_ (
    .I(reset),
    .ZN(_014_)
  );
  INV_X1 _087_ (
    .I(reset),
    .ZN(_015_)
  );
  INV_X1 _088_ (
    .I(reset),
    .ZN(_016_)
  );
  INV_X1 _089_ (
    .I(reset),
    .ZN(_017_)
  );
  DFFSNQ_X1 _090_ (
    .CLK(clock),
    .D(1'h0),
    .Q(state[0]),
    .SN(_006_)
  );
  DFFRNQ_X1 _091_ (
    .CLK(clock),
    .D(_001_),
    .Q(state[1]),
    .RN(_007_)
  );
  DFFRNQ_X1 _092_ (
    .CLK(clock),
    .D(_002_),
    .Q(state[2]),
    .RN(_008_)
  );
  DFFRNQ_X1 _093_ (
    .CLK(clock),
    .D(_044_[1]),
    .Q(state[3]),
    .RN(_009_)
  );
  DFFRNQ_X1 _094_ (
    .CLK(clock),
    .D(_004_),
    .Q(state[4]),
    .RN(_010_)
  );
  DFFRNQ_X1 _095_ (
    .CLK(clock),
    .D(_003_),
    .Q(state[5]),
    .RN(_011_)
  );
  DFFRNQ_X1 _096_ (
    .CLK(clock),
    .D(_005_),
    .Q(state[6]),
    .RN(_012_)
  );
  (* src = "b06.v:27.1-127.4" *)
  DFFRNQ_X1 _097_ (
    .CLK(clock),
    .D(_018_),
    .Q(uscite[1]),
    .RN(_013_)
  );
  (* src = "b06.v:27.1-127.4" *)
  DFFRNQ_X1 _098_ (
    .CLK(clock),
    .D(_019_),
    .Q(uscite[2]),
    .RN(_014_)
  );
  (* src = "b06.v:27.1-127.4" *)
  DFFRNQ_X1 _099_ (
    .CLK(clock),
    .D(_020_),
    .Q(cc_mux[1]),
    .RN(_015_)
  );
  (* src = "b06.v:27.1-127.4" *)
  DFFRNQ_X1 _100_ (
    .CLK(clock),
    .D(_021_),
    .Q(cc_mux[2]),
    .RN(_016_)
  );
  (* src = "b06.v:27.1-127.4" *)
  DFFRNQ_X1 _101_ (
    .CLK(clock),
    .D(_000_),
    .Q(enable_count),
    .RN(_017_)
  );
  assign ackout = enable_count;
endmodule
