/*
    Automatically generated by Fault
    Do not modify.
    Generated on: 2026-03-30 16:48:09
*/
/* FAULT METADATA: '{"order":[{"width":1,"name":"START","kind":"input","ordinal":0},{"width":8,"name":"I","kind":"input","ordinal":0},{"width":1,"name":"_294_","kind":"dff","ordinal":0},{"width":1,"name":"_295_","kind":"dff","ordinal":0},{"width":1,"name":"_296_","kind":"dff","ordinal":0},{"width":1,"name":"_297_","kind":"dff","ordinal":0},{"width":1,"name":"_298_","kind":"dff","ordinal":0},{"width":1,"name":"_299_","kind":"dff","ordinal":0},{"width":1,"name":"_300_","kind":"dff","ordinal":0},{"width":1,"name":"_301_","kind":"dff","ordinal":0},{"width":1,"name":"_303_","kind":"dff","ordinal":0},{"width":1,"name":"_304_","kind":"dff","ordinal":0},{"width":1,"name":"_305_","kind":"dff","ordinal":0},{"width":1,"name":"_306_","kind":"dff","ordinal":0},{"width":1,"name":"_307_","kind":"dff","ordinal":0},{"width":1,"name":"_308_","kind":"dff","ordinal":0},{"width":1,"name":"_309_","kind":"dff","ordinal":0},{"width":1,"name":"_310_","kind":"dff","ordinal":0},{"width":1,"name":"_311_","kind":"dff","ordinal":0},{"width":1,"name":"_312_","kind":"dff","ordinal":0},{"width":1,"name":"_313_","kind":"dff","ordinal":0},{"width":1,"name":"_314_","kind":"dff","ordinal":0},{"width":1,"name":"_315_","kind":"dff","ordinal":0},{"width":1,"name":"_316_","kind":"dff","ordinal":0},{"width":1,"name":"_317_","kind":"dff","ordinal":0},{"width":1,"name":"_318_","kind":"dff","ordinal":0},{"width":1,"name":"_319_","kind":"dff","ordinal":0},{"width":1,"name":"_320_","kind":"dff","ordinal":0},{"width":1,"name":"_321_","kind":"dff","ordinal":0},{"width":4,"name":"O","kind":"output","ordinal":0}],"internalCount":27,"shift":"shift","sout":"sout","sin":"sin","boundaryCount":13}' END FAULT METADATA */
/* Generated by Yosys 0.58+35 (git sha1 9a12d9255, clang++ 18.1.3 -fPIC -O3) */

module b08_scan(CLOCK, RESET, START, I, O, sin, shift, sout, tck, test);
  input CLOCK;
  wire CLOCK;
  input RESET;
  wire RESET;
  input START;
  wire START;
  input [7:0] I;
  wire [7:0] I;
  output [3:0] O;
  wire [3:0] O;
  input sin;
  wire sin;
  input shift;
  wire shift;
  output sout;
  wire sout;
  input tck;
  wire tck;
  input test;
  wire test;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire \I__dout[0] ;
  wire \I__dout[1] ;
  wire \I__dout[2] ;
  wire \I__dout[3] ;
  wire \I__dout[4] ;
  wire \I__dout[5] ;
  wire \I__dout[6] ;
  wire \I__dout[7] ;
  wire \O_din[0] ;
  wire \O_din[1] ;
  wire \O_din[2] ;
  wire \O_din[3] ;
  wire START__dout;
  wire \__BoundaryScanRegister_input__0__.sout ;
  wire \__BoundaryScanRegister_input__1__.sout ;
  wire \__BoundaryScanRegister_input__2__.sout ;
  wire \__BoundaryScanRegister_input__3__.sout ;
  wire \__BoundaryScanRegister_input__4__.sout ;
  wire \__BoundaryScanRegister_input__5__.sout ;
  wire \__BoundaryScanRegister_input__6__.sout ;
  wire \__BoundaryScanRegister_input__7__.sout ;
  wire \__BoundaryScanRegister_input__8__.sout ;
  wire \__BoundaryScanRegister_output__10__.sin ;
  wire \__BoundaryScanRegister_output__10__.sout ;
  wire \__BoundaryScanRegister_output__11__.sout ;
  wire \__BoundaryScanRegister_output__9__.sin ;
  wire \__uuf__.IN_R[0] ;
  wire \__uuf__.IN_R[1] ;
  wire \__uuf__.IN_R[2] ;
  wire \__uuf__.IN_R[3] ;
  wire \__uuf__.IN_R[4] ;
  wire \__uuf__.IN_R[5] ;
  wire \__uuf__.IN_R[6] ;
  wire \__uuf__.IN_R[7] ;
  wire \__uuf__.MAR[0] ;
  wire \__uuf__.MAR[1] ;
  wire \__uuf__.MAR[2] ;
  wire \__uuf__.MAR[3] ;
  wire \__uuf__.MAR[4] ;
  wire \__uuf__.MAR[5] ;
  wire \__uuf__.MAR[6] ;
  wire \__uuf__.MAR[7] ;
  wire \__uuf__.OUT_R[0] ;
  wire \__uuf__.OUT_R[1] ;
  wire \__uuf__.OUT_R[2] ;
  wire \__uuf__.STATO[0] ;
  wire \__uuf__.STATO[1] ;
  wire \__uuf__.STATO[2] ;
  wire \__uuf__.STATO[3] ;
  wire \__uuf__._000_ ;
  wire \__uuf__._001_ ;
  wire \__uuf__._002_ ;
  wire \__uuf__._003_ ;
  wire \__uuf__._004_ ;
  wire \__uuf__._005_ ;
  wire \__uuf__._006_ ;
  wire \__uuf__._007_ ;
  wire \__uuf__._008_ ;
  wire \__uuf__._009_ ;
  wire \__uuf__._010_ ;
  wire \__uuf__._011_ ;
  wire \__uuf__._012_ ;
  wire \__uuf__._013_ ;
  wire \__uuf__._014_ ;
  wire \__uuf__._015_ ;
  wire \__uuf__._016_ ;
  wire \__uuf__._017_ ;
  wire \__uuf__._018_ ;
  wire \__uuf__._019_ ;
  wire \__uuf__._020_ ;
  wire \__uuf__._021_ ;
  wire \__uuf__._022_ ;
  wire \__uuf__._023_ ;
  wire \__uuf__._024_ ;
  wire \__uuf__._025_ ;
  wire \__uuf__._026_ ;
  wire \__uuf__._027_ ;
  wire \__uuf__._028_ ;
  wire \__uuf__._029_ ;
  wire \__uuf__._030_ ;
  wire \__uuf__._031_ ;
  wire \__uuf__._032_ ;
  wire \__uuf__._033_ ;
  wire \__uuf__._034_ ;
  wire \__uuf__._035_ ;
  wire \__uuf__._036_ ;
  wire \__uuf__._037_ ;
  wire \__uuf__._038_ ;
  wire \__uuf__._039_ ;
  wire \__uuf__._040_ ;
  wire \__uuf__._041_ ;
  wire \__uuf__._042_ ;
  wire \__uuf__._043_ ;
  wire \__uuf__._044_ ;
  wire \__uuf__._045_ ;
  wire \__uuf__._046_ ;
  wire \__uuf__._047_ ;
  wire \__uuf__._048_ ;
  wire \__uuf__._049_ ;
  wire \__uuf__._050_ ;
  wire \__uuf__._051_ ;
  wire \__uuf__._052_ ;
  wire \__uuf__._053_ ;
  wire \__uuf__._054_ ;
  wire \__uuf__._055_ ;
  wire \__uuf__._056_ ;
  wire \__uuf__._057_ ;
  wire \__uuf__._058_ ;
  wire \__uuf__._059_ ;
  wire \__uuf__._060_ ;
  wire \__uuf__._061_ ;
  wire \__uuf__._062_ ;
  wire \__uuf__._063_ ;
  wire \__uuf__._064_ ;
  wire \__uuf__._065_ ;
  wire \__uuf__._066_ ;
  wire \__uuf__._067_ ;
  wire \__uuf__._068_ ;
  wire \__uuf__._069_ ;
  wire \__uuf__._070_ ;
  wire \__uuf__._071_ ;
  wire \__uuf__._072_ ;
  wire \__uuf__._073_ ;
  wire \__uuf__._074_ ;
  wire \__uuf__._075_ ;
  wire \__uuf__._076_ ;
  wire \__uuf__._077_ ;
  wire \__uuf__._078_ ;
  wire \__uuf__._079_ ;
  wire \__uuf__._080_ ;
  wire \__uuf__._081_ ;
  wire \__uuf__._082_ ;
  wire \__uuf__._083_ ;
  wire \__uuf__._084_ ;
  wire \__uuf__._085_ ;
  wire \__uuf__._086_ ;
  wire \__uuf__._087_ ;
  wire \__uuf__._088_ ;
  wire \__uuf__._089_ ;
  wire \__uuf__._090_ ;
  wire \__uuf__._091_ ;
  wire \__uuf__._092_ ;
  wire \__uuf__._093_ ;
  wire \__uuf__._094_ ;
  wire \__uuf__._095_ ;
  wire \__uuf__._096_ ;
  wire \__uuf__._097_ ;
  wire \__uuf__._098_ ;
  wire \__uuf__._099_ ;
  wire \__uuf__._100_ ;
  wire \__uuf__._101_ ;
  wire \__uuf__._102_ ;
  wire \__uuf__._103_ ;
  wire \__uuf__._104_ ;
  wire \__uuf__._105_ ;
  wire \__uuf__._106_ ;
  wire \__uuf__._107_ ;
  wire \__uuf__._108_ ;
  wire \__uuf__._109_ ;
  wire \__uuf__._110_ ;
  wire \__uuf__._111_ ;
  wire \__uuf__._112_ ;
  wire \__uuf__._113_ ;
  wire \__uuf__._114_ ;
  wire \__uuf__._115_ ;
  wire \__uuf__._116_ ;
  wire \__uuf__._117_ ;
  wire \__uuf__._118_ ;
  wire \__uuf__._119_ ;
  wire \__uuf__._120_ ;
  wire \__uuf__._121_ ;
  wire \__uuf__._122_ ;
  wire \__uuf__._123_ ;
  wire \__uuf__._124_ ;
  wire \__uuf__._125_ ;
  wire \__uuf__._126_ ;
  wire \__uuf__._127_ ;
  wire \__uuf__._128_ ;
  wire \__uuf__._129_ ;
  wire \__uuf__._130_ ;
  wire \__uuf__._131_ ;
  wire \__uuf__._132_ ;
  wire \__uuf__._133_ ;
  wire \__uuf__._134_ ;
  wire \__uuf__._135_ ;
  wire \__uuf__._136_ ;
  wire \__uuf__._137_ ;
  wire \__uuf__._138_ ;
  wire \__uuf__._139_ ;
  wire \__uuf__._140_ ;
  wire \__uuf__._141_ ;
  wire \__uuf__._142_ ;
  wire \__uuf__._143_ ;
  wire \__uuf__._144_ ;
  wire \__uuf__._145_ ;
  wire \__uuf__._146_ ;
  wire \__uuf__.__clk_source__ ;
  INV_X1 _053_ (
    .I(RESET),
    .ZN(_000_)
  );
  MUX2_X1 _054_ (
    .I0(START),
    .I1(\__BoundaryScanRegister_input__0__.sout ),
    .S(test),
    .Z(START__dout)
  );
  MUX2_X1 _055_ (
    .I0(START__dout),
    .I1(sin),
    .S(shift),
    .Z(_013_)
  );
  MUX2_X1 _056_ (
    .I0(I[0]),
    .I1(\__BoundaryScanRegister_input__1__.sout ),
    .S(test),
    .Z(\I__dout[0] )
  );
  MUX2_X1 _057_ (
    .I0(\I__dout[0] ),
    .I1(\__BoundaryScanRegister_input__0__.sout ),
    .S(shift),
    .Z(_014_)
  );
  MUX2_X1 _058_ (
    .I0(I[1]),
    .I1(\__BoundaryScanRegister_input__2__.sout ),
    .S(test),
    .Z(\I__dout[1] )
  );
  MUX2_X1 _059_ (
    .I0(\I__dout[1] ),
    .I1(\__BoundaryScanRegister_input__1__.sout ),
    .S(shift),
    .Z(_015_)
  );
  MUX2_X1 _060_ (
    .I0(I[2]),
    .I1(\__BoundaryScanRegister_input__3__.sout ),
    .S(test),
    .Z(\I__dout[2] )
  );
  MUX2_X1 _061_ (
    .I0(\I__dout[2] ),
    .I1(\__BoundaryScanRegister_input__2__.sout ),
    .S(shift),
    .Z(_016_)
  );
  MUX2_X1 _062_ (
    .I0(I[3]),
    .I1(\__BoundaryScanRegister_input__4__.sout ),
    .S(test),
    .Z(\I__dout[3] )
  );
  MUX2_X1 _063_ (
    .I0(\I__dout[3] ),
    .I1(\__BoundaryScanRegister_input__3__.sout ),
    .S(shift),
    .Z(_017_)
  );
  MUX2_X1 _064_ (
    .I0(I[4]),
    .I1(\__BoundaryScanRegister_input__5__.sout ),
    .S(test),
    .Z(\I__dout[4] )
  );
  MUX2_X1 _065_ (
    .I0(\I__dout[4] ),
    .I1(\__BoundaryScanRegister_input__4__.sout ),
    .S(shift),
    .Z(_018_)
  );
  MUX2_X1 _066_ (
    .I0(I[5]),
    .I1(\__BoundaryScanRegister_input__6__.sout ),
    .S(test),
    .Z(\I__dout[5] )
  );
  MUX2_X1 _067_ (
    .I0(\I__dout[5] ),
    .I1(\__BoundaryScanRegister_input__5__.sout ),
    .S(shift),
    .Z(_019_)
  );
  MUX2_X1 _068_ (
    .I0(I[6]),
    .I1(\__BoundaryScanRegister_input__7__.sout ),
    .S(test),
    .Z(\I__dout[6] )
  );
  MUX2_X1 _069_ (
    .I0(\I__dout[6] ),
    .I1(\__BoundaryScanRegister_input__6__.sout ),
    .S(shift),
    .Z(_020_)
  );
  MUX2_X1 _070_ (
    .I0(I[7]),
    .I1(\__BoundaryScanRegister_input__8__.sout ),
    .S(test),
    .Z(\I__dout[7] )
  );
  MUX2_X1 _071_ (
    .I0(\I__dout[7] ),
    .I1(\__BoundaryScanRegister_input__7__.sout ),
    .S(shift),
    .Z(_021_)
  );
  MUX2_X1 _072_ (
    .I0(\O_din[0] ),
    .I1(\__BoundaryScanRegister_output__9__.sin ),
    .S(shift),
    .Z(_025_)
  );
  MUX2_X1 _073_ (
    .I0(\O_din[1] ),
    .I1(\__BoundaryScanRegister_output__10__.sin ),
    .S(shift),
    .Z(_022_)
  );
  MUX2_X1 _074_ (
    .I0(\O_din[2] ),
    .I1(\__BoundaryScanRegister_output__10__.sout ),
    .S(shift),
    .Z(_023_)
  );
  MUX2_X1 _075_ (
    .I0(\O_din[3] ),
    .I1(\__BoundaryScanRegister_output__11__.sout ),
    .S(shift),
    .Z(_024_)
  );
  MUX2_X1 _076_ (
    .I0(CLOCK),
    .I1(tck),
    .S(test),
    .Z(\__uuf__.__clk_source__ )
  );
  MUX2_X1 _077_ (
    .I0(\__uuf__._055_ ),
    .I1(\__uuf__.OUT_R[2] ),
    .S(shift),
    .Z(_052_)
  );
  MUX2_X1 _078_ (
    .I0(\__uuf__._054_ ),
    .I1(\__uuf__.OUT_R[1] ),
    .S(shift),
    .Z(_051_)
  );
  MUX2_X1 _079_ (
    .I0(\__uuf__._053_ ),
    .I1(\__uuf__.OUT_R[0] ),
    .S(shift),
    .Z(_050_)
  );
  MUX2_X1 _080_ (
    .I0(\__uuf__._052_ ),
    .I1(\__uuf__.IN_R[7] ),
    .S(shift),
    .Z(_049_)
  );
  MUX2_X1 _081_ (
    .I0(\__uuf__._051_ ),
    .I1(\__uuf__.IN_R[6] ),
    .S(shift),
    .Z(_048_)
  );
  MUX2_X1 _082_ (
    .I0(\__uuf__._050_ ),
    .I1(\__uuf__.IN_R[5] ),
    .S(shift),
    .Z(_047_)
  );
  MUX2_X1 _083_ (
    .I0(\__uuf__._049_ ),
    .I1(\__uuf__.IN_R[4] ),
    .S(shift),
    .Z(_046_)
  );
  MUX2_X1 _084_ (
    .I0(\__uuf__._048_ ),
    .I1(\__uuf__.IN_R[3] ),
    .S(shift),
    .Z(_045_)
  );
  MUX2_X1 _085_ (
    .I0(\__uuf__._047_ ),
    .I1(\__uuf__.IN_R[2] ),
    .S(shift),
    .Z(_044_)
  );
  MUX2_X1 _086_ (
    .I0(\__uuf__._046_ ),
    .I1(\__uuf__.IN_R[1] ),
    .S(shift),
    .Z(_043_)
  );
  MUX2_X1 _087_ (
    .I0(\__uuf__._045_ ),
    .I1(\__uuf__.IN_R[0] ),
    .S(shift),
    .Z(_042_)
  );
  MUX2_X1 _088_ (
    .I0(\__uuf__._044_ ),
    .I1(\O_din[3] ),
    .S(shift),
    .Z(_041_)
  );
  MUX2_X1 _089_ (
    .I0(\__uuf__._043_ ),
    .I1(\O_din[2] ),
    .S(shift),
    .Z(_040_)
  );
  MUX2_X1 _090_ (
    .I0(\__uuf__._042_ ),
    .I1(\O_din[1] ),
    .S(shift),
    .Z(_039_)
  );
  MUX2_X1 _091_ (
    .I0(\__uuf__._041_ ),
    .I1(\O_din[0] ),
    .S(shift),
    .Z(_038_)
  );
  MUX2_X1 _092_ (
    .I0(\__uuf__._040_ ),
    .I1(\__uuf__.STATO[3] ),
    .S(shift),
    .Z(_037_)
  );
  MUX2_X1 _093_ (
    .I0(\__uuf__._003_ ),
    .I1(\__uuf__.STATO[2] ),
    .S(shift),
    .Z(_036_)
  );
  MUX2_X1 _094_ (
    .I0(\__uuf__._000_ ),
    .I1(\__uuf__.STATO[1] ),
    .S(shift),
    .Z(_035_)
  );
  MUX2_X1 _095_ (
    .I0(\__uuf__._002_ ),
    .I1(\__uuf__.MAR[7] ),
    .S(shift),
    .Z(_034_)
  );
  MUX2_X1 _096_ (
    .I0(\__uuf__._039_ ),
    .I1(\__uuf__.MAR[6] ),
    .S(shift),
    .Z(_033_)
  );
  MUX2_X1 _097_ (
    .I0(\__uuf__._038_ ),
    .I1(\__uuf__.MAR[5] ),
    .S(shift),
    .Z(_032_)
  );
  MUX2_X1 _098_ (
    .I0(\__uuf__._037_ ),
    .I1(\__uuf__.MAR[4] ),
    .S(shift),
    .Z(_031_)
  );
  MUX2_X1 _099_ (
    .I0(\__uuf__._036_ ),
    .I1(\__uuf__.MAR[3] ),
    .S(shift),
    .Z(_030_)
  );
  MUX2_X1 _100_ (
    .I0(\__uuf__._035_ ),
    .I1(\__uuf__.MAR[2] ),
    .S(shift),
    .Z(_029_)
  );
  MUX2_X1 _101_ (
    .I0(\__uuf__._034_ ),
    .I1(\__uuf__.MAR[1] ),
    .S(shift),
    .Z(_028_)
  );
  MUX2_X1 _102_ (
    .I0(\__uuf__._033_ ),
    .I1(\__uuf__.MAR[0] ),
    .S(shift),
    .Z(_027_)
  );
  MUX2_X1 _103_ (
    .I0(\__uuf__._032_ ),
    .I1(\__BoundaryScanRegister_input__8__.sout ),
    .S(shift),
    .Z(_026_)
  );
  INV_X1 _104_ (
    .I(RESET),
    .ZN(_001_)
  );
  INV_X1 _105_ (
    .I(RESET),
    .ZN(_002_)
  );
  INV_X1 _106_ (
    .I(RESET),
    .ZN(_003_)
  );
  INV_X1 _107_ (
    .I(RESET),
    .ZN(_004_)
  );
  INV_X1 _108_ (
    .I(RESET),
    .ZN(_005_)
  );
  INV_X1 _109_ (
    .I(RESET),
    .ZN(_006_)
  );
  INV_X1 _110_ (
    .I(RESET),
    .ZN(_007_)
  );
  INV_X1 _111_ (
    .I(RESET),
    .ZN(_008_)
  );
  INV_X1 _112_ (
    .I(RESET),
    .ZN(_009_)
  );
  INV_X1 _113_ (
    .I(RESET),
    .ZN(_010_)
  );
  INV_X1 _114_ (
    .I(RESET),
    .ZN(_011_)
  );
  INV_X1 _115_ (
    .I(RESET),
    .ZN(_012_)
  );
  DFFRNQ_X1 _116_ (
    .CLK(tck),
    .D(_022_),
    .Q(\__BoundaryScanRegister_output__10__.sout ),
    .RN(_000_)
  );
  DFFRNQ_X1 _117_ (
    .CLK(tck),
    .D(_023_),
    .Q(\__BoundaryScanRegister_output__11__.sout ),
    .RN(_001_)
  );
  DFFRNQ_X1 _118_ (
    .CLK(tck),
    .D(_025_),
    .Q(\__BoundaryScanRegister_output__10__.sin ),
    .RN(_002_)
  );
  DFFRNQ_X1 _119_ (
    .CLK(tck),
    .D(_024_),
    .Q(sout),
    .RN(_003_)
  );
  DFFRNQ_X1 _120_ (
    .CLK(tck),
    .D(_021_),
    .Q(\__BoundaryScanRegister_input__8__.sout ),
    .RN(_004_)
  );
  DFFRNQ_X1 _121_ (
    .CLK(tck),
    .D(_013_),
    .Q(\__BoundaryScanRegister_input__0__.sout ),
    .RN(_005_)
  );
  DFFRNQ_X1 _122_ (
    .CLK(tck),
    .D(_014_),
    .Q(\__BoundaryScanRegister_input__1__.sout ),
    .RN(_006_)
  );
  DFFRNQ_X1 _123_ (
    .CLK(tck),
    .D(_015_),
    .Q(\__BoundaryScanRegister_input__2__.sout ),
    .RN(_007_)
  );
  DFFRNQ_X1 _124_ (
    .CLK(tck),
    .D(_016_),
    .Q(\__BoundaryScanRegister_input__3__.sout ),
    .RN(_008_)
  );
  DFFRNQ_X1 _125_ (
    .CLK(tck),
    .D(_017_),
    .Q(\__BoundaryScanRegister_input__4__.sout ),
    .RN(_009_)
  );
  DFFRNQ_X1 _126_ (
    .CLK(tck),
    .D(_018_),
    .Q(\__BoundaryScanRegister_input__5__.sout ),
    .RN(_010_)
  );
  DFFRNQ_X1 _127_ (
    .CLK(tck),
    .D(_019_),
    .Q(\__BoundaryScanRegister_input__6__.sout ),
    .RN(_011_)
  );
  DFFRNQ_X1 _128_ (
    .CLK(tck),
    .D(_020_),
    .Q(\__BoundaryScanRegister_input__7__.sout ),
    .RN(_012_)
  );
  NAND2_X1 \__uuf__._147_  (
    .A1(\__uuf__.STATO[2] ),
    .A2(\I__dout[0] ),
    .ZN(\__uuf__._116_ )
  );
  NAND2_X1 \__uuf__._148_  (
    .A1(\__uuf__._142_ ),
    .A2(\__uuf__.IN_R[0] ),
    .ZN(\__uuf__._117_ )
  );
  NAND2_X1 \__uuf__._149_  (
    .A1(\__uuf__._116_ ),
    .A2(\__uuf__._117_ ),
    .ZN(\__uuf__._044_ )
  );
  NOR2_X1 \__uuf__._150_  (
    .A1(\__uuf__.MAR[5] ),
    .A2(\__uuf__.MAR[3] ),
    .ZN(\__uuf__._118_ )
  );
  NOR3_X1 \__uuf__._151_  (
    .A1(\__uuf__.MAR[7] ),
    .A2(\__uuf__.MAR[6] ),
    .A3(\__uuf__.MAR[4] ),
    .ZN(\__uuf__._119_ )
  );
  NAND3_X1 \__uuf__._152_  (
    .A1(\__uuf__._079_ ),
    .A2(\__uuf__._118_ ),
    .A3(\__uuf__._119_ ),
    .ZN(\__uuf__._120_ )
  );
  OR2_X1 \__uuf__._153_  (
    .A1(\__uuf__._062_ ),
    .A2(\__uuf__._120_ ),
    .Z(\__uuf__._121_ )
  );
  NOR2_X1 \__uuf__._154_  (
    .A1(START__dout),
    .A2(\__uuf__._121_ ),
    .ZN(\__uuf__._122_ )
  );
  MUX2_X1 \__uuf__._155_  (
    .I0(\O_din[3] ),
    .I1(\__BoundaryScanRegister_output__9__.sin ),
    .S(\__uuf__._122_ ),
    .Z(\__uuf__._043_ )
  );
  MUX2_X1 \__uuf__._156_  (
    .I0(\O_din[2] ),
    .I1(\__uuf__.OUT_R[2] ),
    .S(\__uuf__._122_ ),
    .Z(\__uuf__._042_ )
  );
  MUX2_X1 \__uuf__._157_  (
    .I0(\O_din[1] ),
    .I1(\__uuf__.OUT_R[1] ),
    .S(\__uuf__._122_ ),
    .Z(\__uuf__._041_ )
  );
  MUX2_X1 \__uuf__._158_  (
    .I0(\O_din[0] ),
    .I1(\__uuf__.OUT_R[0] ),
    .S(\__uuf__._122_ ),
    .Z(\__uuf__._040_ )
  );
  AND3_X1 \__uuf__._159_  (
    .A1(\__uuf__.MAR[4] ),
    .A2(\__uuf__.MAR[3] ),
    .A3(\__uuf__._079_ ),
    .Z(\__uuf__._123_ )
  );
  NAND2_X1 \__uuf__._160_  (
    .A1(\__uuf__.MAR[5] ),
    .A2(\__uuf__._123_ ),
    .ZN(\__uuf__._124_ )
  );
  NAND3_X1 \__uuf__._161_  (
    .A1(\__uuf__.MAR[5] ),
    .A2(\__uuf__.STATO[3] ),
    .A3(\__uuf__._123_ ),
    .ZN(\__uuf__._125_ )
  );
  NAND2_X1 \__uuf__._162_  (
    .A1(\__uuf__._146_ ),
    .A2(\__uuf__.MAR[6] ),
    .ZN(\__uuf__._126_ )
  );
  NAND3_X1 \__uuf__._163_  (
    .A1(\__uuf__.MAR[6] ),
    .A2(\__uuf__.MAR[5] ),
    .A3(\__uuf__._123_ ),
    .ZN(\__uuf__._127_ )
  );
  NAND2_X1 \__uuf__._164_  (
    .A1(\__uuf__.STATO[3] ),
    .A2(\__uuf__._120_ ),
    .ZN(\__uuf__._128_ )
  );
  NAND2_X1 \__uuf__._165_  (
    .A1(\__uuf__.STATO[2] ),
    .A2(\__uuf__._062_ ),
    .ZN(\__uuf__._129_ )
  );
  AND2_X1 \__uuf__._166_  (
    .A1(\__uuf__._128_ ),
    .A2(\__uuf__._129_ ),
    .Z(\__uuf__._130_ )
  );
  NAND2_X1 \__uuf__._167_  (
    .A1(\__uuf__._128_ ),
    .A2(\__uuf__._129_ ),
    .ZN(\__uuf__._131_ )
  );
  NAND2_X1 \__uuf__._168_  (
    .A1(\__uuf__.STATO[3] ),
    .A2(\__uuf__._124_ ),
    .ZN(\__uuf__._132_ )
  );
  AOI21_X1 \__uuf__._169_  (
    .A1(\__uuf__.STATO[3] ),
    .A2(\__uuf__._127_ ),
    .B(\__uuf__._130_ ),
    .ZN(\__uuf__._133_ )
  );
  OAI22_X1 \__uuf__._170_  (
    .A1(\__uuf__._125_ ),
    .A2(\__uuf__._126_ ),
    .B1(\__uuf__._133_ ),
    .B2(\__uuf__._146_ ),
    .ZN(\__uuf__._039_ )
  );
  AOI21_X1 \__uuf__._171_  (
    .A1(\__uuf__._056_ ),
    .A2(\__uuf__._125_ ),
    .B(\__uuf__._133_ ),
    .ZN(\__uuf__._038_ )
  );
  AOI21_X1 \__uuf__._172_  (
    .A1(\__uuf__.STATO[3] ),
    .A2(\__uuf__._123_ ),
    .B(\__uuf__.MAR[5] ),
    .ZN(\__uuf__._134_ )
  );
  AOI21_X1 \__uuf__._173_  (
    .A1(\__uuf__._131_ ),
    .A2(\__uuf__._132_ ),
    .B(\__uuf__._134_ ),
    .ZN(\__uuf__._037_ )
  );
  NAND3_X1 \__uuf__._174_  (
    .A1(\__uuf__.MAR[3] ),
    .A2(\__uuf__.STATO[3] ),
    .A3(\__uuf__._079_ ),
    .ZN(\__uuf__._135_ )
  );
  NAND2_X1 \__uuf__._175_  (
    .A1(\__uuf__._129_ ),
    .A2(\__uuf__._135_ ),
    .ZN(\__uuf__._136_ )
  );
  NAND3_X1 \__uuf__._176_  (
    .A1(\__uuf__.MAR[4] ),
    .A2(\__uuf__._129_ ),
    .A3(\__uuf__._135_ ),
    .ZN(\__uuf__._137_ )
  );
  OAI21_X1 \__uuf__._177_  (
    .A1(\__uuf__.MAR[4] ),
    .A2(\__uuf__._135_ ),
    .B(\__uuf__._137_ ),
    .ZN(\__uuf__._036_ )
  );
  AOI21_X1 \__uuf__._178_  (
    .A1(\__uuf__._079_ ),
    .A2(\__uuf__._131_ ),
    .B(\__uuf__.MAR[3] ),
    .ZN(\__uuf__._138_ )
  );
  NOR2_X1 \__uuf__._179_  (
    .A1(\__uuf__._136_ ),
    .A2(\__uuf__._138_ ),
    .ZN(\__uuf__._035_ )
  );
  NAND2_X1 \__uuf__._180_  (
    .A1(\__uuf__.STATO[3] ),
    .A2(\__uuf__._090_ ),
    .ZN(\__uuf__._139_ )
  );
  OAI22_X1 \__uuf__._181_  (
    .A1(\__uuf__._057_ ),
    .A2(\__uuf__._131_ ),
    .B1(\__uuf__._139_ ),
    .B2(\__uuf__._068_ ),
    .ZN(\__uuf__._034_ )
  );
  AOI22_X1 \__uuf__._182_  (
    .A1(\__uuf__.STATO[3] ),
    .A2(\__uuf__._065_ ),
    .B1(\__uuf__._130_ ),
    .B2(\__uuf__.MAR[1] ),
    .ZN(\__uuf__._140_ )
  );
  INV_X1 \__uuf__._183_  (
    .I(\__uuf__._140_ ),
    .ZN(\__uuf__._033_ )
  );
  NAND2_X1 \__uuf__._184_  (
    .A1(\__uuf__._059_ ),
    .A2(\__uuf__.STATO[3] ),
    .ZN(\__uuf__._141_ )
  );
  OAI21_X1 \__uuf__._185_  (
    .A1(\__uuf__._059_ ),
    .A2(\__uuf__._131_ ),
    .B(\__uuf__._141_ ),
    .ZN(\__uuf__._032_ )
  );
  NOR2_X1 \__uuf__._186_  (
    .A1(\__uuf__._060_ ),
    .A2(\__uuf__._061_ ),
    .ZN(\__uuf__._000_ )
  );
  AOI21_X1 \__uuf__._187_  (
    .A1(\__uuf__._060_ ),
    .A2(\__uuf__._121_ ),
    .B(START__dout),
    .ZN(\__uuf__._001_ )
  );
  OAI21_X1 \__uuf__._188_  (
    .A1(\__uuf__._061_ ),
    .A2(\__uuf__._121_ ),
    .B(\__uuf__._063_ ),
    .ZN(\__uuf__._003_ )
  );
  NAND2_X1 \__uuf__._189_  (
    .A1(\__uuf__._142_ ),
    .A2(\__uuf__._128_ ),
    .ZN(\__uuf__._002_ )
  );
  INV_X1 \__uuf__._190_  (
    .I(RESET),
    .ZN(\__uuf__._005_ )
  );
  INV_X1 \__uuf__._191_  (
    .I(RESET),
    .ZN(\__uuf__._006_ )
  );
  INV_X1 \__uuf__._192_  (
    .I(RESET),
    .ZN(\__uuf__._007_ )
  );
  INV_X1 \__uuf__._193_  (
    .I(RESET),
    .ZN(\__uuf__._008_ )
  );
  INV_X1 \__uuf__._194_  (
    .I(RESET),
    .ZN(\__uuf__._009_ )
  );
  INV_X1 \__uuf__._195_  (
    .I(RESET),
    .ZN(\__uuf__._010_ )
  );
  INV_X1 \__uuf__._196_  (
    .I(RESET),
    .ZN(\__uuf__._011_ )
  );
  INV_X1 \__uuf__._197_  (
    .I(RESET),
    .ZN(\__uuf__._012_ )
  );
  INV_X1 \__uuf__._198_  (
    .I(RESET),
    .ZN(\__uuf__._013_ )
  );
  INV_X1 \__uuf__._199_  (
    .I(RESET),
    .ZN(\__uuf__._014_ )
  );
  INV_X1 \__uuf__._200_  (
    .I(RESET),
    .ZN(\__uuf__._015_ )
  );
  INV_X1 \__uuf__._201_  (
    .I(RESET),
    .ZN(\__uuf__._016_ )
  );
  INV_X1 \__uuf__._202_  (
    .I(RESET),
    .ZN(\__uuf__._017_ )
  );
  INV_X1 \__uuf__._203_  (
    .I(RESET),
    .ZN(\__uuf__._018_ )
  );
  INV_X1 \__uuf__._204_  (
    .I(RESET),
    .ZN(\__uuf__._019_ )
  );
  INV_X1 \__uuf__._205_  (
    .I(RESET),
    .ZN(\__uuf__._020_ )
  );
  INV_X1 \__uuf__._206_  (
    .I(RESET),
    .ZN(\__uuf__._021_ )
  );
  INV_X1 \__uuf__._207_  (
    .I(RESET),
    .ZN(\__uuf__._022_ )
  );
  INV_X1 \__uuf__._208_  (
    .I(RESET),
    .ZN(\__uuf__._023_ )
  );
  INV_X1 \__uuf__._209_  (
    .I(RESET),
    .ZN(\__uuf__._024_ )
  );
  INV_X1 \__uuf__._210_  (
    .I(RESET),
    .ZN(\__uuf__._025_ )
  );
  INV_X1 \__uuf__._211_  (
    .I(RESET),
    .ZN(\__uuf__._026_ )
  );
  INV_X1 \__uuf__._212_  (
    .I(RESET),
    .ZN(\__uuf__._027_ )
  );
  INV_X1 \__uuf__._213_  (
    .I(RESET),
    .ZN(\__uuf__._028_ )
  );
  INV_X1 \__uuf__._214_  (
    .I(RESET),
    .ZN(\__uuf__._029_ )
  );
  INV_X1 \__uuf__._215_  (
    .I(RESET),
    .ZN(\__uuf__._030_ )
  );
  INV_X1 \__uuf__._216_  (
    .I(RESET),
    .ZN(\__uuf__._031_ )
  );
  INV_X1 \__uuf__._217_  (
    .I(\__uuf__.STATO[2] ),
    .ZN(\__uuf__._142_ )
  );
  INV_X1 \__uuf__._218_  (
    .I(\__uuf__.IN_R[3] ),
    .ZN(\__uuf__._143_ )
  );
  INV_X1 \__uuf__._219_  (
    .I(\__uuf__.IN_R[2] ),
    .ZN(\__uuf__._144_ )
  );
  INV_X1 \__uuf__._220_  (
    .I(\__uuf__.IN_R[1] ),
    .ZN(\__uuf__._145_ )
  );
  INV_X1 \__uuf__._221_  (
    .I(\__uuf__.MAR[7] ),
    .ZN(\__uuf__._146_ )
  );
  INV_X1 \__uuf__._222_  (
    .I(\__uuf__.MAR[6] ),
    .ZN(\__uuf__._056_ )
  );
  INV_X1 \__uuf__._223_  (
    .I(\__uuf__.MAR[2] ),
    .ZN(\__uuf__._057_ )
  );
  INV_X1 \__uuf__._224_  (
    .I(\__uuf__.MAR[1] ),
    .ZN(\__uuf__._058_ )
  );
  INV_X1 \__uuf__._225_  (
    .I(\__uuf__.MAR[0] ),
    .ZN(\__uuf__._059_ )
  );
  INV_X1 \__uuf__._226_  (
    .I(\__uuf__.STATO[0] ),
    .ZN(\__uuf__._060_ )
  );
  INV_X1 \__uuf__._227_  (
    .I(START__dout),
    .ZN(\__uuf__._061_ )
  );
  INV_X1 \__uuf__._228_  (
    .I(\__uuf__.STATO[3] ),
    .ZN(\__uuf__._062_ )
  );
  INV_X1 \__uuf__._229_  (
    .I(\__uuf__.STATO[1] ),
    .ZN(\__uuf__._063_ )
  );
  INV_X1 \__uuf__._230_  (
    .I(RESET),
    .ZN(\__uuf__._004_ )
  );
  NAND2_X1 \__uuf__._231_  (
    .A1(\__uuf__.MAR[1] ),
    .A2(\__uuf__._059_ ),
    .ZN(\__uuf__._064_ )
  );
  XOR2_X1 \__uuf__._232_  (
    .A1(\__uuf__.MAR[1] ),
    .A2(\__uuf__.MAR[0] ),
    .Z(\__uuf__._065_ )
  );
  AND2_X1 \__uuf__._233_  (
    .A1(\__uuf__._057_ ),
    .A2(\__uuf__._065_ ),
    .Z(\__uuf__._066_ )
  );
  NAND2_X1 \__uuf__._234_  (
    .A1(\__uuf__.IN_R[1] ),
    .A2(\__uuf__._066_ ),
    .ZN(\__uuf__._067_ )
  );
  NOR2_X1 \__uuf__._235_  (
    .A1(\__uuf__.MAR[2] ),
    .A2(\__uuf__.MAR[0] ),
    .ZN(\__uuf__._068_ )
  );
  NOR3_X1 \__uuf__._236_  (
    .A1(\__uuf__.IN_R[0] ),
    .A2(\__uuf__.MAR[1] ),
    .A3(\__uuf__._068_ ),
    .ZN(\__uuf__._069_ )
  );
  NOR3_X1 \__uuf__._237_  (
    .A1(\__uuf__.IN_R[5] ),
    .A2(\__uuf__.MAR[2] ),
    .A3(\__uuf__.MAR[1] ),
    .ZN(\__uuf__._070_ )
  );
  NOR4_X1 \__uuf__._238_  (
    .A1(\__uuf__.IN_R[4] ),
    .A2(\__uuf__.MAR[2] ),
    .A3(\__uuf__._058_ ),
    .A4(\__uuf__._059_ ),
    .ZN(\__uuf__._071_ )
  );
  NAND2_X1 \__uuf__._239_  (
    .A1(\__uuf__.MAR[2] ),
    .A2(\__uuf__._058_ ),
    .ZN(\__uuf__._072_ )
  );
  XOR2_X1 \__uuf__._240_  (
    .A1(\__uuf__.MAR[2] ),
    .A2(\__uuf__.MAR[1] ),
    .Z(\__uuf__._073_ )
  );
  NAND3_X1 \__uuf__._241_  (
    .A1(\__uuf__._144_ ),
    .A2(\__uuf__.MAR[0] ),
    .A3(\__uuf__._073_ ),
    .ZN(\__uuf__._074_ )
  );
  NAND3_X1 \__uuf__._242_  (
    .A1(\__uuf__.IN_R[0] ),
    .A2(\__uuf__.MAR[1] ),
    .A3(\__uuf__._059_ ),
    .ZN(\__uuf__._075_ )
  );
  NAND3_X1 \__uuf__._243_  (
    .A1(\__uuf__.STATO[1] ),
    .A2(\__uuf__._074_ ),
    .A3(\__uuf__._075_ ),
    .ZN(\__uuf__._076_ )
  );
  NOR4_X1 \__uuf__._244_  (
    .A1(\__uuf__._069_ ),
    .A2(\__uuf__._070_ ),
    .A3(\__uuf__._071_ ),
    .A4(\__uuf__._076_ ),
    .ZN(\__uuf__._077_ )
  );
  NOR2_X1 \__uuf__._245_  (
    .A1(\__uuf__._057_ ),
    .A2(\__uuf__._059_ ),
    .ZN(\__uuf__._078_ )
  );
  AND3_X1 \__uuf__._246_  (
    .A1(\__uuf__.MAR[2] ),
    .A2(\__uuf__.MAR[1] ),
    .A3(\__uuf__.MAR[0] ),
    .Z(\__uuf__._079_ )
  );
  OAI21_X1 \__uuf__._247_  (
    .A1(\__uuf__._066_ ),
    .A2(\__uuf__._079_ ),
    .B(\__uuf__.IN_R[6] ),
    .ZN(\__uuf__._080_ )
  );
  NOR3_X1 \__uuf__._248_  (
    .A1(\__uuf__._057_ ),
    .A2(\__uuf__._058_ ),
    .A3(\__uuf__.MAR[0] ),
    .ZN(\__uuf__._081_ )
  );
  XOR2_X1 \__uuf__._249_  (
    .A1(\__uuf__.MAR[2] ),
    .A2(\__uuf__.MAR[0] ),
    .Z(\__uuf__._082_ )
  );
  NOR3_X1 \__uuf__._250_  (
    .A1(\__uuf__.IN_R[6] ),
    .A2(\__uuf__.MAR[1] ),
    .A3(\__uuf__._082_ ),
    .ZN(\__uuf__._083_ )
  );
  AOI21_X1 \__uuf__._251_  (
    .A1(\__uuf__._145_ ),
    .A2(\__uuf__._081_ ),
    .B(\__uuf__._083_ ),
    .ZN(\__uuf__._084_ )
  );
  NAND2_X1 \__uuf__._252_  (
    .A1(\__uuf__.IN_R[5] ),
    .A2(\__uuf__._081_ ),
    .ZN(\__uuf__._085_ )
  );
  OAI21_X1 \__uuf__._253_  (
    .A1(\__uuf__._058_ ),
    .A2(\__uuf__.MAR[0] ),
    .B(\__uuf__._057_ ),
    .ZN(\__uuf__._086_ )
  );
  NAND3_X1 \__uuf__._254_  (
    .A1(\__uuf__.IN_R[4] ),
    .A2(\__uuf__._072_ ),
    .A3(\__uuf__._086_ ),
    .ZN(\__uuf__._087_ )
  );
  AND4_X1 \__uuf__._255_  (
    .A1(\__uuf__._080_ ),
    .A2(\__uuf__._084_ ),
    .A3(\__uuf__._085_ ),
    .A4(\__uuf__._087_ ),
    .Z(\__uuf__._088_ )
  );
  AOI21_X1 \__uuf__._256_  (
    .A1(\__uuf__.MAR[1] ),
    .A2(\__uuf__._082_ ),
    .B(\__uuf__.IN_R[7] ),
    .ZN(\__uuf__._089_ )
  );
  AOI21_X1 \__uuf__._257_  (
    .A1(\__uuf__._057_ ),
    .A2(\__uuf__._058_ ),
    .B(\__uuf__._079_ ),
    .ZN(\__uuf__._090_ )
  );
  AOI21_X1 \__uuf__._258_  (
    .A1(\__uuf__.IN_R[7] ),
    .A2(\__uuf__._090_ ),
    .B(\__uuf__._089_ ),
    .ZN(\__uuf__._091_ )
  );
  NAND2_X1 \__uuf__._259_  (
    .A1(\__uuf__.IN_R[2] ),
    .A2(\__uuf__._065_ ),
    .ZN(\__uuf__._092_ )
  );
  OAI21_X1 \__uuf__._260_  (
    .A1(\__uuf__.MAR[2] ),
    .A2(\__uuf__._058_ ),
    .B(\__uuf__._143_ ),
    .ZN(\__uuf__._093_ )
  );
  AOI21_X1 \__uuf__._261_  (
    .A1(\__uuf__._092_ ),
    .A2(\__uuf__._093_ ),
    .B(\__uuf__._078_ ),
    .ZN(\__uuf__._094_ )
  );
  NOR2_X1 \__uuf__._262_  (
    .A1(\__uuf__._091_ ),
    .A2(\__uuf__._094_ ),
    .ZN(\__uuf__._095_ )
  );
  NAND4_X1 \__uuf__._263_  (
    .A1(\__uuf__._067_ ),
    .A2(\__uuf__._077_ ),
    .A3(\__uuf__._088_ ),
    .A4(\__uuf__._095_ ),
    .ZN(\__uuf__._096_ )
  );
  NOR2_X1 \__uuf__._264_  (
    .A1(\__uuf__._059_ ),
    .A2(\__uuf__._073_ ),
    .ZN(\__uuf__._097_ )
  );
  NAND2_X1 \__uuf__._265_  (
    .A1(\__uuf__.STATO[2] ),
    .A2(\__uuf__._063_ ),
    .ZN(\__uuf__._098_ )
  );
  NAND2_X1 \__uuf__._266_  (
    .A1(\__BoundaryScanRegister_output__9__.sin ),
    .A2(\__uuf__._098_ ),
    .ZN(\__uuf__._099_ )
  );
  OAI21_X1 \__uuf__._267_  (
    .A1(\__uuf__._096_ ),
    .A2(\__uuf__._097_ ),
    .B(\__uuf__._099_ ),
    .ZN(\__uuf__._055_ )
  );
  NAND2_X1 \__uuf__._268_  (
    .A1(\__uuf__.OUT_R[2] ),
    .A2(\__uuf__._098_ ),
    .ZN(\__uuf__._100_ )
  );
  AOI21_X1 \__uuf__._269_  (
    .A1(\__uuf__._058_ ),
    .A2(\__uuf__.MAR[0] ),
    .B(\__uuf__._081_ ),
    .ZN(\__uuf__._101_ )
  );
  NAND2_X1 \__uuf__._270_  (
    .A1(\__uuf__._086_ ),
    .A2(\__uuf__._101_ ),
    .ZN(\__uuf__._102_ )
  );
  OAI21_X1 \__uuf__._271_  (
    .A1(\__uuf__._096_ ),
    .A2(\__uuf__._102_ ),
    .B(\__uuf__._100_ ),
    .ZN(\__uuf__._054_ )
  );
  NAND2_X1 \__uuf__._272_  (
    .A1(\__uuf__.OUT_R[1] ),
    .A2(\__uuf__._098_ ),
    .ZN(\__uuf__._103_ )
  );
  OAI21_X1 \__uuf__._273_  (
    .A1(\__uuf__._078_ ),
    .A2(\__uuf__._096_ ),
    .B(\__uuf__._103_ ),
    .ZN(\__uuf__._053_ )
  );
  NAND2_X1 \__uuf__._274_  (
    .A1(\__uuf__.OUT_R[0] ),
    .A2(\__uuf__._098_ ),
    .ZN(\__uuf__._104_ )
  );
  OAI21_X1 \__uuf__._275_  (
    .A1(\__uuf__._064_ ),
    .A2(\__uuf__._096_ ),
    .B(\__uuf__._104_ ),
    .ZN(\__uuf__._052_ )
  );
  NAND2_X1 \__uuf__._276_  (
    .A1(\I__dout[7] ),
    .A2(\__uuf__.STATO[2] ),
    .ZN(\__uuf__._105_ )
  );
  NAND2_X1 \__uuf__._277_  (
    .A1(\__uuf__.IN_R[7] ),
    .A2(\__uuf__._142_ ),
    .ZN(\__uuf__._106_ )
  );
  NAND2_X1 \__uuf__._278_  (
    .A1(\__uuf__._105_ ),
    .A2(\__uuf__._106_ ),
    .ZN(\__uuf__._051_ )
  );
  NAND2_X1 \__uuf__._279_  (
    .A1(\__uuf__.STATO[2] ),
    .A2(\I__dout[6] ),
    .ZN(\__uuf__._107_ )
  );
  NAND2_X1 \__uuf__._280_  (
    .A1(\__uuf__._142_ ),
    .A2(\__uuf__.IN_R[6] ),
    .ZN(\__uuf__._108_ )
  );
  NAND2_X1 \__uuf__._281_  (
    .A1(\__uuf__._107_ ),
    .A2(\__uuf__._108_ ),
    .ZN(\__uuf__._050_ )
  );
  NAND2_X1 \__uuf__._282_  (
    .A1(\__uuf__.STATO[2] ),
    .A2(\I__dout[5] ),
    .ZN(\__uuf__._109_ )
  );
  NAND2_X1 \__uuf__._283_  (
    .A1(\__uuf__._142_ ),
    .A2(\__uuf__.IN_R[5] ),
    .ZN(\__uuf__._110_ )
  );
  NAND2_X1 \__uuf__._284_  (
    .A1(\__uuf__._109_ ),
    .A2(\__uuf__._110_ ),
    .ZN(\__uuf__._049_ )
  );
  NAND2_X1 \__uuf__._285_  (
    .A1(\__uuf__.STATO[2] ),
    .A2(\I__dout[4] ),
    .ZN(\__uuf__._111_ )
  );
  NAND2_X1 \__uuf__._286_  (
    .A1(\__uuf__._142_ ),
    .A2(\__uuf__.IN_R[4] ),
    .ZN(\__uuf__._112_ )
  );
  NAND2_X1 \__uuf__._287_  (
    .A1(\__uuf__._111_ ),
    .A2(\__uuf__._112_ ),
    .ZN(\__uuf__._048_ )
  );
  NAND2_X1 \__uuf__._288_  (
    .A1(\__uuf__.STATO[2] ),
    .A2(\I__dout[3] ),
    .ZN(\__uuf__._113_ )
  );
  OAI21_X1 \__uuf__._289_  (
    .A1(\__uuf__.STATO[2] ),
    .A2(\__uuf__._143_ ),
    .B(\__uuf__._113_ ),
    .ZN(\__uuf__._047_ )
  );
  NAND2_X1 \__uuf__._290_  (
    .A1(\__uuf__.STATO[2] ),
    .A2(\I__dout[2] ),
    .ZN(\__uuf__._114_ )
  );
  OAI21_X1 \__uuf__._291_  (
    .A1(\__uuf__.STATO[2] ),
    .A2(\__uuf__._144_ ),
    .B(\__uuf__._114_ ),
    .ZN(\__uuf__._046_ )
  );
  NAND2_X1 \__uuf__._292_  (
    .A1(\__uuf__.STATO[2] ),
    .A2(\I__dout[1] ),
    .ZN(\__uuf__._115_ )
  );
  OAI21_X1 \__uuf__._293_  (
    .A1(\__uuf__.STATO[2] ),
    .A2(\__uuf__._145_ ),
    .B(\__uuf__._115_ ),
    .ZN(\__uuf__._045_ )
  );
  DFFRNQ_X1 \__uuf__._294_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_026_),
    .Q(\__uuf__.MAR[0] ),
    .RN(\__uuf__._004_ )
  );
  DFFRNQ_X1 \__uuf__._295_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_027_),
    .Q(\__uuf__.MAR[1] ),
    .RN(\__uuf__._005_ )
  );
  DFFRNQ_X1 \__uuf__._296_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_028_),
    .Q(\__uuf__.MAR[2] ),
    .RN(\__uuf__._006_ )
  );
  DFFRNQ_X1 \__uuf__._297_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_029_),
    .Q(\__uuf__.MAR[3] ),
    .RN(\__uuf__._007_ )
  );
  DFFRNQ_X1 \__uuf__._298_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_030_),
    .Q(\__uuf__.MAR[4] ),
    .RN(\__uuf__._008_ )
  );
  DFFRNQ_X1 \__uuf__._299_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_031_),
    .Q(\__uuf__.MAR[5] ),
    .RN(\__uuf__._009_ )
  );
  DFFRNQ_X1 \__uuf__._300_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_032_),
    .Q(\__uuf__.MAR[6] ),
    .RN(\__uuf__._010_ )
  );
  DFFRNQ_X1 \__uuf__._301_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_033_),
    .Q(\__uuf__.MAR[7] ),
    .RN(\__uuf__._011_ )
  );
  DFFSNQ_X1 \__uuf__._302_  (
    .CLK(CLOCK),
    .D(\__uuf__._001_ ),
    .Q(\__uuf__.STATO[0] ),
    .SN(\__uuf__._012_ )
  );
  DFFRNQ_X1 \__uuf__._303_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_034_),
    .Q(\__uuf__.STATO[1] ),
    .RN(\__uuf__._013_ )
  );
  DFFRNQ_X1 \__uuf__._304_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_035_),
    .Q(\__uuf__.STATO[2] ),
    .RN(\__uuf__._014_ )
  );
  DFFRNQ_X1 \__uuf__._305_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_036_),
    .Q(\__uuf__.STATO[3] ),
    .RN(\__uuf__._015_ )
  );
  DFFRNQ_X1 \__uuf__._306_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_037_),
    .Q(\O_din[0] ),
    .RN(\__uuf__._016_ )
  );
  DFFRNQ_X1 \__uuf__._307_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_038_),
    .Q(\O_din[1] ),
    .RN(\__uuf__._017_ )
  );
  DFFRNQ_X1 \__uuf__._308_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_039_),
    .Q(\O_din[2] ),
    .RN(\__uuf__._018_ )
  );
  DFFRNQ_X1 \__uuf__._309_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_040_),
    .Q(\O_din[3] ),
    .RN(\__uuf__._019_ )
  );
  DFFRNQ_X1 \__uuf__._310_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_041_),
    .Q(\__uuf__.IN_R[0] ),
    .RN(\__uuf__._020_ )
  );
  DFFRNQ_X1 \__uuf__._311_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_042_),
    .Q(\__uuf__.IN_R[1] ),
    .RN(\__uuf__._021_ )
  );
  DFFRNQ_X1 \__uuf__._312_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_043_),
    .Q(\__uuf__.IN_R[2] ),
    .RN(\__uuf__._022_ )
  );
  DFFRNQ_X1 \__uuf__._313_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_044_),
    .Q(\__uuf__.IN_R[3] ),
    .RN(\__uuf__._023_ )
  );
  DFFRNQ_X1 \__uuf__._314_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_045_),
    .Q(\__uuf__.IN_R[4] ),
    .RN(\__uuf__._024_ )
  );
  DFFRNQ_X1 \__uuf__._315_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_046_),
    .Q(\__uuf__.IN_R[5] ),
    .RN(\__uuf__._025_ )
  );
  DFFRNQ_X1 \__uuf__._316_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_047_),
    .Q(\__uuf__.IN_R[6] ),
    .RN(\__uuf__._026_ )
  );
  DFFRNQ_X1 \__uuf__._317_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_048_),
    .Q(\__uuf__.IN_R[7] ),
    .RN(\__uuf__._027_ )
  );
  DFFRNQ_X1 \__uuf__._318_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_049_),
    .Q(\__uuf__.OUT_R[0] ),
    .RN(\__uuf__._028_ )
  );
  DFFRNQ_X1 \__uuf__._319_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_050_),
    .Q(\__uuf__.OUT_R[1] ),
    .RN(\__uuf__._029_ )
  );
  DFFRNQ_X1 \__uuf__._320_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_051_),
    .Q(\__uuf__.OUT_R[2] ),
    .RN(\__uuf__._030_ )
  );
  DFFRNQ_X1 \__uuf__._321_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_052_),
    .Q(\__BoundaryScanRegister_output__9__.sin ),
    .RN(\__uuf__._031_ )
  );
  assign O = { \O_din[3] , \O_din[2] , \O_din[1] , \O_din[0]  };
endmodule

